### ISSUE TITLE
Activity section on error when a user plays synchronized music.

### ISSUE THREAD

**Issue by naisspas** [Tautulli/Tautulli-Issues#103]
**Version:**
2.1.14
**Branch:**
master
**Commit hash:**
7eee7024b6eac0a858748664878d146bf63623b4
**Operating system:**

Linux 4.14.49-unRAID (#1 SMP Mon Jun 11 16:21:07 PDT 2018)
**Python version:**
2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?**
Access to webUI, home tab

**What happened?**
Error "There was an error communicating with your Plex Server. Check the logs and verify your server connection in the settings." on the "Activity" section.
 Logs are full of :
```
2018-07-23 11:03:00 - WARNING :: Thread-3 : Failed to access uri endpoint /sync/items/26001158. Status code 404
2018-07-23 11:03:00 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: 'NoneType' object has no attribute 'getElementsByTagName'.
```

**What you expected?**
Display activity / users playing

**How can we reproduce your issue?**

The error occurs when a user plays synchronized music from an Android device. Once he stopped, the activity section works again.

**What are your (relevant) settings?**

**Link to logs:**
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/2219852/tautulli.log)

**Comment by naisspas** [comment]
Strangely everything works again. I refreshed my own synchronized media on my phone, disconnected / reconnected my Plex account, and everything is back in working order.
I noticed that under the interface of Plex Web, certain synchronized items appeared with an "unknown" state, and that the logs of the web page showed errors close to those of the logs of tautulli.

**Comment by spuniun** [comment]
I too noticed this started occurring immediately after upgrading to PMS 1.13.4.5271 last week.

**Comment by spuniun** [comment]
So it seems this is an issue upstream with PMS. After any service restart, I must go into Plex Web > Activity > Sync > Refresh to get the synced items to be accessible via API again.

**Comment by spuniun** [comment]
FYI, I have confirmed this is an upstream bug after fully rebuilding my PMS library per Chuck's demand.
