### ISSUE TITLE
Viewing Tautulli home on Chrome when the browser is windowed, the Activity subtitle is hidden

### ISSUE THREAD

**Issue by soaringswine** [Tautulli/Tautulli-Issues#104]
**Version:**
VERSION V2.1.17-BETA
**Branch:**
Beta
**Commit hash:**
89d1a5782ae3153e810f716114a65276b0d8749f
**Operating system:**
Windows 10 (10.0.17134)
**Python version:**
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
**What you did?**
Browse to Tautulli home page, and place Chrome into a smaller window.
**What happened?**
The Activity subtitle (with number of streams and bandwidth info) is hidden by the black Tautulli title bar.
**What you expected?**
That the Activity subtitle is shown. It is shown fine in Internet Explorer and Edge with the same windowed geometry.
**How can we reproduce your issue?**
Open Tautulli homepage in Chrome and resize the browser window to 1024x575 and you'll see the Activity subtitle is cut off.

**Comment by Arcanemagus** [comment]
That is literally the last thing to hide:
![image](https://user-images.githubusercontent.com/427137/43281239-0d42c908-90c8-11e8-868a-51c7c6372ad8.png)

Any further and you only have the title bar. Please post a screenshot of what you are talking about.

**Comment by soaringswine** [comment]
![image](https://user-images.githubusercontent.com/19174853/43291254-c4b1d2c4-90fe-11e8-8cb3-f335f6d763cc.png)

if I increase the width by about 5 pixels, the Activity part unhides.

**Comment by soaringswine** [comment]
actually, surprisingly, its only a small range of widths that it hides, if I make it _narrower_ it unhides, and if it I make it _wider_, it also unhides.
