### ISSUE TITLE
Script Notification agent doesn't run: Tautulli NotificationHandler :: Notification thread exception: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ronilaukkarinen** [Tautulli/Tautulli-Issues#106]
Getting this error no matter what:

````
Tautulli NotificationHandler :: Notification thread exception: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last): 
    File "/opt/plexpy/plexpy/notification_handler.py", line 61, in process_queue 
        add_notifier_each(**params) 
    File "/opt/plexpy/plexpy/notification_handler.py", line 117, in add_notifier_each 
        if manual_trigger or notify_custom_conditions(notifier_id=notifier['id'], parameters=parameters): 
    File "/opt/plexpy/plexpy/notification_handler.py", line 215, in notify_custom_conditions 
        custom_conditions_logic = notifier_config['custom_conditions_logic'] 
TypeError: 'NoneType' object has no attribute '__getitem__'
````

My test script is quite simple, this will run on command line and print out any parameters:

```` python
#/usr/bin/python
import os
import sys
import time
import pylast
import subprocess

#artist = sys.argv[1] 
#album = sys.argv[2] 
#title = sys.argv[3]
#duration = sys.argv[3]

#network.update_now_playing(artist = artist, album = album, title = title, duration = duration)
print("Updated now playing successfully.")

# Tests
#print('{0} {1} {2} {3}'.format(artist, album, title, duration))
````

Details:

**Version:** 2.1.18
**Branch:** master
**Commit hash:** a8a676b79496b4dc3dea9596dfd09a4eeeae60e0
**Operating system:** Linux 4.13.16-100.fc25.x86_64 (#1 SMP Mon Nov 27 19:52:46 UTC 2017 - Fedora 25 Twenty Five)
**Python version:** 2.7.13 (default, Dec 1 2017, 09:21:53) [GCC 6.4.1 20170727 (Red Hat 6.4.1-1)]
**What you did?** Added a custom python script with conditions, triggers and arguments
**What happened?** Error in log
**What you expected?** The script to run

**How can we reproduce your issue?**
Add a custom python script with conditions, triggers and arguments

**Link to logs:**
https://rolle.design/tautulli_2.log

**Comment by ronilaukkarinen** [comment]
I think this is strongly related to [my other issue](https://github.com/Tautulli/Tautulli-Issues/issues/105) because I can't remove other agents...

When I edit the existing agent Scripts (bash) it works. But newer python side Scripts are currently broken. How to remove them manually?

**Comment by Arcanemagus** [comment]
https://github.com/Tautulli/Tautulli-Issues/issues/105#issuecomment-409002249

**Comment by ronilaukkarinen** [comment]
Yeah, so related. Closing this as useless/solved issue.
