### ISSUE TITLE
Error sending gmail with two factor enabled and app password correct. 

### ISSUE THREAD

**Issue by Reedler01** [Tautulli/Tautulli-Issues#107]
**Version:VERSION V2.1.18**

**Branch:master**

**Commit hash:a8a676b79496b4dc3dea9596dfd09a4eeeae60e0**

**Operating system:Centos 7 latest updates**

--

Linux 3.10.0-862.9.1.el7.x86_64 (#1 SMP Mon Jul 16 16:29:36 UTC 2018 - CentOS Linux 7.5.1804 Core)

**Python version:2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]**
--

**What you did?Tried revoking and recreating several gmail app passwords. I tested on another app. (my home apc ups unit and worked fine)**

**What happened?Unable to send notifications to gmail**

**What you expected?To rec a test email from this app**

**How can we reproduce your issue?Try using one of your gmail adressess with two factor enabled and a gmail app generated pw**

**What are your (relevant) settings? from name: Tautulli 
from email address: 'my gmail address'
smtp server: smtp.gmail.com
port: 587
TLS: checked
smtp user name: 'my gmail address'
smtp user pw: 'my gmail app generated pw'**

**Link to logs:https://gist.github.com/Reedler01/b4471c0c6f1aafa86cf9ff6a215d3c2f**

**Comment by Arcanemagus** [comment]
Your version of Python is positively _ancient_, please update to v2.7.15 before trying again.

As issues are not the place where support requests are handled if you are still having issues after updating your Python version please hop into the #support channel in the [Discord server](https://tautulli.com/discord.html) and we can help you out further there.
