### ISSUE TITLE
Email Notification doesn't work

### ISSUE THREAD

**Issue by ochbob** [Tautulli/Tautulli-Issues#108]
**Version: v2.1.18**

**Branch: master**

**Operating system: Debian Stretch**

**Python version: 2.7.13**

**What happened?**
Error when sendind email notification

**Log:**

> Tautulli NotificationHandler :: Notification thread exception: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128)
Traceback (most recent call last):
    File "/opt/plexpy/plexpy/notification_handler.py", line 59, in process_queue
        notify(**params)
    File "/opt/plexpy/plexpy/notification_handler.py", line 375, in notify
        **kwargs)
    File "/opt/plexpy/plexpy/notifiers.py", line 605, in send_notification
        **kwargs)
    File "/opt/plexpy/plexpy/notifiers.py", line 785, in notify
        return self.agent_notify(subject=subject, body=body, action=action, **kwargs)
    File "/opt/plexpy/plexpy/notifiers.py", line 1333, in agent_notify
        logger.error(u"Tautulli Notifiers :: {name} notification failed: {e}".format(name=self.NAME, e=e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 55: ordinal not in range(128) 

Any idea ?

Thank you :)

**Comment by ochbob** [comment]
Any thought about this ?

If you need more info, let me know.

**Comment by coolfarmer** [comment]
Damn I have the same problem, exactly the same error. Have you find a solution? I work on this problem since 8 hours.

**Comment by coolfarmer** [comment]
I want to help because I have the exact same problem with the same error. Here is my information:

**Version:** 2.1.26

**Operating system:** Windows 10 (10.0.17134)

**Python version:** 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

**What you did?** Already updated Tautulli to the last version, restart the server, analyze my logs to find if the error can be solved by myself but can't find a solution. I have talked with a support guys on your Discord and I think he can't help me...

**What happened?** I can't send any email via the email notification agent. I setup correctly the form with basic information such my name, my email, my smtp server (with my gmail and working credencials). Every time I click on the button to send a test email, I got a "Notification Failed" in my notification logs and an exception in Tautulli logs.

Here is the exception in my log:
```
Tautulli NotificationHandler :: Notification thread exception: 'ascii' codec can't decode byte 0xe9 in position 43: ordinal not in range(128)
Traceback (most recent call last): 
    File "C:\Tautulli\plexpy\notification_handler.py", line 58, in process_queue 
        notify(**params) 
    File "C:\Tautulli\plexpy\notification_handler.py", line 369, in notify 
        **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 630, in send_notification 
        **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 810, in notify 
        return self.agent_notify(subject=subject, body=body, action=action, **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 1366, in agent_notify 
        logger.error(u"Tautulli Notifiers :: {name} notification failed: {e}".format(name=self.NAME, e=e)) 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 43: ordinal not in range(128)
```

**What are your (relevant) settings?** Nothing special here, almost all on default value.

**Link to logs:**
https://gist.github.com/coolfarmer/a5d4be40af40c52156428e5df4e16c3a

**Images:**
 - https://i.imgur.com/DQigYOw.png
 - https://i.imgur.com/FE6z3Zf.png
 - https://i.imgur.com/UEx0dan.png

I really want to find out a solution, if I can help you with testing something or if I can give you more infos, just tell me what.

Thanks!

**Comment by ochbob** [comment]
Thank you for this :)

@JonnyWong16 what kind of information did you need ?

Just let me know, i will provide to you.

**Comment by coolfarmer** [comment]
@ochbob , I just find a way to bypass their email agent while we're waiting for a fix. Create a new applet on IFTTT.com with a WebHook's trigger. Complete the form then go on Tautulli, create a new notif agent with IFTTT and fill the form with the correct details like event name.

Then on IFTTT, you have to choose an action like sending an email (or other service). In my case, I have a notif agent IFTTT who send an web request on my WebHook, then the Webhook call Buffer (and on my Buffer account I create a facebook post in my selected group).

Sorry english is not my main language, hope you understand :)

**Comment by JonnyWong16** [comment]
If you are still experience this issue, could you please try switching to the `nightly` branch to test.

**Comment by ochbob** [comment]
Hello,

I still encounter the issue, but yes it's more clear now:

> Tautulli Notifiers :: Email notification failed: Connection unexpectedly closed: [Errno 104] Connexion ré-initialisée par le correspondant

I use the same settings from Ombi and it works great, so i'm sure my smtp settings are good, and smtp server works great.
I use  my ISP (Orange) smtp (not google or outlook smtp)

**Comment by JonnyWong16** [comment]
You finally provided some useful info, your SMTP settings.

It looks like the info provided by your ISP is not correct. `smtp.orange.fr` does not have a mail server on port `465`.

```
telnet smtp.orange.fr 465
Trying 193.252.22.86...
Connected to smtp.orange.fr.
Escape character is '^]'.
Connection closed by foreign host.
```

It does however have a mail server on port `587`, but it does not look like it uses TLS.

```
telnet smtp.orange.fr 587
Trying 193.252.22.86...
Connected to smtp.orange.fr.
Escape character is '^]'.
220 mwinf5d36 ME ESMTP server ready
EHLO test.example.com   
250-mwinf5d36 hello [216.71.200.229], pleased to meet you
250-HELP
250-AUTH LOGIN PLAIN
250-SIZE 44000000
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 OK
QUIT
221 2.0.0 mwinf5d36 ME closing connection
Connection closed by foreign host.
```

Here is Gmail, for example, which is on port `587` with TLS.

```
telnet smtp.gmail.com 587
Trying 74.125.20.109...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP r29sm22082291pga.62 - gsmtp
EHLO test.example.com
250-smtp.gmail.com at your service, [216.71.200.229]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS          <-------------- Gmail uses TLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
QUIT
221 2.0.0 closing connection r29sm22082291pga.62 - gsmtp
Connection closed by foreign host.
```

I have no idea what Ombi is doing, but it's not connecting to where you think it is.

This is no longer a Tautulli bug report, so I am closing this issue. It is just a misconfigured SMTP server.

**Comment by ochbob** [comment]
Hum, seems very odd, from Orange support:

https://assistance.orange.fr/mobile-tablette/tous-les-mobiles-et-tablettes/installer-et-utiliser/utiliser-internet-mail-et-cloud/mail/l-application-mail-orange/parametrer-et-configurer/mail-configurer-les-serveurs-sortants-et-entrants-des-principaux-comptes-mails_47992-48856#onglet2

> Orange/Wanadoo | orange.fr /wanadoo.fr | smtp.orange.fr | 465 | SSL | Oui*

I use this settings in Ombi / roundcube / etc...

Will look arround.

Thnak you anyway.
