### ISSUE TITLE
Error with PushBullet notification agent configuration

### ISSUE THREAD

**Issue by krazykrazz** [Tautulli/Tautulli-Issues#109]
**Version:**
2.1.18

**Branch:**
master

**Commit hash:**
a8a676b79496b4dc3dea9596dfd09a4eeeae60e0

**Operating system:**
Windows 8 (6.2.9200)

**Python version:**
2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]

**What you did?**
Try to create or modify a PushBullet notification agent.

**What happened?**
1) For create - it creates, but then cannot be opened.
2) For existing - cannot load
**What you expected?**
PushBullet notification agent to be created correctly.
**How can we reproduce your issue?**
1) Create a new PushBullet notification agent
2) Add token
3) Save
4) Attempt to load or modify

**What are your (relevant) settings?**
- I dropped the notifiers table and restarted but this did not correct the problem.

**Link to logs:**

2018-08-01 08:42:18 | ERROR | Tautulli  Notifiers :: Failed to get notifier config options:  HTTPSConnectionPool(host='api.pushbullet.com', port=443): Max retries  exceeded with url: /v2/devices (Caused by SSLError(SSLError(8,  '_ssl.c:510: EOF occurred in violation of protocol'),)).

**Comment by JonnyWong16** [comment]
Update your version of Python. Current latest version of Python 2.7 is 2.7.15.

**Comment by krazykrazz** [comment]
Thanks for the quick reply. I'll try that and let you know the results.

**Comment by krazykrazz** [comment]
Resolved with Python update to 2.7.15
