### ISSUE TITLE
Does not support current version of sqlite

### ISSUE THREAD

**Issue by CrispinP** [Tautulli/Tautulli-Issues#110]
I've installed the latest version of everything in a freenas jail. 
pkg upgrade and update.
When running the Python scripts I have get the following
`root@Tautulli:/usr/local/share/Tautulli # python2 Tautulli.py
Traceback (most recent call last):
  File "Tautulli.py", line 35, in <module>
    import plexpy
  File "/usr/local/share/Tautulli/plexpy/__init__.py", line 18, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: /usr/local/lib/libsqlite3.so.0: Undefined symbol "fdatasync"`

I believe this is related to sqlite version. Radarr has the same issue.

**Comment by Arcanemagus** [comment]
This is an issue with the `sqlite3` installation in your jail, and nothing to do with Tautulli itself.

**Comment by Arcanemagus** [comment]
It looks like you are trying to use the 11.1 version of `libsqlite3.so` in a 11.0 based jail from [this bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221672).

Try rebuilding your jail in an `iocage` jail based on 11.1.

(`py27-sqlite3-2.7.15_7` is working perfectly fine in my 11.1 based jail.)
