### ISSUE TITLE
get_history api - started timestamp wrong when playing completed

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli-Issues#112]
**Version:** v2.1.18-beta
**Branch:** beta
**Commit hash:** a8a676b79496b4dc3dea9596dfd09a4eeeae60e0
**Operating system:** Linux 4.15.0-24-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Called `get_history` api as shown in the api docs while item is playing, wait until playing completes (or next entry in list starts) and call api again
**What happened?** `started` timstamp is correct while playing, but jumps ~1 month into past after playing completed
**What you expected?** Started timestamp shouldn't change
**How can we reproduce your issue?** See above.

**Comment by samwiseg00** [comment]
I am trying to replicate. Does it have to be a new item?

**Comment by tfonfara** [comment]
I actually reproduced it with a non-new item, but seems that this happens randomly, for a lot of items I get correct timestamps (testing with tracks).

**Comment by samwiseg00** [comment]
Interesting... that is why the few time I tried it seemed to work just fine.

**Comment by tfonfara** [comment]
This is what I get for example:
```
started: 1527189393
paused_counter: 270
duration: 5031
date: 1534415262
percent_complete: 100
stopped: 1534418435
```
I'll have an eye on that to find out how to reproduce it.

**Comment by samwiseg00** [comment]
@tfonfara If you turn off "Group Play History" in Settings --> General. Do you still see the issue?

**Comment by tfonfara** [comment]
@samwiseg00 nope, when turned off the timestamp is correct (even for previously wrong timestamps)

**Comment by samwiseg00** [comment]
After looking into it. It's not a bug but by design. What you are seeing is the start time of the first grouped item. With grouping enabled it will display the start item of the first history item. You can disable grouping by adding `grouping=0` as referenced in the API docs below. You can also use `grouping=0&reference_id=XYZ` to get the sub table.

https://github.com/Tautulli/Tautulli/blob/master/API.md#get_history

**Comment by tfonfara** [comment]
Got it, thanks!
