### ISSUE TITLE
Option to Disable Certificate Check for emails

### ISSUE THREAD

**Issue by JigSawFr** [Tautulli/Tautulli-Issues#114]
**Version:** v2.1.19-beta

**Branch:** beta

**Commit hash:** 4f397b032ee50111f5bff477dd9a0481bce63c67

**Operating system:** Docker

**What happened?** Error if problems with certificate

**What you expected?** Add an option to disable certification check while sending email through TLS

Thank you

**Comment by Arcanemagus** [comment]
This isn't a bug in Tautulli.

Please read the instructions for [Feature Requests](https://github.com/Tautulli/Tautulli-Issues#feature-requests). Alternatively, just get a [valid certificate](https://letsencrypt.org/) for your email server 😉.
