### ISSUE TITLE
Get Tautulli version number via api

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli-Issues#116]
**Version:** v2.1.19-beta
**Branch:** beta
**Commit hash:** 4f397b032ee50111f5bff477dd9a0481bce63c67
**Operating system:** Linux 4.15.0-24-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Called `get_settings` api
**What happened?** PMS version is included, but Tautulli version is not
**What you expected?** Tautulli version number (e.g. v2.1.19-beta or v2.1.18) should appear in General section same as for PMS in pms_version.

**Comment by JonnyWong16** [comment]
Not a bug report. Version is not stored in the config file. Feature request instead.
