### ISSUE TITLE
Script Notifier: Script files aren't showing

### ISSUE THREAD

**Issue by kylemart** [Tautulli/Tautulli-Issues#117]
**Version:**
2.1.18

**Branch:**
master

**Commit hash:**
a8a676b79496b4dc3dea9596dfd09a4eeeae60e0

**Operating system:**
Linux 4.9.0-0.bpo.6-amd64 (#1 SMP Debian 4.9.82-1+deb9u3~bpo8+1 (2018-03-22))

**Python version:**
2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]

**What you did?**
First I created a directory called "scripts" in the root directory of my machine and placed a python script inside. (My instance of Tautulli is running inside a docker container, so really I binded "/scripts" to a directory on my host disk.) In Tautulli I went to Settings -> Notification Agents -> Add a new notification agent -> Script. I then typed "/scripts" (without quotes) into the Script Folder text box, and selected the Script File dropdown.

**What happened?**
Nothing was listed in the Script File dropdown.

**What you expected?**
I expected the python script to appear in the dropdown.

**What are your (relevant) settings?**
My Tautulli instance is contained within a docker container: https://hub.docker.com/r/linuxserver/tautulli/.

**Link to logs:**
https://gist.github.com/kylemart/f05fe546c4a14a90eeb1a42c0b54d0b8

**Comment by Arcanemagus** [comment]
If you open a shell in that container, does it actually show the files there? Are the permissions correct for the user Tautulli is running as to access the files?

**Comment by kylemart** [comment]
Yes and yes. 

Interestingly the issue seems to have gone away. I had restarted Tautulli and the container multiple times, but each time the issue persisted. After rebooting my entire machine, however, the issue went away. Odd :-/
