### ISSUE TITLE
Typo in systemd scirpt

### ISSUE THREAD

**Issue by ldumont** [Tautulli/Tautulli-Issues#119]
**Version:**
2.1.20
**Branch:**
master
**Commit hash:**
4944ce1ca05af75efd8ad5df30cf537ae43bace0
**Operating system:**

Linux 4.17.0-0.bpo.3-amd64 (#1 SMP Debian 4.17.17-1~bpo9+1 (2018-08-27) - debian 9.5)
**Python version:**
 2.7.13 (default, Nov 24 2017, 17:33:09)  [GCC 6.3.0 20170516]
**What you did?**
Update Tautulli from interface
**What happened?**
Tautulli doesn't start anymore
**What you expected?**
Tautulli should start
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

There is a typo in the new systemd script regarding the permission group:
https://github.com/Tautulli/Tautulli/commit/a48ebef9ae426588d0f3e233c1ed6fb3d87656e1

I think it should be tautulli and not tautlli.

**Comment by JonnyWong16** [comment]
Fixed in #1308.
