### ISSUE TITLE
Content Rating conditions don't work

### ISSUE THREAD

**Issue by Arcanemagus** [Tautulli/Tautulli-Issues#122]
**Version:**
v2.1.20

**Branch:**
`nightly`

**Commit hash:**
https://github.com/Tautulli/Tautulli/commit/9b8fb73a7afa5cafd0b427db0acc637e3e775feb

**Operating system:**
`FreeBSD 11.1-STABLE (FreeBSD 11.1-STABLE #0 r321665+9902d126c39(freenas/11.1-stable): Tue Aug 21 12:24:37 EDT 2018 root@nemesis.tn.ixsystems.com:/freenas-11-releng/freenas/_BE/objs/freenas-11-releng/freenas/_BE/os/sys/FreeNAS.amd64)`

**Python version:**
`2.7.15 (default, May 13 2018, 01:10:00) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`

**What you did?**
Added a Notification Agent that uses a Custom Condition on the Content Rating of the stream. For example, attempting to limit it to only trigger when the stream has a Content Rating of `R`:
![image](https://user-images.githubusercontent.com/427137/45775254-07b51880-bc04-11e8-810e-5d7a827ee7fd.png)

**What happened?**
The condition _always_ evaluates to `True`, no matter what rating the stream is.

**What you expected?**
The condition to properly check against the Content Rating of the stream.

**How can we reproduce your issue?**
1. Create a Notification Agent with a trigger (e.g. Playback Start)
2. Add a Condition that checks against the Content Rating
3. Play a stream that triggers the agent

**What are your (relevant) settings?**
See above.

**Link to logs:**
[tautulli.log](https://gist.github.com/Arcanemagus/28b4c1166bd36f34da836d47f664157e)

**Comment by goku-son** [comment]
I am running v2.1.21 but can’t get this to work. I suspect that I am simply using it incorrectly.  

Here is my goal, I have two users that I would like to get notified if they play something with a content rating of ‘R’ or ‘NR-17’. 

Here are my settings:
![8c35d9d0-146e-4133-b4f2-0ee915b5439e](https://user-images.githubusercontent.com/20881936/45929838-efebd600-bf1c-11e8-92ff-c615489bb38f.png)
![68f98379-6883-4c16-96fa-2c9fe26ce409](https://user-images.githubusercontent.com/20881936/45929841-efebd600-bf1c-11e8-98fa-67652e464590.png)
![33fc2704-8831-4fdb-8ba5-4031fe90d9a7](https://user-images.githubusercontent.com/20881936/45929839-efebd600-bf1c-11e8-95c5-c77d0965df76.png)
![ca29bde5-fe91-4af4-b56b-17d2ae2002e8](https://user-images.githubusercontent.com/20881936/45929840-efebd600-bf1c-11e8-84b5-25358de146b8.png)

Any pointers as to what I can be doing wrong?

Thanks in advance.

**Comment by JonnyWong16** [comment]
GitHub issues are not the pace for support. Please use the [Discord Server](https://tautulli.com/discord).
