### ISSUE TITLE
Running behind a https proxy server results in a http redirect

### ISSUE THREAD

**Issue by hashworks** [Tautulli/Tautulli-Issues#123]
**Version:** v2.1.21
**Branch:** master
**Commit hash:** v2.1.21
**Operating system:** Linux 4.16.11-1-ARCH (# 1 SMP PREEMPT Tue May 22 21:40:27 UTC 2018)
**Python version:** 2.7.15 (default, Jun 27 2018, 13:05:28)  [GCC 8.1.1 20180531]

Calling `curl -D - https://tautulli.server.com` results in a HTTP redirect:
```
HTTP/2 302 
server: nginx
date: Mon, 24 Sep 2018 11:24:35 GMT
content-type: text/html;charset=utf-8
content-length: 165
location: http://tautulli.server.com:443/auth/logout?redirect_uri=/
vary: Accept-Encoding
[...]

This resource resides temporarily at <a href="http://tautulli.server.com/auth/logout?redirect_uri=/">http://tautulli.server.com/auth/logout?redirect_uri=/</a>.%      
```

In a browser this gets fixed since I'm using strict-transport-security, but of course there is nothing behind `http://tautulli.server.com/auth/logout`, resulting in a 404 with curl.

This is my nginx config:
```nginx
server {                                                                                               
        listen          127.0.0.1:443 ssl http2;
        listen          [::1]:443 ssl http2;
        server_name     tautulli.server.com;

        location / {
                proxy_pass http://127.0.0.1:8181;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_redirect ~^(http(?:s)?://)([^:/]+)(?::\d+)?(/.*)?$ $1$2:$server_port$3;
                proxy_read_timeout 90;
        }
[...]
}
```

This is my tautulli config: https://fb.hash.works/JvhIB/ini

**Comment by hashworks** [comment]
Notes: the wrong `location` directive seems to be from a wrong `proxy_redirect` setting. I used [the one from your FAQ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-how-can-i-access-tautulli-outside-my-home-network).

**Comment by hashworks** [comment]
Thanks!

**Comment by maran** [comment]
Had the same issue but this fixed it, thanks!
