### ISSUE TITLE
Slack Agent Notification Not Persisting Fields

### ISSUE THREAD

**Issue by eschizoid** [Tautulli/Tautulli-Issues#124]
**Version:**
VERSION V2.1.21

**Branch:**
master

**Commit hash:**
c8575bbc0fb7091e92f316628940acf3790f04da

**Operating system:**
Centos7

**Python version:**
2.7.5

**What you did?**
Enabled a Slack Notification Agent

**What happened?**
`Subject Line` and `Message Body` fields were not persisted

**What you expected?**
After enabling a slack notification agent, and clicking the button `save` all fields should be persisted

**How can we reproduce your issue?**
1. Create new slack notification agent
2. Change the text for `Subject Line` and `Message Body` fields
3. Click `save`
4. Refresh page
5. Check the field values for `Subject Line` and `Message Body` again, and the new values were persisted (even after restarting `Tautulli` process)

**What are your (relevant) settings?**
Slack Webhook URL
`https://hooks.slack.com/services/...`

**Link to logs:**
```
2018-09-26 16:58:45 - INFO    :: CP Server Thread-12 : Tautulli Notifiers :: Updated notification agent: Slack (notifier_id 3).
```

**Comment by eschizoid** [comment]
The Slack Notification Agent works fine (i can receive messages). However, when I change the title or message body these two fields are not persisted. From the logs, you can see that the process for saving the slack notification agent it's being triggered, but unfortunately, the information it's not persisted.

**Comment by Arcanemagus** [comment]
I'm unable to replicate this, so it isn't a bug with Tautulli itself. Please use one of the [support options](https://tautulli.com/#support), with the [Discord server](https://tautulli.com/discord) being preferred.

Thanks!
