### ISSUE TITLE
Please update Javascript libraries

### ISSUE THREAD

**Issue by GitGerby** [Tautulli/Tautulli-Issues#127]
**Version:** 2.1.21

**Branch:** Master

**Commit hash:** c8575bbc0fb7091e92f316628940acf3790f04da

**Operating system:**  
FreeBSD 11.2-RELEASE-p4 (FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018 root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC)

**Python version:** 2.7.15 (default, May 25 2018, 22:55:00) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]

**What you did?** Lighthouse Audit in Chrome developer tools

**What happened?** 3 Libraries have known vulnerabilities 

**What you expected?**  No vulnerabilities

**How can we reproduce your issue?**
1. Using Chrome log in to Tautulli
1. Open Chrome dev console (keyboard shortcut is ctrl + shift + j)
1. Select the Audits tab
1. Select 'Desktop' under Device
1. Ensure 'Best Practices' is selected under Audits
1. Click 'Run audits'
1. Scroll to 'Best Practices' and expand item 4 `Includes front-end JavaScript libraries with known security vulnerabilities`

**What are your (relevant) settings?**

**Link to logs:**

![image](https://user-images.githubusercontent.com/36684477/46411564-2c23f100-c6ea-11e8-9e1b-e19c14284490.png)

**Comment by JonnyWong16** [comment]
Acknowledged, but unlikely to be updated anytime soon because there are too many things that would also need to be updated just by upgrading the library versions.

**Comment by GitGerby** [comment]
Thanks, anything I can do to help let me know.

**Comment by shr00mie** [comment]
not sure if related, but as of the latest docker image, i'm no longer able to load History.

`2019-09-11 18:33:19 - ERROR :: CP Server Thread-13 : WebUI :: /history : Uncaught TypeError: Illegal invocation. (jquery-2.1.4.min.js:4)`

was working just fine until latest image. tried clearing temp sessions from DB to no avail.

let me know if you need any more info.
