### ISSUE TITLE
Twitter notifications?

### ISSUE THREAD

**Issue by joeyimage** [Tautulli/Tautulli-Issues#128]
**Version:** VERSION V2.1.21

**Branch:** master

**Commit hash:**  c8575bbc0fb7091e92f316628940acf3790f04da

**Operating system:** Win10 Pro 64
Windows 10 (10.0.17763)

**Python version:**2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]

**What you did?**
Setup Twitter notifications
**What happened?**
nothing
**What you expected?**
Twitter notifications

WHY do Twitter notifications stop working randomly? It will be fine for weeks, then suddenly nothing. I had to re-config this two days ago and now it has stopped again. I again re-config'ed it, and now even the Test tweets don't work.  "Aggravating" is an understatement.

**Comment by samwiseg00** [comment]
Your logs will need to be reviewed to understand what might be happening. 

Issues aren't the place for support, please use one of the [available options](https://tautulli.com/#support), with the [Discord server](https://tautulli.com/discord) being preferred.
