### ISSUE TITLE
XML error when attempting to refresh users list

### ISSUE THREAD

**Issue by chugcup** [Tautulli/Tautulli-Issues#130]
**Version:**
2.1.22
**Branch:**
master
**Commit hash:**
03751abc0e34575e2b57d9f0edb241303059ea97
**Operating system:**
Linux 3.10.105 (#23739 SMP Wed Jun 20 22:40:01 CST 2018)
**Python version:**
2.7.12 (default, Jul 3 2018, 19:55:39) [GCC 4.9.3 20150311 (prerelease)]
**What you did?**
Navigate to **Users**, click **Refresh Users**
**What happened?**
See "Refreshing users list..." popup, followed by "Unable to refresh users list." error
**What you expected?**
Expected users list to be updated successfully with new managed users.
**How can we reproduce your issue?**
Add a new Managed User in Plex Media Server, open Tautilli, navigate to **Users**, click **Refresh Users** button.

Inspecting the **Tautilli Logs** section under the *Logs* page I see the following parsing error:
`get_full_users_list: 'NoneType' object has no attribute 'getElementsByTagName'`

**What are your (relevant) settings?**
Not sure
**Link to logs:**
Relevant log messages
```
2018-10-08 15:24:41 | WARNING | Tautulli Users :: Unable to refresh users list.
2018-10-08 15:24:41 | WARNING | Tautulli PlexTV :: Unable to parse shared server list XML for get_full_users_list: 'NoneType' object has no attribute 'getElementsByTagName'.
2018-10-08 15:24:41 | WARNING | Failed to access uri endpoint /api/servers//shared_servers. Status code 404
2018-10-08 15:24:38 | INFO | Tautulli Users :: Requesting users list refresh...
2018-10-08 15:24:38 | INFO | Manual users list refresh requested.
```

I did read in the FAQ that there could be errors related to "Unable to retrieve..." messages if the user has not viewed anything before, but in this case all the Users on my server should all have viewed at least one movie (and I'm just missing a few of the recent user additions).  The XML parsing error also didn't seem like it was expected and maybe a result of Plex changing API format?

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#users-list-not-updating

**Comment by Arcanemagus** [comment]
Issues are not the place for support requests. In the future please use one of the [supported options](https://tautulli.com/#support) with the [Discord server](https://tautulli.com/discord) being preferred.

**Comment by chugcup** [comment]
Empty Plex Server Identifier was the issue, don't know how I missed that section in the FAQ.  My apologies.
