### ISSUE TITLE
Corrupted Image cache after ran outta drive space

### ISSUE THREAD

**Issue by GLotsapot** [Tautulli/Tautulli-Issues#131]
**Version:** 2.1.22

**Branch:** master

**Commit hash:** 03751abc0e34575e2b57d9f0edb241303059ea97

**Operating system:** Linux 4.4.0-137-generic (#163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 - Ubuntu 16.04 xenial)

**Python version:** 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

**What you did?** Hard drive ran outta space (my bad)

**What happened?** cache images wrote as 0b - removed the 0b images

**What you expected?** Thought that if it didn't find the cache image, it would re-cache them as needed. Tried the Refresh Image after and it refreshes the image fine but only temporarily. Get a message in the log stating "No image input received".

**How can we reproduce your issue?** Run outta hard drive space (although I don't recommend it)

**What are your (relevant) settings?**

**Link to logs:**

2018-10-08 17:47:26 | WARNING | No image input received.
-- | -- | --

**Comment by samwiseg00** [comment]
Issues are not the place for support requests. In the future please use one of the [supported options](https://tautulli.com/#support) with the [Discord server](https://tautulli.com/discord) being preferred.

**Comment by JonnyWong16** [comment]
GitHub issues are bug reports, not for support.

Clear your browser cache.

**Comment by GLotsapot** [comment]
> Issues are not the place for support requests. In the future please use one of the [supported options](https://tautulli.com/#support) with the [Discord server](https://tautulli.com/discord) being preferred.

I put this here as a requested code fix as the cache retrieval code is not doing a check to see if the cached image exists on the server. 
Additionally, the refresh image button button works, but doesn't re-save the image to the cache.

**Comment by GLotsapot** [comment]
> GitHub issues are bug reports, not for support.
> 
> Clear your browser cache.

Tried several browsers, on 2 different devices
