### ISSUE TITLE
[Feature Request/Question] Does Tautulli Support SSO?

### ISSUE THREAD

**Issue by AngryNoodlez** [Tautulli/Tautulli-Issues#132]
Hi, 

Quick one, does Tautulli support any kind of Single Sign On? Can't see anything on the API, and I'm still running an old version (v2.0.22) so I'm not sure what the updated version contains.

Thanks!

**Comment by samwiseg00** [comment]
No but it does support plex Oauth. You maybe able to use SSO with a reverse proxy. Please Use [Feathub for feature requests](https://feathub.com/Tautulli/Tautulli).

**Comment by AngryNoodlez** [comment]
Thanks, OAuth will do fine.
