### ISSUE TITLE
Opera Version:56.0.3051.52 Graphs won't load

### ISSUE THREAD

**Issue by lucidonlinenet** [Tautulli/Tautulli-Issues#133]
**Version:** 
V2.1.23-BETA

**Branch:** 
beta

**Commit hash:**
1bce850765f5252b3f88cf22daedd8d5c2fd4efd
--
**Operating system:** Windows 10 Pro

**Python version:** 
2.7.11

**What you did?** 
Tried to view graphs on opera browser, works in chrome

**What happened?**
Graphs never load

**What you expected?**
Graphs to load

**How can we reproduce your issue?**
Open Opera browser
Navigate to Graphs page in Tautulli

**What are your (relevant) settings?**
Unknow
**Link to logs:**
Relevnat line: WebUI :: /graphs : Uncaught Highcharts error #13: www.highcharts.com/errors/13. (highcharts.js:13)
Full Log: https://gist.github.com/lucidonlinenet/70f33470c083a364cdc0d1aed59d6145

**Comment by samwiseg00** [comment]
Clear your browser cache and reload the page. 

Issues aren't the place for support, please use one of the [available options](https://tautulli.com/#support), with the [Discord server](https://tautulli.com/discord) being preferred.
