### ISSUE TITLE
Unable to view ongoing sync progress from (remote) user

### ISSUE THREAD

**Issue by loyaltyarm** [Tautulli/Tautulli-Issues#134]
**Version:**
`VERSION V2.1.22`

**Branch:**
`Git Branch:	master`

**Commit hash:**
`Git Commit Hash:	03751abc0e34575e2b57d9f0edb241303059ea97`

**Operating system:**
`Platform:	Linux 4.4.0-87-generic (#110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 - Ubuntu 16.04 xenial)`

**Python version:**
`Python Version:	2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]`

**What you did?**

- Attempted to track the progress of a user's ongoing sync (troubleshooting sync)

**What happened?**

- During sync, no progress is reported (reported as 0%).
- On completion, progress is reported as 100%.

**What you expected?**

- Expected to see some progress during the sync. (Don't think I've ever seen it, don't think this is a regression.

**How can we reproduce your issue?**

Steps to reproduce:
- Get (remote) user to sync data to remote device
- View `Synced Items` dashboard in Tautulli

**What are your (relevant) settings?**

Install configuration:
```
Arguments:	['--quiet', '--daemon', '--nolaunch', '--config', '/opt/Tautulli/config.ini', '--datadir', '/opt/Tautulli']
```

**Link to logs:**

https://gist.github.com/loyaltyarm/7904d09cf72741bb1dad86a4d6bcdf54

**Comment by samwiseg00** [comment]
Unfortunately, Plex does not provide a progress percentage for sync items. Tautulli can only present the information plex provides. 

Sample Sync Info:
```xml
<SyncItem id="31106688" version="1" rootTitle="TV Shows" title="Doctor Who - S11 E3" metadataType="episode" contentType="video">
<Status failureCode="" failure="" state="pending" itemsCount="1" itemsCompleteCount="0" totalSize="0" itemsDownloadedCount="0" itemsReadyCount="0" itemsSuccessfulCount="0"/>
<MediaSettings audioBoost="100" maxVideoBitrate="200000" photoQuality="74" photoResolution="1920x1080" subtitleSize="100" videoQuality="100" videoResolution="1920x1080"/>
<Policy scope="all" unwatched="0"/>
<Location uri="library://xxxxxxxxxx/item/%2Flibrary%2Fmetadata%2Fxxxxx"/>
</SyncItem>
```

You can see the source data that Tautulli uses by triple clicking on the Synced Items title in the top left corner. See [Debugging Tautulli](https://github.com/Tautulli/Tautulli-Wiki/wiki/Debugging) for more info.

**Comment by loyaltyarm** [comment]
Thanks for the info, despite probably having seen this before I still appreciate the explanation!
