### ISSUE TITLE
macOS daemon instructions missing "mkdir" on Wiki

### ISSUE THREAD

**Issue by jackwilsdon** [Tautulli/Tautulli-Issues#139]
I don't think the template really applies here, as the issue is with https://github.com/Tautulli/Tautulli-Wiki. It doesn't seem editable so I'm opening this issue.

The macOS instructions seem to expect the `~/Library/LaunchAgents` folder to exist, but it seems in certain circumstances that it may not. `mkdir -p ~/Library/LaunchAgents` should be run _before_ the copy to ensure that it does. It would be nice if this step was added to the wiki :+1:

**Comment by JonnyWong16** [comment]
Done.
