### ISSUE TITLE
Telegram notification after update from PlexPy

### ISSUE THREAD

**Issue by Jacopx** [Tautulli/Tautulli-Issues#14]
**Version:** 2.0.22

**Branch:** master

**Commit hash:**  a08bce2073b1847762a22a843b13acc5f996d9cb

**Operating system:** Linux 4.9.70-v7+

**Python version:** 2.7.13

**What you did?** After i have checked that the Telegram bot was working with the proposed test, I have tried with a real notification but it dosent't work.

**What happened?** The notification isn't arrived.

**Link to logs:** https://gist.github.com/Jacopx/e67ee34e523e1a9b86bf1de63ead5cf9

It seems to be a problem with Python looking at the log file... The trigger has worked. I need to use Python3?

**Comment by Arcanemagus** [comment]
It looks like there was an issue migrating part of these notification agents to the new system. Please remove the agents and recreate it to fix this. If you are still having issues after doing this feel free to hop in the `#support` channel of the [Discord server](https://discord.gg/tQcWEUp).

Thanks for taking the time to file an issue!

**Comment by Jacopx** [comment]
The problem is not solved yet... I'm asking in the Discord server now!

**Comment by Jacopx** [comment]
The problem is solved with the last update! ;)
