### ISSUE TITLE
HTTPS Certificate Chain Field Does Not Permanently Save Values

### ISSUE THREAD

**Issue by Spaatz1402** [Tautulli/Tautulli-Issues#141]
**Version:**: 2.1.25 (2018-11-03)

**Branch:**: beta

**Commit hash:**: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28

**Operating system:**:  Windows 10 (10.0.17763)

**Python version:**: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

**What you did?**
I setup HTTPS with SSL as per the instructions in the FAQ etc.  I am running a DynDNS Domain Name with SSL.  In Tautulli's Settings - Web Interface section, underneath the advanced settings, there is a field called "HTTPS Certificate Chain" which I originally populated with a .pfx file path only to realize it is not appropriate and a .pem file path is needed.  So, I configured a .pem file, pasted the path into the field and committed the change.  Tautulli restarted and all was good, until I attempted to go back to the settings and tweak other settings.  To my surprise, the "HTTPS Certificate Chain" field has fallen back to the .pfx file path I thought I had overwritten!  In fact, any change I make to the settings on any of the settings tabs seems to automatically re-populate this field with the previously incorrect value!  Every single time I edit any setting in the Settings menu, this field reverts back to its previous value and commits the change to the config file.  If I don't remember to manually change this value each and everytime, it overwrite the config file with the incorrect value and then Tautulli refuses to launch properly, failing over.  I have no idea where this value is being populated from but it happens on every computer I use and is getting a bit old.  Can you please ensure that this value, when overwritten with a new value, stays overwritten and isn't resurrected from the dead each time I want to make a settings change?

*What happened?**

**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Comment by JonnyWong16** [comment]
Have you considered looking at the logs before posting an issue?

**Comment by Spaatz1402** [comment]
Hey there,

I looked at my logs.  Also reviewed the issue trackers in GitHub.  If I
write the change and save it, my platform functions well.  It's just when I
need to make any changes that it recurs.

Richard

**Comment by JonnyWong16** [comment]
Are you going to post the logs or keep us guessing?

**Comment by Spaatz1402** [comment]
I'll post the logs the next time it crashes and we can see what happens.  I
can say that whenever it stops launching after a change is committed with
this legacy cert path in place, it doesn't start and a simple change of the
config file entry related to this path to the correct one fixes the issue.

Richard

**Comment by samwiseg00** [comment]
There should be enough history in your logs to post them as long as you have not cleared them. There is no need to wait for the next incident.

**Comment by Spaatz1402** [comment]
Find attached.

Richard

**Comment by Spaatz1402** [comment]
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/2562207/tautulli.log)

**Comment by samwiseg00** [comment]
They need to be in a gist as described in 
https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support

**Comment by Arcanemagus** [comment]
Please post your logs as requested in the template (that you largely ignored) or in the article linked above.

**Comment by Spaatz1402** [comment]
No.  If that's a problem, close the ticket.  I am simply reporting a bug.
That's all the effort I am willing to expend on this.

**Comment by samwiseg00** [comment]
We will spend just as much effort trying to identify it.
