### ISSUE TITLE
Tautulli shows no detailed records for stream info history graphs

### ISSUE THREAD

**Issue by n1nj4888** [Tautulli/Tautulli-Issues#142]
**Version:** V2.1.25

**Branch:** Master

**Commit hash:** 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28

**Operating system:** Linux 3.10.105 (#23824 SMP Fri Oct 12 18:30:21 CST 2018)

NOTE: I'm using the latest linuxserver/tautulli Docker Image

**Python version:** 	2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]

**What you did?**

Tautulli shows no detailed records for "Stream Info" history graphs (it does show detailed records for "Plays by Period" history graphs)

Click Graphs (Play Count) -> Stream Info... If you click any of the (non-zero) values for any of Direct Play/Direct Stream/Transcode, the "<Play Type> History for DAY MON DD YYYY" box is shown but always displays "No matching records found" even though there should be records matching the number of play type counts...

If the same is done on the Graphs (Play Count) -> "Plays by Period" graphs, this returns the detailed records as expected...

**Comment by ochbob** [comment]
I can confirm, same issue on my side.

![capture](https://user-images.githubusercontent.com/16723954/49037387-5eb60b80-f1ba-11e8-9548-5f227c7ea357.PNG)
