### ISSUE TITLE
Start / pause / stop notification at the end of a movie

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#144]
Hi, 

I have set up a notification for start / pause / stop with parameters "Type=Movie". I have this linked to my home automation so that when I start a movie, the lights go of, when I pause the lights go on dimmed en when I stop watching the lights go on all the way. 

Now the issue is: when a movie plays until the end of the credits, the movie stops, but the status of tautulli changes to 'pause'. Even after an hour the status remains pause. 

I hope this can be fixed! 

Regards, 
Patrick 

-->

**Version: 2.1.25

**Branch: Master

**Commit hash:**

**Operating system: Darwin 15.6.0 (Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64)

**Python version: 2.7.10

**How can we reproduce your issue?**
Setup a start / pause / stop notification and let a movie play until it ends itself. 

**What are your (relevant) settings?**

**Comment by samwiseg00** [comment]
Unfortunately, This is an issue with your player/plex. I have seen this many times. This is not an issue with Tautulli. We respect the player state that is sent by the Plex server.
