### ISSUE TITLE
History not getting logged due to innacurate reporting of Play duration time

### ISSUE THREAD

**Issue by Maximus97** [Tautulli/Tautulli-Issues#146]
**Version:** V2.1.25

**Branch:** nightly

**Commit hash:** ac259214f7877fe570999cd52586ea9cda3bd6df
**Operating system**: Linux 4.15.0-39-generic (#42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018)

**Python version:** 2.7.15

Tautulli reports buffering even though the devices are not buffering, and that seems to interfere with the history logging. See Session 28 and Session 29 in the logs. Both those sessions reports an inaccurate Play duration (a few seconds) and thus do not get logged.

**Link to logs:**
https://pastebin.com/UjzydAxM

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/releases/tag/v2.1.26

**Comment by samwiseg0** [comment]
Please attach websocket logs from the time of the issue. 

Also which client is being used?
