### ISSUE TITLE
Problem running as daemon on Ubuntu 18.04

### ISSUE THREAD

**Issue by Ammar7347** [Tautulli/Tautulli-Issues#147]
Tautulli works just fine using the command `python2 Tautulli.py` but it doesn't work as a daemon. Please find the screenshot below for further clearity of the problem.

![image](https://user-images.githubusercontent.com/19525838/49608044-93cb1680-f98f-11e8-9980-640f6b3e41d0.png)

**Comment by Arcanemagus** [comment]
Issues are not the place for support. Please see the [Asking for Support](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support) article (or the readme of this repo).
