### ISSUE TITLE
Multi-Server Support

### ISSUE THREAD

**Issue by zSeriesGuy** [Tautulli/Tautulli-Issues#148]
@JonnyWong16 
Sorry to open this here if this is the wrong place. I'm not sure how to reach out to you.

I have been working on multi-server support in Tautulli and actually have it working now with multiple servers. 
Once I get it closer to completion, are you interested in incorporating my changes into your repository?

**Comment by samwiseg0** [comment]
Issues is not the proper place for this. Submit a PR.

Thanks
