### ISSUE TITLE
Error sending test email notification: Tautulli Notifiers :: Email notification failed: please run connect() first

### ISSUE THREAD

**Issue by tir38** [Tautulli/Tautulli-Issues#15]
Git Branch: | master
Git Commit Hash: | a08bce2073b1847762a22a843b13acc5f996d9cb
Configuration File: | /Applications/Tautulli/config.ini
Database File: | /Applications/Tautulli/tautulli.db
Log File: | /Applications/Tautulli/logs/tautulli.log
Backup Directory: | /Applications/Tautulli/backups
Cache Directory: | /Applications/Tautulli/cache
GeoLite2 Database: | Click here to install the GeoLite2 database.
Platform: | Darwin 15.6.0
Python Version: | 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

**What you did?**
Tried to create an email notification. I entered "From name", "From" and "To". I selected which triggers I want. I tried to send a test email. I saw a failed notification. Checking logs I see:

`Tautulli Notifiers :: Email notification failed: please run connect() first`

**Comment by Arcanemagus** [comment]
You haven't entered any of the connection information for your SMTP server. If you are still having issues after fixing that please join the `#support` channel of the [Discord server](https://discord.gg/tQcWEUp).
