### ISSUE TITLE
Can't send any notification using email notification agent (ascii codec can't decode byte)

### ISSUE THREAD

**Issue by coolfarmer** [Tautulli/Tautulli-Issues#150]
**Version:** 2.1.26

**Operating system:** Windows 10 (10.0.17134)

**Python version:** 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

**What you did?** Already updated Tautulli to the last version, restart the server, analyze my logs to find if the error can be solved by myself but can't find a solution. I have talked with a support guys on your Discord and I think he can't help me...

**What happened?** I can't send any email via the email notification agent. I setup correctly the form with basic information such my name, my email, my smtp server (with my gmail and working credencials). Every time I click on the button to send a test email, I got a "Notification Failed" in my notification logs and an exception in Tautulli logs.

Here is the exception in my log:
```
Tautulli NotificationHandler :: Notification thread exception: 'ascii' codec can't decode byte 0xe9 in position 43: ordinal not in range(128)
Traceback (most recent call last): 
    File "C:\Tautulli\plexpy\notification_handler.py", line 58, in process_queue 
        notify(**params) 
    File "C:\Tautulli\plexpy\notification_handler.py", line 369, in notify 
        **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 630, in send_notification 
        **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 810, in notify 
        return self.agent_notify(subject=subject, body=body, action=action, **kwargs) 
    File "C:\Tautulli\plexpy\notifiers.py", line 1366, in agent_notify 
        logger.error(u"Tautulli Notifiers :: {name} notification failed: {e}".format(name=self.NAME, e=e)) 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 43: ordinal not in range(128)
```

**What are your (relevant) settings?** Nothing special here, almost all on default value.

**Link to logs:**
https://gist.github.com/coolfarmer/a5d4be40af40c52156428e5df4e16c3a

**Images:**
 - https://i.imgur.com/DQigYOw.png
 - https://i.imgur.com/FE6z3Zf.png
 - https://i.imgur.com/UEx0dan.png

I really want to find out a solution, if I can help you with testing something or if I can give you more infos, just tell me what.

Thanks!

**Comment by JonnyWong16** [comment]
Please do not open duplicate issues.

#108

**Comment by coolfarmer** [comment]
@JonnyWong16 , I know it's a dupplicate but you tagged the other issue "status:need-more-info" and the guy don't give you more information. What can I do? Just close his issue and re-open mine, I want to solve that problem and I'm ok to give you time and a ton of details...

**Comment by JonnyWong16** [comment]
Provide info in the other issue.

**Comment by ochbob** [comment]
But the other issue is closed, and you did not tell to me what kind of information you need ?

and I asked for. :/
