### ISSUE TITLE
Newsletter directory keeps changing back to standard

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#151]
**Version:**
2.1.25
**Branch:**
Master
**Commit hash:**

**Operating system:**

MacOS
**Python version:**

**What you did?**
Change the newsletter directory
**What happened?**
It changed, and after a Mac restart changed back to the standard directory

**What you expected?**
It stayed changed

**How can we reproduce your issue?**
Edit newsletter directory (from UI or the config.ini file), restart Mac, check directory 

**What are your (relevant) settings?**

**Link to logs:**

**Comment by Arcanemagus** [comment]
One of two things is happening here:
* You are editing the config file while Tautulli is still running
* Tautulli doesn't have permissions to the `config.ini` file (ran as `sudo` once?)

Neither of this is a bug with Tautulli though. Please read the [Asking for Support](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support) article and use one of the support options listed there. Thanks!

**Comment by Patrick1610** [comment]
I have unloaded the daemon before editing the config.ini, but with the same result after a restart. I guess I did / do run it as sudo.
What should I do to give tautulli permissions again, without breaking the daemon?

**Comment by Patrick1610** [comment]
I'm sorry, I didn't read your post carefully! I will ask that question through support!
