### ISSUE TITLE
Track buffering

### ISSUE THREAD

**Issue by xiphosm3** [Tautulli/Tautulli-Issues#152]
One of the ways that I use the History page is to see how often shows are fully watched, and how long it takes a user to watch the episode vs how long the episode is.

This way I can see if its taking longer than it should for the user to play the episode, which typically indicates it was buffering a lot.

Is there a way you could add in another column that takes the total play time, excluding paused duration, and subtracts it from the episode/movie duration? If its anything greater than 0, you know it buffered and we can see how long it buffered for.

This would help me understand which users struggle with buffering and if its certain media or bitrate.

**Comment by Arcanemagus** [comment]
https://github.com/Tautulli/Tautulli-Issues#feature-requests
