### ISSUE TITLE
Direct Play / Direct stream / Direct Video(or some better name) / Transcode

### ISSUE THREAD

**Issue by Maximus97** [Tautulli/Tautulli-Issues#154]
Right now, I think it's a little bad that audio transcode are categorized the same as video transcode. Because honestly, video transcodes are on a league of thier own regarding system resources. So I think that streams where video is direct played but audio is transcoded should get a new category and be distunguished from video transcodes. Maybe call it Direct Video? It would give a better overview of how your users are streaming your media.
Thanks!

**Comment by JonnyWong16** [comment]
This is not a bug report.

**Comment by samwiseg0** [comment]
All information is pulled directly from plex. These terms and decisions are exactly as plex provides and uses.
