### ISSUE TITLE
LAN/WAN is mixed up

### ISSUE THREAD

**Issue by Panja0** [Tautulli/Tautulli-Issues#157]
**Version:**
v2.1.26

**Branch:**
Master

**Commit hash:**
aa023f016671e78463dd95e8f662cbc6cc712cf0

**Operating system:**
Linux 3.10.105 (#23824 SMP Tue Dec 25 18:26:44 CST 2018)
(Docker image)

**Python version:**
2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]

**Problem description**
LAN/WAN is mixed up.

**What you did?**
Run a movie (or other content).

**What happened?**
When I play a movie in my own local network it is marked as being played through WAN.
When I play a movie externally it is marked as being played through LAN.

**What you expected?**
That the movie that was played locally would be marked as played through LAN.
That the movie that was played externally would be marked as played through WAN.

**How can we reproduce your issue?**
Just play a movie. ;-)

<img width="1042" alt="screen shot 2019-01-25 at 11 56 57" src="https://user-images.githubusercontent.com/12939350/51743247-58e68480-209c-11e9-9c64-7c3900c8ae29.png">

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use one of your [support options](http://tautulli.com/#support) with discord being preferred. 

More than likely this has to do with how your player is connecting to your plex server. Tautulli only shows what plex says.

**Comment by Komic** [comment]
@samwiseg0, does this mean the LAN/WAN distinction is done on Plex's side? I see there's a list of private ranges [here](https://github.com/Tautulli/Tautulli/blob/7eee7024b6eac0a858748664878d146bf63623b4/lib/ipaddress.py#L1685), not sure what it's for. Either way, Tautulli seems to be tagging 10.10.10.1 as WAN but 10.88.0.1 as LAN, the inconsistency is kind of frustrating.

**Comment by Arcanemagus** [comment]
The distinction is done on Plex's side, Tautulli is only recording what it is told by Plex. You need to fix your Plex server if you want that reported correctly.

Again, this is **not** the place for support, please do not post here for support issues!

**Comment by Komic** [comment]
Yep, not looking for help, I was legitimately wondering if this was intended. Turns out specifying LAN networks is a Plex Pass feature for some reason. Does Tautulli have to trust Plex on this?

**Comment by Arcanemagus** [comment]
Since Tautulli [doesn't have to be on the same machine as Plex](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#install-same-machine-plex), yes, it needs to trust Plex on this.

**Comment by Komic** [comment]
Right, what I meant is that maybe Tautulli could tag as WAN/LAN depending on the IP reported by Plex and defined IP ranges. Essentially replacing the Plex option I was talking about, I guess. It might not be worth your time of course, just floating the idea.

**Comment by JonnyWong16** [comment]
No, because Tautulli is accurately telling you that something is wrong with your Plex network setup. If Tautulli changed the `WAN`/`LAN` then you would never know that there is an issue which needs to be fixed.

For example, `WAN: 127.0.0.1` being reported by Plex means that the stream is being proxied through the Plex Relay. If that said `LAN` then you would not know that there is a network issue.

Tautulli is used to tell you what is happening on your Plex server and help you diagnose issues. It is not there to make your data look perfect.

**Comment by Komic** [comment]
Hm, my stuff definitely isn't proxied through the relay, it's explicitly disabled. I'll take a look, thanks for your inputs.
