### ISSUE TITLE
Heads up re: linuxserver.io multi-arch docker images

### ISSUE THREAD

**Issue by aptalca** [Tautulli/Tautulli-Issues#158]
Hi, I'm a member of the linuxserver.io team.

I just wanted to give you a heads up that we migrated tautulli over to our new builder and we are now providing multi-arch docker images (x86_64, armv6 and aarch64) through a single repo at https://hub.docker.com/r/linuxserver/tautulli

The separate arm repo has been deprecated.

In the future, users can simply pull `linuxserver/tautulli` and it should automatically download the correct docker image for their arch.

Also, our new images are tagged with specific versions, for both the stable and master branch releases. Our jenkins queries github for new releases and commits and new builds should be pushed shortly after there is a new release or commit.

`linuxserver/tautulli:latest` will follow the stable github releases and `linuxserver/tautulli:develop` will follow the master branch commits

You can see the concise builds on github: https://github.com/linuxserver/docker-tautulli/releases
and all available docker image tags are right here: https://hub.docker.com/r/linuxserver/tautulli/tags

Feel free to update the tautulli readme to point out the changes.

Thanks so much and keep up the good work ;)

**Comment by Arcanemagus** [comment]
Closing this since it isn't a bug report, thanks for letting us know though!

----

Btw, `master` is _always_ the same as the latest stable release, your `develop` tag should follow the `nightly` branch, or possibly the `beta` branch if you want it to be slightly less experimental.

**Comment by aptalca** [comment]
ahh, thanks for that. We'll update the builds. Likely change to the beta branch.

**Comment by jalmansor** [comment]
@aptalca It would be good to have nightly as an option as well, since that's the reason I started using the Tautulli official image in the first place.

**Comment by thelamer** [comment]
@aptalca @Arcanemagus after talking with arc and the requirements needed I am gonna have the develop pull from nightly and specifically checkout that branch. It does pose a race condition for our tag versioing at the github commit, but it looks like the app has an understanding of what branch it is on etc and we need to clone and checkout at that branch .
We should keep the tag and just update the readmes when we get them converted over .
