### ISSUE TITLE
New QNAP Installation Link for the Wiki

### ISSUE THREAD

**Issue by bennokress** [Tautulli/Tautulli-Issues#16]
**Version:** 
v2.0.22

**Branch:** 
master

**Commit hash:** 
a08bce2073b1847762a22a843b13acc5f996d9cb

**Operating system:** 
Linux 4.2.8 (QNAP)

**Python version:** 
All

**What you did?** 
Check the Wiki

**What happened?** 
Found an old Link

**What you expected?** 
I expected to be able to edit the page myself and give you a PR, but there's no option for that

**How can we reproduce your issue?**
1. Go to the Wiki -> Installation -> [QNAP](https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#qnap)
2. Edit the link to the [new release page for Tautulli](https://qnapclub.eu/en/qpkg/557)

**Comment by Arcanemagus** [comment]
Since the current one is [soon to be updated](https://forum.qnap.com/viewtopic.php?p=662351#p662351), what reason is there to switch to this brand new one that was just created yesterday?

**Comment by bennokress** [comment]
Because it [is the new one](702094) that is already updated (and running well by the way) ;)

**Comment by Arcanemagus** [comment]
I'd say that's a pretty good reason 😆, updating the Wiki and thanks for the notification!
