### ISSUE TITLE
Playback stopped notification not sent after 'Watched percentage' is reached. 

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#162]
**Version:**
V2.1.26
**Branch:**
Master
**Commit hash:**

**Operating system:**

Linux 4.15.0-45-generic (#48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 - Ubuntu 18.04 bionic)

**Python version:**

2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

**What you did?**
1. Started a movie, watched it until after the 'watched movie percentage', stopped the movie with plenty of time before 100% was reached. 

2. Started a movie, watched it until before the 'watched movie percentage', stopped the movie with plenty of time before 100% was reached. 

3. Changed the 'movie watched percentage', started a movie, watched it until after the 'watched movie percentage', stopped the movie with plenty of time before 100% was reached.

**What happened?**
In cases 1 and 3, the movie did not execute the 'Playback stopped' notification, in case 2 it did. 

**What you expected?**
I expected the 'Playback stopped' notification to run when I stopped the movie in cases 1, 2 and 3. 

**How can we reproduce your issue?**
By doing the "**What you did?**" steps exactly. 

**What are your (relevant) settings?**
Notifications setup for start, pause, resume and stop playback and for watched. 

**Link to logs:**

**Comment by JonnyWong16** [comment]
https://www.reddit.com/r/Tautulli/comments/aqs12y/tautulli_notification_agent_stream_stoppedended/

**Comment by Patrick1610** [comment]
Thanks! When I enable that, my Smart Home controller gets so many web hook notifications, for example when fast-forwarding. Is there a way to make the stop notification work better without enabling that? 

Also, I would like to create a web hook notification to sent the {remaining_duration} when the watched percentage is reached. How should I set that up and what is the exact output of that notification?

**Comment by Patrick1610** [comment]
I just tested the following again: 

Started a movie, watched it until after the 'watched movie percentage', watched another 7 minutes stopped the movie with plenty of time before 100% was reached. 

On stop, the movie disappears immediately from the 'activity' field, so Tautulli seems to know it is stopped. 

Since there is 7 minutes between "Watched" and "Stopped", this cannot have anything to do with Consecutive Notifications, does it?
