### ISSUE TITLE
Webhook Callback Exception

### ISSUE THREAD

**Issue by brandonm** [Tautulli/Tautulli-Issues#165]
I setup a Webhook for play and pause and when its triggered I get an exception thrown in logs.

Setup:

**URL**: https://example.com/callback
**Method**: POST
**Description**: Webhook Test
**Triggers**: Only Strat and Stop selected
**Conditions**: None

**Data**:
**Start**:
```
{
    "type": "start",
    "name": "{user}",
    "user": "{username}",
    "email": "{user_email}",
    "streams": "{user_streams}",
    "sessionKey": "{session_key}",
    "transcodeKey": "{transcode_key}",
    "sessionId": "{session_id}",
    "userId": "{user_id}",
    "machineId": "{machine_id}"
}
```

**Stop**:
```
{
    "type": "stop",
    "name": "{user}",
    "user": "{username}",
    "email": "{user_email}",
    "streams": "{user_streams}",
    "sessionKey": "{session_key}",
    "transcodeKey": "{transcode_key}",
    "sessionId": "{session_id}",
    "userId": "{user_id}",
    "machineId": "{machine_id}"
}
```

When the start is triggered I get this error in the logs.  I have tried on two different servers and both had the same results.  I even tried manually modifying the db and DROP the notifiers and setup again but that didn't stop the exception.

```
2019-03-03 21:11:30 - ERROR   :: Thread-1 : Tautulli NotificationHandler :: Notification thread exception: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/plexpy/plexpy/notification_handler.py", line 58, in process_queue
    notify(**params)
  File "/opt/plexpy/plexpy/notification_handler.py", line 369, in notify
    **kwargs)
  File "/opt/plexpy/plexpy/notifiers.py", line 630, in send_notification
    **kwargs)
  File "/opt/plexpy/plexpy/notifiers.py", line 810, in notify
    return self.agent_notify(subject=subject, body=body, action=action, **kwargs)
  File "/opt/plexpy/plexpy/notifiers.py", line 3598, in agent_notify
    return self.make_request(self.config['hook'], method=self.config['method'], headers=headers, json=webhook_data)
  File "/opt/plexpy/plexpy/notifiers.py", line 817, in make_request
    response, err_msg, req_msg = request.request_response2(url, method, **kwargs)
  File "/opt/plexpy/plexpy/request.py", line 194, in request_response2
    req_msg = server_message(e.response, return_msg=True)
  File "/opt/plexpy/plexpy/request.py", line 292, in server_message
    if "text/html" in response.headers.get("content-type"):
TypeError: argument of type 'NoneType' is not iterable
```

The callback is working and getting 200 back from webserver but its showing this in the logs.

123.123.123.123 - - [03/Mar/2019:20:19:11 +0000] "POST /callback HTTP/1.1" 200 0 "-" "python-requests/2.18.4"

**Version:**
2.1.26

**Branch:**
master
**Commit hash:**
aa023f016671e78463dd95e8f662cbc6cc712cf0 
**Operating system:**
Linux 4.20.6-xanmod4 (#1.190131 SMP PREEMPT Thu Jan 31 13:41:21 -02 2019 - Ubuntu 18.04 bionic) 

**Python version:**
2.7.15rc1 (default, Nov 12 2018, 14:31:15)  [GCC 7.3.0]

**What you did?**
**What happened?**
**What you expected?**
**How can we reproduce your issue?**
**What are your (relevant) settings?**
**Link to logs:**
See above

**Comment by Arcanemagus** [comment]
It looks like your server isn't adding a [`Content-Type`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) header to the response. Although not _strictly_ required, there isn't much that you can do with a response without knowing what those raw bits are supposed to mean.

**Comment by brandonm** [comment]
Yes that does make sense but I return 200 OK with no body "content-length: 0".  I'm not sure what response Tautulli would want.

**Comment by brandonm** [comment]
Looking at the code at [line 819](https://github.com/Tautulli/Tautulli/blob/56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28/plexpy/notifiers.py#L819) it checks that response exists and error wasnt returned.  I feel that if a 200 is returned and you dont care what the body is then why require it?  I added response of {"message":"OK"} and it stopped throwing the exception.

**Comment by JonnyWong16** [comment]
I will fix this so that it won't raise an exception with a missing `Content-Type` header, but the *only* way to get to that exception is if your response raised an `HTTPError`.
```
  File "/opt/plexpy/plexpy/request.py", line 194, in request_response2
    req_msg = server_message(e.response, return_msg=True)
```
https://github.com/Tautulli/Tautulli/blob/56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28/plexpy/request.py#L180-L194

So missing `Content-Type` header aside, something else is wrong with your webhook.
