### ISSUE TITLE
(un)install Tautulli GeoLite2 Database failure

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#167]
**Version:**

**Branch:**

**Commit hash:**

**Operating system: Linux Ubuntu

**Python version:**

**What you did?**
A few months ago I switched my Tautulli Database from MacOS to Ubuntu. Everything works fine except GeoLite2.
I tried to install, uninstall or reinstall the GeoLite2 database

**What happened?**
All three options failed. 

**What you expected?**
That at least after uninstalling, I would be able to install again. 

**How can we reproduce your issue?**
Move Tautullu from MacOS to Ubuntu and try to get GeoLite2 working. 

**What are your (relevant) settings?**
I noticed that the database still points to a MacOS path. 

Git Branch: | master
Git Commit Hash: | e949b1486e67bc58c636ad13adad83a1747c5574
Configuration File: | /opt/Tautulli/config.ini
Database File: | /opt/Tautulli/tautulli.db
Log File: | /opt/Tautulli/logs/tautulli.log
Backup Directory: | /opt/Tautulli/backups
Cache Directory: | /opt/Tautulli/cache
Newsletter Directory: | /opt/Tautulli/newsletters
GeoLite2 Database: | /Applications/Tautulli/GeoLite2-City.mmdb \| Reinstall / Update \| Uninstall

**Link to logs:**

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.
