### ISSUE TITLE
IP Lookup showing Null

### ISSUE THREAD

**Issue by modem7** [Tautulli/Tautulli-Issues#168]
Related link: https://forums.freebsd.org/threads/geoiplookup-for-the-new-geolite2-country-db.69866/

![iplookup](https://user-images.githubusercontent.com/4349962/55000523-9eef9400-4fca-11e9-9a75-032213112005.JPG)

IP lookup address is showing as null. Unsure if this is to do with the above link and maxmind changing thing around with the geolite2 stuff

OS: Fedora
Tautulli Version v2.1.28

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.

The database does not have the ISP's address so `null` will be displayed.
