### ISSUE TITLE
Enhancement / thought: Poster refresh before newsletter send

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#169]
Hi, 

I really like Tautulli for a lot of features (especially home-automation and the newsletter feature). Though, I noticed today that in the newsletter a poster was missing, even though I added one hours before the newsletter was sent. 

Could It be made that Tautulli checks the Plex server for the posters of the recently added items and updates those, before sending the newsletter? 

Regards, 
Patrick

**Comment by samwiseg0** [comment]
Issues are not the place for feature requests, as explained in the README. Please use [Feathub for feature requests](https://feathub.com/Tautulli/Tautulli). Secondly, if you are having an issue please use one of the [support options](https://Tautulli.com/#support). Discord is preferred.

**Comment by Patrick1610** [comment]
Sorry! Posted it on Feathub ;)
