### ISSUE TITLE
Script error - Function interrupted? 

### ISSUE THREAD

**Issue by magauthority** [Tautulli/Tautulli-Issues#170]
This may not be specifically a Tautulli issue, but I'm not sure... So save me the flames if this is a problem with my code, but I need some help. 

  I've written a script that does some processing of new items added to plex. Specifically checking for proper audio and subtitle track naming and so on. Works great. However I did notice that when multiple items were added all at once, calling multiple instances of my script caused unexpected behavior. Since in my setup a file is copied before any work is preformed on it, having 5-10 copies spawn all at the same time isn't workable, so I added a process lock to my script, so only one file is being worked on at a time. This also works correctly. The additional instance(s) are put into a time.sleep loop until the file lock is removed. 

 This worked great until recently I started seeing the below in my logs. Over and over again this message:
`  | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "G:\Tautulli\Scripts\SubProcessing.py", line 21, in <module>             time.sleep(30)     IOError: [Errno 4] Interrupted function call
`
Tautulli is running latest git release. 
Running on Windows 7x64 sp1 
Python 2.7.16
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/3084897/tautulli.log)

any help would be greatly appreciated. My scripts works as expected when I test it from a command line, but not is throwing these errors when called from Tautulli. 

Here's a copy of the script as well: 
[SubProcessing.zip](https://github.com/Tautulli/Tautulli-Issues/files/3084903/SubProcessing.zip)

Thanks in advance for any help. 
Best.
{c}guy

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.
