### ISSUE TITLE
Tautulli shows duplicated library names in Settings -> Homepage -> Library Statistics

### ISSUE THREAD

**Issue by n1nj4888** [Tautulli/Tautulli-Issues#173]
**Version:** V2.1.28

**Branch:** master

**Commit hash:** None

**Operating system:** Linux 3.10.105 (#24922 SMP Thu Mar 28 11:04:28 CST 2019)

**Python version:** 2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]

**What you did?**
When navigating to Settings -> Home Page -> Library Statistics, my names are shown but are all duplicated so that each library name is shown 7 times. 

**What happened?**
Each library name is duplicated 7 times - For example:

Library A
Library B
Library C
...
Library A
Library B
Library C
...
Library A
Library B
Library C

I suspect this maybe because there are multiple Plex Servers (although not 7 - Perhaps i is also including old/removed servers?!) configured in my same Plex Account...

The problem is that there is no way to distinguish which of the 7 sets of Library names relate to the desired server...

**What you expected?**
A single set of valid Library Names would be presented for the selected Plex Server **only** - Any Library Names associated with other Plex Servers configured in the Plex Account should not be presented i.e.

Library A
Library B
Library C

**How can we reproduce your issue?**
Configure multiple Plex servers in a single Plex Account (each with Library A, Library B, Library C etc)
Install Tautulli and point to Plex server1
Navigate to Settings -> Homepage -> Library Statistics
Multple duplicated Libraries are shown with no way of determining which relates to the selected Plex Server.

**What are your (relevant) settings?**

**Link to logs:**

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.

ps. Multiple servers is not supported.

**Comment by n1nj4888** [comment]
@samwiseg0 - This is not a support request, it’s a bug. 

I know Tautulli doesn’t support multiple Plex Servers so the issue is, when selecting a specific single Plex Server A, Tautulli should not be showing the Library Names duplicated / across each server in the Plex account.

**Comment by JonnyWong16** [comment]
Your question has already been answered in the FAQ.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q8
