### ISSUE TITLE
emails not rendering images in outlook (screenshot)

### ISSUE THREAD

**Issue by bbrendon** [Tautulli/Tautulli-Issues#175]
I'm assuming this is happening for everyone and it has something to do with the template. If not I'd be happy to gather logs etc.  As you can see the images are not appearing. If I load the email in my browser the images appear.  The emails work fine in gmail.  I have the newsletter configured to upload images to cloudinary.

**Version:**  V2.1.28   

![image](https://user-images.githubusercontent.com/6364477/57040124-5f444980-6c13-11e9-9340-af9e0be62ba5.png)

**Comment by Arcanemagus** [comment]
[Images are not showing up in my newsletter emails.](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-missing-images)

Issues are not the place for support requests, especially when they are already answered in the FAQ.

**Comment by bbrendon** [comment]
Cool. Thanks!

**Comment by medic6578** [comment]
Shrugging your shoulders is not the same as an answer. You have seemed to say that it is an Outlook issue which is a poor answer and does not address that the largest number of email users use outlook. So no it is not answered in the FAQ.

**Comment by JonnyWong16** [comment]
There are no plans to make the default newsletter template support Outlook. If you want to support Outlook then you will need to create your own newsletter template which uses images instead of css backgrounds. That is the same answer as the FAQ.
