### ISSUE TITLE
Tautulli Newsletter ignores recently added Audio Books

### ISSUE THREAD

**Issue by Massaguana** [Tautulli/Tautulli-Issues#176]
**Version:** V.2.1.28
**Branch:** master
**Commit hash:** e949b1486e67bc58c636ad13adad83a1747c5574
**Operating system:** Linux 4.15.0-47-generic (#50~16.04.1-Ubuntu SMP Fri Mar 15 16:06:21 UTC 2019 - Ubuntu 16.04 xenial)
**Python version:** 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
**What you did?** add new Audio Books to PMS

**What happened?** PMS add and show me the recently added Audio Books, but the Newsletter not
![Bildschirmfoto_2019-05-03_um_13 49 14](https://user-images.githubusercontent.com/15521791/57177984-3ff32980-6e6a-11e9-8229-74359d9088d9.jpg)

**How can we reproduce your issue?** add new audio books

**What are your (relevant) settings?** 
![Bildschirmfoto 2019-05-04 um 12 41 25](https://user-images.githubusercontent.com/15521791/57177960-f4408000-6e69-11e9-97a2-a519eee3278b.jpg)

**Link to logs:**
[tautulli.log.zip](https://github.com/Tautulli/Tautulli-Issues/files/3144251/tautulli.log.zip)

**Comment by Massaguana** [comment]
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="46" librarySectionTitle="Hörbücher" librarySectionUUID="94cfeee1-4e4f-4e2d-aae7-ae6cb4b84387" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1555951837">
<Directory ratingKey="952311" key="/library/metadata/952311/children" parentRatingKey="952310" guid="com.plexapp.agents.none://952311?lang=xn" librarySectionTitle="Hörbücher" librarySectionID="46" librarySectionKey="/library/sections/46" type="album" title="044/Alarm für die Glaxis" titleSort="044/Alarm fur die Glaxis" parentKey="/library/metadata/952310" parentTitle="044/Alarm für die Galaxis" summary="Der Höhepunkt im Kampf zwischen dem Solaren Imperium der Menschheit und der Ersten Schwingungsmacht sowie der sogenannten Zeitpolizei steht bevor. Schiffe der Solaren Flotte dringen in die Kleine Magellansche Wolke vor, ein Kommandounternehmen kommt hinter das Geheimnis der Ersten Schwingungsmacht: Die Terraner erkennen, in welchem Verhältnis die monströsen Zweitkonditionierten in ihren lebendigen Raumschiffen und die Haluter stehen. Aber sie schaffen es nicht, ihr Heimatsystem zu stürmen, das durch ein Zeitfeld und einen Paratronschirm geschützt ist.
 
 Stattdessen wird das Solsystem zum Schauplatz einer fürchterlichen Schlacht: Die Erde und die anderen Planeten werden von einer riesigen Flotte der Zweitkonditionierten angegriffen; Millionen von Menschen sterben, und die Welten der Menschheit werden schrecklich verwüstet. Terra scheint am Ende zu sein.
 
 In dieser Situation tauchen riesige Flotten aus der fernen Galaxis M 87 in der Milchstraße auf. Ihre Herrn fordern von Perry Rhodan den Verrat an Terras besten Freunden, den Halutern. Die Alternative zum Verrat ist das Ende der Menschheit ..." index="1" viewCount="15" lastViewedAt="1558805563" year="2015" thumb="/library/metadata/952311/thumb/1558730333" originallyAvailableAt="2015-01-01" leafCount="174" viewedLeafCount="15" addedAt="1558729891" updatedAt="1558730333">
<Genre id="143739" filter="genre=143739" tag="Hörbuch"/>
</Directory>
</MediaContainer>`

**Comment by Massaguana** [comment]
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="46" librarySectionTitle="Hörbücher" librarySectionUUID="94cfeee1-4e4f-4e2d-aae7-ae6cb4b84387" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1555951837">
<Directory ratingKey="952311" key="/library/metadata/952311/children" parentRatingKey="952310" guid="com.plexapp.agents.none://952311?lang=xn" librarySectionTitle="Hörbücher" librarySectionID="46" librarySectionKey="/library/sections/46" type="album" title="044/Alarm für die Glaxis" titleSort="044/Alarm fur die Glaxis" parentKey="/library/metadata/952310" parentTitle="044/Alarm für die Galaxis" summary="Der Höhepunkt im Kampf zwischen dem Solaren Imperium der Menschheit und der Ersten Schwingungsmacht sowie der sogenannten Zeitpolizei steht bevor. Schiffe der Solaren Flotte dringen in die Kleine Magellansche Wolke vor, ein Kommandounternehmen kommt hinter das Geheimnis der Ersten Schwingungsmacht: Die Terraner erkennen, in welchem Verhältnis die monströsen Zweitkonditionierten in ihren lebendigen Raumschiffen und die Haluter stehen. Aber sie schaffen es nicht, ihr Heimatsystem zu stürmen, das durch ein Zeitfeld und einen Paratronschirm geschützt ist.
 
 Stattdessen wird das Solsystem zum Schauplatz einer fürchterlichen Schlacht: Die Erde und die anderen Planeten werden von einer riesigen Flotte der Zweitkonditionierten angegriffen; Millionen von Menschen sterben, und die Welten der Menschheit werden schrecklich verwüstet. Terra scheint am Ende zu sein.
 
 In dieser Situation tauchen riesige Flotten aus der fernen Galaxis M 87 in der Milchstraße auf. Ihre Herrn fordern von Perry Rhodan den Verrat an Terras besten Freunden, den Halutern. Die Alternative zum Verrat ist das Ende der Menschheit ..." index="1" viewCount="15" lastViewedAt="1558805563" year="2015" thumb="/library/metadata/952311/thumb/1558730333" originallyAvailableAt="2015-01-01" leafCount="174" viewedLeafCount="15" addedAt="1558729891" updatedAt="1558730333">
<Genre id="143739" filter="genre=143739" tag="Hörbuch"/>
</Directory>
</MediaContainer>
```

**Comment by Massaguana** [comment]
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/3219587/tautulli.log)

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-recently-added-library
