### ISSUE TITLE
V2.0.22 History tab stuck fetching rows. Throws error.

### ISSUE THREAD

**Issue by Xenocell12** [Tautulli/Tautulli-Issues#18]
Version: V2.0.22

Branch: nightly 

Commit hash: 9905ebc1441bf4f2168bc6fe30dda58a8c1569e2

Operating system: Windows 10

Python version:  2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]

What you did?: Open history tab

What happened?: Nothing populates. Stuck fetching. Threw ERROR "WebUI :: /history : Uncaught TypeError: Illegal invocation. (jquery-2.1.4.min.js:4)" This does not happen on the Tautulli Android app, however.

What you expected?: Able to view watch history from users.

How can we reproduce your issue?: Run version 2.0.22. (this is a fresh install) git pull. Link Plex server. Watch a few things. Try to pull history from history tab.

What are your (relevant) settings: Running through HTTP root reverse proxy. 

Link to logs: https://pastebin.com/YFzDB7HP

**Comment by JonnyWong16** [comment]
1. Try clearing browser cache.
2. There might be an error in your database.
  a. Try doing Settings > General (show advanced) > Flush Temporary Sessions.
  b. Does `http://IP_ADDRESS:PORT/get_history` work? It should return the raw history in json format.

**Comment by Xenocell12** [comment]
Well.. Not using my IIS reverse proxy works. Also the raw json comes up under reverse proxy.

My suspicion is that whatever is coded differently now- the jscript does not go through well with my IIS.

It's odd that there is an error being thrown on the app?

**Comment by JonnyWong16** [comment]
I'm not familiar with IIS, sorry.

**Comment by AngryNoodlez** [comment]
Same problem with this for me on nginx. Locally works fine, but via nginx reverse proxy I get the a 404 error to say it can't find a particular endpoint.


See error from browser below. Maybe a character limitation or something?

`VM707:1 GET https://my.domain.com/plexpy/get_history?json_data=%7B%22draw%22%3A1%2C%22columns%22%3A%5B%7B%22data%22%3Anull%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Afalse%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22date%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22friendly_name%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22ip_address%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22platform%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22player%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22full_title%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Atrue%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22started%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22paused_counter%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22stopped%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22duration%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Atrue%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%2C%7B%22data%22%3A%22watched_status%22%2C%22name%22%3A%22%22%2C%22searchable%22%3Afalse%2C%22orderable%22%3Afalse%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D%5D%2C%22order%22%3A%5B%7B%22column%22%3A1%2C%22dir%22%3A%22desc%22%7D%5D%2C%22start%22%3A0%2C%22length%22%3A25%2C%22search%22%3A%7B%22value%22%3A%22%22%2C%22regex%22%3Afalse%7D%7D&media_type=&user_id=&_=1521409301462 404 (Not Found)
(anonymous) @ VM707:1
send @ jquery-2.1.4.min.js:4
ajax @ jquery-2.1.4.min.js:4
ra @ jquery.dataTables.min.js:36
lb @ jquery.dataTables.min.js:37
O @ jquery.dataTables.min.js:29
T @ jquery.dataTables.min.js:31
ga @ jquery.dataTables.min.js:48
(anonymous) @ jquery.dataTables.min.js:96
each @ jquery-2.1.4.min.js:2
each @ jquery-2.1.4.min.js:2
m @ jquery.dataTables.min.js:86
h.fn.DataTable @ jquery.dataTables.min.js:166
loadHistoryTable @ history:446
(anonymous) @ history:472
j @ jquery-2.1.4.min.js:2
fireWith @ jquery-2.1.4.min.js:2
ready @ jquery-2.1.4.min.js:2
I @ jquery-2.1.4.min.js:2
jquery-2.1.4.min.js:4 Uncaught TypeError: Illegal invocation
    at e (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13154)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13039)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13062)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13062)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13062)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13062)
    at Ab (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13062)
    at Function.n.param (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:13400)
    at Function.ajax (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:9596)
    at Function.n.(anonymous function) [as post] (https://my.domain.com/plexpy/js/jquery-2.1.4.min.js:4:11707)`

**Comment by AngryNoodlez** [comment]
Found the issue.

I'm running IIS in-front of Nginx and looks like this was hitting a request limit on IIS.

Fixed by adding the following to web.config;

`        <security>
            <requestFiltering>
		<requestLimits maxQueryString="4096"/>
            </requestFiltering>
        </security>`

**Comment by Arcanemagus** [comment]
Thanks for reporting back what the solution was @AngryNoodlez!

**Comment by jippo015** [comment]
I'm having the same issue but @AngryNoodlez solution isn't working for me.

Version: V2.0.24
Branch: nightly
Commit hash: a5807f21b41189538fa624b59a157faa9675734b
Operating system: Windows 10
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

Got this error from the logs:
ERROR   :: CP Server Thread-5 : WebUI :: /history : TypeError: 'createCaption' called on an object that does not implement interface HTMLTableElement.. (jquery-2.1.4.min.js:4

Running it locally on localhost:8181 it works fine, but with a reverse proxy through IIS it doesn't.

Anyone any thoughts?

**Comment by jippo015** [comment]
Found the solution, in addition to @AngryNoodlez edit on the web.config the following has to be added as well:
```
<system.web>
     <httpRuntime maxQueryStringLength="4096"/>
 </system.web>
```

**Comment by Arcanemagus** [comment]
For reference, these workarounds should no longer be necessary as of v2.0.27.
