### ISSUE TITLE
Github issue template has a wrong link to feathub

### ISSUE THREAD

**Issue by plankes-projects** [Tautulli/Tautulli-Issues#180]
Github issue template has a wrong link to feathub.
Actual: http://feathub.com/JonnyWong16/plexpy
Expected: https://feathub.com/Tautulli/Tautulli

(Not sure if https://feathub.com/Tautulli/Tautulli is the correct one, but I assume)

**Comment by JonnyWong16** [comment]
Thank you. Issues template has been updated.
