### ISSUE TITLE
500 Internal Server Error when accessing JBOP Script Notifications Agents

### ISSUE THREAD

**Issue by theweasley** [Tautulli/Tautulli-Issues#186]
<img width="667" alt="Screenshot 2019-07-11 at 05 06 50" src="https://user-images.githubusercontent.com/47760341/61013017-6c5f8080-a39a-11e9-8bae-5f62093f9499.png">

Just upgraded to the latest release v2.1.32 and now I every time I try to click on a JBOP Script Notification instance to access its settings under Notification Agents, I get the 500 Internal Server Error as pictured above. Cross-verified with other users and they're having the same issue. Reporting it as a bug here.

Not sure which log to post here for further assistance.

**Comment by JonnyWong16** [comment]
Bug report template not filed out.

**Edit** your issue with the competed template and I will reopen the issue if it is a valid bug report. *Do not* repost by opening a new issue.
