### ISSUE TITLE
Media Info Missing

### ISSUE THREAD

**Issue by TXDeadBear** [Tautulli/Tautulli-Issues#187]
Media info for some files is missing. I have attached a screenshot showing this. Media info for all of those files used to be there but now is not. I have tried "Refresh Media Info" but to no avail. Is there anything I can do to get that info back into Tautulli?
![Capture](https://user-images.githubusercontent.com/7632482/61473692-883fc500-a94c-11e9-8261-f82cf8c6b99f.PNG)

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.
