### ISSUE TITLE
Newsletters - Mexico .MX TLD not accepted by GUI

### ISSUE THREAD

**Issue by sienar1** [Tautulli/Tautulli-Issues#188]
Github wiped out my submission that was all typed up pretty in the format below. so not redoing that. The newsletter configuration in the To/CC/BCC sections does not allow email address with the Mexico TLD, eg name@example.mx. It is a valid TLD and the GUI appears to specifically disallow it. The From field allows arbitrary entry, so it works there.

tested in chrome 75 and firefox 68

VERSION V2.1.32
Git Branch: | beta
Git Commit Hash: | 6d35bd7947bad9e50772ab49bcc6c9c34979eeaa
Platform: | Linux 4.15.18-17-pve (#1 SMP PVE 4.15.18-43 (Tue, 25 Jun 2019 17:59:49 +0200) - Ubuntu 18.04 bionic)
Python Version: | 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

**Describe the Bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.1.29]
- Git Branch: [eg. master]
- Git Commit Hash: [eg. 2635569e765e5817400ed1032a27bfc850242f6a]
- Platform and Version: [eg. Windows 10]
- Python Version: [e.g. 2.7.16]
- Browser and Version: [e.g. Chrome 74]

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).

**Comment by JonnyWong16** [comment]
1. Template is not filled in properly.
2. This is not a bug report. Please use the [Discord Server](https://tautulli.com/discord) for support requests.

![image](https://user-images.githubusercontent.com/9099342/61593653-3f2f8100-ab97-11e9-8ac1-b2391c523eaa.png)
