### ISSUE TITLE
Include Kill Stream Functionality into Tautulli (JBOPS)

### ISSUE THREAD

**Issue by xInsertx** [Tautulli/Tautulli-Issues#189]
Hi,

It would be sweet to include some of the kill stream script functionality into Tautulli natively (rather than having to fiddle around to call a separate script). https://github.com/blacktwin/JBOPS/tree/master/killstream

I can see two ways to approach this.
#1 - Adding an "action" tab under notification agents with built-in actions that the existing logic can trigger.
#2 - Adding a new tab under Settings with options and logic to apply these new settings.

Features I think worth considering:

- Killing streams paused/idle for X (with conditional targeting/exclusion logic)
- Killing remote streams (with conditional targeting/exclusion logic)
- Limiting Streams by killing new streams over target limit (with conditional targeting/exclusion logic)

Most of this stuff can be mixed with existing logical conditions already present in Notification agents, so you could just add additional logic.

**Comment by JonnyWong16** [comment]
This is not a bug report.

https://github.com/Tautulli/Tautulli-Issues#feature-requests

**Comment by xInsertx** [comment]
@JonnyWong16 Opps sorry for of habit from using GitHub to long.
