### ISSUE TITLE
Unable to verify Plex Media Server during the setup wizard when using an unpublished hostname without SSL

### ISSUE THREAD

**Issue by igniscordis** [Tautulli/Tautulli-Issues#190]
**Describe the Bug**
It's impossible to verify a plex server instance via http during the first setup process.

**Steps to Reproduce**
1. Go to «Plex Media Server» step of «Tautulli Setup Wizard»
2. Enter a hostname and a port from the Relevant Settings into the corresponding fields
3. Leave the «Use SSL» option unchecked
4. Click «Verify!»
4. «This is not a Plex Server!» message is displayed

**Expected Behavior**
The specified instance of a plex server is verified.

**Relevant Settings**
- Plex is set up behind a proxy so that a request `HTTP GET hostname:port` returns an xml response containing «MediaContainer» node attributed with «machineIdentifier»
- DNS query for the hostname returns a local IP of the proxy server that does not correspond to the IP of the plex instance.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.1.33
- Git Branch:  master
- Git Commit Hash: 1046b29c1a1f7d7bd2c72743aaec695b1938b709
- Platform and Version: Windows 10
- Python Version: 2.7.16
- Browser and Version: Firefox 68.0.1

**Link to logs (required)**
[logs](https://gist.github.com/igniscordis/4208394eed50a849e77e1c70c1a745dd)

After looking at the [source code](https://github.com/Tautulli/Tautulli/blob/1046b29c1a1f7d7bd2c72743aaec695b1938b709/plexpy/webserve.py#L3630), it seems there is an issue with type conversion.
` def get_server_id(self, hostname=None, port=None, identifier=None, ssl=0, remote=0, manual=0, get_url=False, test_websocket=False, **kwargs):`
The «ssl» parameter here is expected to be a number but actually is received as a string.
Consequently, the following check for the scheme:
 `scheme = 'https' if ssl else 'http'`
results in «https» always being selected. 
I don't do any python but after a quick search for the type conversion options and putting there `ssl = int(ssl)`  the problem seems to go away.

**Comment by austinwbest** [comment]
Have the same issue as the original topic title. It **would not** verify my local ip, external ip, nothing. 10.1.0.6 with SSL enabled wont work.. Checked the https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=<TOKEN> and the computer is listed and the ip is as well. Killed the session and started over, 10.1.0.6 with SSL enabled worked fine.

**Comment by austinwbest** [comment]
Marked my previous post off topic & ignored it instead of at least responding? What a joke. Guess the bug will stay as it is swept under the rug so devs can act like it doesn't exist. Uninstalling this.

**Comment by JonnyWong16** [comment]
The original issue was already fixed in Tautulli/Tautulli@7b16af0.

Your issue is likely completely different. Please use the [Discord server](https://tautulli.com/discord) to see if we can resolve it first.
