### ISSUE TITLE
Hardware decoding (HW) not reflected in GUI

### ISSUE THREAD

**Issue by rcork** [Tautulli/Tautulli-Issues#193]
**Describe the Bug**
I installed the latest Plex transcoder beta 1.16.7.1597 which now support hardware decoding on linux with NVidia GPU. When playing back a 4K video that is being transcoded to 1080P, Plex reflects that it is using hardware transcoding for both the decode and the encode but Tautulli only reflects the encoding in the gui.

**Steps to Reproduce**
1. Start playing a 4k video on plex from a client that requires transcoding
2. Verify on Plex dashboard that hardware transcoding is being used for both decode and encode
3. Open Tautulli and look if it denotes hardware transcoding is denoted for both decode and encode

**Expected Behavior**
Tautulli should show '(HW)' on the left side of the arrow (indicating HW decode) and the right side of the arrow (indicating HW encode)

**Screenshots**
![Screenshot from 2019-09-09 18-33-38](https://user-images.githubusercontent.com/3687003/64577141-71a46180-d330-11e9-9394-abe9618e6cc8.png)

![Screenshot from 2019-09-09 18-33-28](https://user-images.githubusercontent.com/3687003/64577148-76691580-d330-11e9-803f-ee4d0cb03574.png)

**Relevant Settings**
1. PMS 1.16.7.1597 transcoder preview installed (https://forums.plex.tv/t/plex-media-server-1-16-7-1597-updated-new-transcoder-preview/451135/41)
2. Hardware transcoding enabled in Plex settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.1.34
- Git Branch: master
- Git Commit Hash: 08714436c3a7665abeb621b9fe52cc8b779c5473
- Platform and Version: [Docker] Linux 3.10.105 (#24922 SMP Wed Jul 3 16:37:24 CST 2019)
- Python Version: 2.7.16
- Browser and Version: Firefox 69

**Link to logs (required)**
https://gist.github.com/rcork/e751c2dcdbec9edee4c364198b2c8ec7

**Comment by JonnyWong16** [comment]
Bug report template not filled in.

**Comment by rcork** [comment]
> Bug report template not filled in.

template filled in

**Comment by samwiseg0** [comment]
You will need to also provide the raw activity from plex. Please see [debugging](https://github.com/Tautulli/Tautulli-Wiki/wiki/Debugging#activity).

**Comment by rcork** [comment]
Raw activity XML:
`<MediaContainer size="1">
<Video addedAt="1520694896" art="/library/metadata/320923/art/1520706138" chapterSource="media" contentRating="TV-G" duration="3075913" grandparentArt="/library/metadata/320923/art/1520706138" grandparentGuid="com.plexapp.agents.thetvdb://330942?lang=en" grandparentKey="/library/metadata/320923" grandparentRatingKey="320923" grandparentTheme="/library/metadata/320923/theme/1520706138" grandparentThumb="/library/metadata/320923/thumb/1520706138" grandparentTitle="Blue Planet II" guid="com.plexapp.agents.thetvdb://330942/1/1?lang=en" index="1" key="/library/metadata/320925" lastViewedAt="1568083798" librarySectionID="40" librarySectionKey="/library/sections/40" librarySectionTitle="4K TV Shows" originallyAvailableAt="2017-10-29" parentGuid="com.plexapp.agents.thetvdb://330942/1?lang=en" parentIndex="1" parentThumb="/library/metadata/320924/thumb/1520706138" parentTitle="Season 1" rating="9.5" ratingKey="320925" sessionKey="17" skipParent="1" summary="Footage of marine life in different environments around the north, beginning with a tropical coral reef which has medicinal properties for dolphins, and is used as a tool by tusk fish. In Japan, a shipwreck is home to the Asian sheepshead wrasse, which can change gender, while in the polar north, walruses struggle to find ice floes for their pups to rest on as climate change takes its toll on the environment." thumb="/library/metadata/320925/thumb/1559675780" title="One Ocean" type="episode" updatedAt="1559675780" viewCount="1" viewOffset="1152000" year="2017">
<Media audioProfile="ma" id="596008" videoProfile="main 10" audioChannels="2" audioCodec="aac" bitrate="69125" container="mp4" duration="3075913" height="1280" optimizedForStreaming="1" protocol="dash" videoCodec="h264" videoFrameRate="24p" videoResolution="1080p" width="2276" selected="1">
<Part audioProfile="ma" id="647789" indexes="sd" videoProfile="main 10" bitrate="69125" container="mp4" duration="3075913" height="1280" optimizedForStreaming="1" protocol="dash" width="2276" decision="transcode" selected="1">
<Stream bitrate="68869" codec="h264" colorPrimaries="bt2020" colorTrc="smpte2084" displayTitle="4K (HEVC Main 10 HDR)" frameRate="23.975999999999999" height="1280" id="1270566" language="English" languageCode="eng" streamType="1" width="2276" decision="transcode" location="segments-video"/>
<Stream bitrate="256" bitrateMode="cbr" channels="2" codec="aac" default="1" displayTitle="English (DTS-HD MA 5.1)" id="1270567" language="English" languageCode="eng" selected="1" streamType="2" decision="transcode" location="segments-audio"/>
</Part>
</Media>
<Director filter="director=139844" id="139844" tag="Jonathan Smith"/>
<User id="1" thumb="https://plex.tv/users/be31412862c6c9f7/avatar?c=1558324444" title="rcork"/>
<Player address="192.168.10.209" device="OSX" machineIdentifier="iiv7uec2s2ivh1iu4brtwafm" model="hosted" platform="Firefox" platformVersion="68.0" product="Plex Web" profile="Firefox" remotePublicAddress="" state="playing" title="Firefox" vendor="" version="4.4.1" local="1" relayed="0" secure="1" userID="1"/>
<Session id="zyj0e8c7x8i90zuket9wrkix" bandwidth="72582" location="lan"/>
<TranscodeSession key="/transcode/sessions/s7dxbg45b7p3xs6dre7oj8ma" throttled="1" complete="0" progress="40.200000762939453" speed="0" duration="3075906" remaining="21821" context="streaming" sourceVideoCodec="hevc" sourceAudioCodec="dca" videoDecision="transcode" audioDecision="transcode" protocol="dash" container="mp4" videoCodec="h264" audioCodec="aac" audioChannels="2" transcodeHwRequested="1" transcodeHwDecoding="nvdec" transcodeHwEncoding="nvenc" transcodeHwDecodingTitle="NVIDIA (NVDEC)" transcodeHwFullPipeline="1" transcodeHwEncodingTitle="NVIDIA (NVENC)" timeStamp="1568083798.4895797" maxOffsetAvailable="1234.9866666666669" minOffsetAvailable="1016.0159912109375"/>
</Video>
</MediaContainer>`

Raw stream info:
`

{
    "actors": [
        "David Attenborough"
    ],
    "added_at": "1520694896",
    "allow_guest": 0,
    "art": "/library/metadata/320923/art/1520706138",
    "aspect_ratio": "1.78",
    "audience_rating": "",
    "audience_rating_image": "",
    "audio_bitrate": "2225",
    "audio_bitrate_mode": "",
    "audio_channel_layout": "5.1(side)",
    "audio_channels": "6",
    "audio_codec": "dca",
    "audio_decision": "transcode",
    "audio_language": "English",
    "audio_language_code": "eng",
    "audio_profile": "ma",
    "audio_sample_rate": "48000",
    "bandwidth": "72582",
    "banner": "/library/metadata/320923/banner/1520706138",
    "bif_thumb": "/library/parts/647789/indexes/sd/1232000",
    "bitrate": "47331",
    "channel_stream": 0,
    "children_count": "",
    "collections": [],
    "container": "mkv",
    "content_rating": "TV-G",
    "deleted_user": 0,
    "device": "OSX",
    "directors": [
        "Jonathan Smith"
    ],
    "do_notify": 1,
    "duration": "3075913",
    "email": "robcork@gmail.com",
    "file": "/mnt/media/Plex/4K TV/Blue Planet II/Season 01/Blue Planet II - S01E01.mkv",
    "file_size": "18200090267",
    "friendly_name": "rcork",
    "full_title": "Blue Planet II - One Ocean",
    "genres": [
        "Documentary"
    ],
    "grandparent_rating_key": "320923",
    "grandparent_thumb": "/library/metadata/320923/thumb/1520706138",
    "grandparent_title": "Blue Planet II",
    "guid": "com.plexapp.agents.thetvdb://330942/1/1?lang=en",
    "height": "2160",
    "id": "",
    "indexes": 1,
    "ip_address": "192.168.10.209",
    "ip_address_public": "",
    "is_admin": 1,
    "is_allow_sync": 1,
    "is_home_user": 1,
    "is_restricted": 0,
    "keep_history": 1,
    "labels": [],
    "last_viewed_at": "1568083798",
    "library_name": "4K TV Shows",
    "live": 0,
    "live_uuid": "",
    "local": 1,
    "location": "lan",
    "machine_id": "iiv7uec2s2ivh1iu4brtwafm",
    "media_index": "1",
    "media_type": "episode",
    "optimized_version": 0,
    "optimized_version_profile": "",
    "optimized_version_title": "",
    "original_title": "",
    "originally_available_at": "2017-10-29",
    "parent_media_index": "1",
    "parent_rating_key": "320924",
    "parent_thumb": "/library/metadata/320924/thumb/1520706138",
    "parent_title": "Season 1",
    "platform": "Firefox",
    "platform_name": "firefox",
    "platform_version": "68.0",
    "player": "Firefox",
    "product": "Plex Web",
    "product_version": "4.4.1",
    "profile": "Firefox",
    "progress_percent": "40",
    "quality_profile": "Original",
    "rating": "9.5",
    "rating_image": "",
    "rating_key": "320925",
    "relayed": 0,
    "section_id": "40",
    "secure": 1,
    "selected": 1,
    "session_id": "zyj0e8c7x8i90zuket9wrkix",
    "session_key": "17",
    "shared_libraries": [
        "39",
        "40",
        "3",
        "1",
        "48",
        "2"
    ],
    "sort_title": "",
    "state": "playing",
    "stream_aspect_ratio": "",
    "stream_audio_bitrate": "256",
    "stream_audio_bitrate_mode": "cbr",
    "stream_audio_channel_layout": "Stereo",
    "stream_audio_channel_layout_": "",
    "stream_audio_channels": "2",
    "stream_audio_codec": "aac",
    "stream_audio_decision": "transcode",
    "stream_audio_language": "English",
    "stream_audio_language_code": "eng",
    "stream_audio_sample_rate": "",
    "stream_bitrate": "69125",
    "stream_container": "mp4",
    "stream_container_decision": "transcode",
    "stream_duration": "3075913",
    "stream_subtitle_codec": "",
    "stream_subtitle_container": "",
    "stream_subtitle_decision": "",
    "stream_subtitle_forced": 0,
    "stream_subtitle_format": "",
    "stream_subtitle_language": "",
    "stream_subtitle_language_code": "",
    "stream_subtitle_location": "",
    "stream_video_bit_depth": "",
    "stream_video_bitrate": "68869",
    "stream_video_codec": "h264",
    "stream_video_codec_level": "",
    "stream_video_decision": "transcode",
    "stream_video_framerate": "24p",
    "stream_video_height": "1280",
    "stream_video_language": "English",
    "stream_video_language_code": "eng",
    "stream_video_ref_frames": "",
    "stream_video_resolution": "1080",
    "stream_video_width": "2276",
    "studio": "BBC One",
    "subtitle_codec": "",
    "subtitle_container": "",
    "subtitle_decision": "",
    "subtitle_forced": 0,
    "subtitle_format": "",
    "subtitle_language": "",
    "subtitle_language_code": "",
    "subtitle_location": "",
    "subtitles": 0,
    "summary": "Footage of marine life in different environments around the north, beginning with a tropical coral reef which has medicinal properties for dolphins, and is used as a tool by tusk fish. In Japan, a shipwreck is home to the Asian sheepshead wrasse, which can change gender, while in the polar north, walruses struggle to find ice floes for their pups to rest on as climate change takes its toll on the environment.",
    "synced_version": 0,
    "synced_version_profile": "",
    "tagline": "",
    "throttled": "1",
    "thumb": "/library/metadata/320925/thumb/1559675780",
    "title": "One Ocean",
    "transcode_audio_channels": "2",
    "transcode_audio_codec": "aac",
    "transcode_container": "mp4",
    "transcode_decision": "transcode",
    "transcode_height": "",
    "transcode_hw_decode": "nvdec",
    "transcode_hw_decode_title": "NVIDIA (NVDEC)",
    "transcode_hw_decoding": 0,
    "transcode_hw_encode": "nvenc",
    "transcode_hw_encode_title": "NVIDIA (NVENC)",
    "transcode_hw_encoding": 1,
    "transcode_hw_full_pipeline": 1,
    "transcode_hw_requested": 1,
    "transcode_key": "/transcode/sessions/s7dxbg45b7p3xs6dre7oj8ma",
    "transcode_progress": 43,
    "transcode_protocol": "dash",
    "transcode_speed": "0.0",
    "transcode_throttled": 1,
    "transcode_video_codec": "h264",
    "transcode_width": "",
    "type": "",
    "updated_at": "1559675780",
    "user": "rcork",
    "user_id": 359786,
    "user_rating": "",
    "user_thumb": "https://plex.tv/users/be31412862c6c9f7/avatar?c=1558324444",
    "username": "rcork",
    "video_bit_depth": "10",
    "video_bitrate": "43573",
    "video_codec": "hevc",
    "video_codec_level": "153",
    "video_decision": "transcode",
    "video_frame_rate": "23.976",
    "video_framerate": "24p",
    "video_height": "2160",
    "video_language": "English",
    "video_language_code": "eng",
    "video_profile": "main 10",
    "video_ref_frames": "1",
    "video_resolution": "4k",
    "video_width": "3840",
    "view_offset": "1232000",
    "width": "3840",
    "writers": [],
    "year": "2017"
}

`

**Comment by samwiseg0** [comment]
Please place it in a gist or wrap it in a code block.

**Comment by rcork** [comment]
Edited post above to wrap in code block

**Comment by LrrrAc** [comment]
I have the same issue.

**Comment by docwho76** [comment]
FYI, the latest PlexPass version 1.17.x fromt Sept 13th includes this nvdec support on Linux so this will start to become more prevalent
