### ISSUE TITLE
Tautuilli previous history

### ISSUE THREAD

**Issue by sp33dman** [Tautulli/Tautulli-Issues#198]
I have just installed Tautuilli on windows 10 and is working great. I have had my plex server running for quite some time now and the watch statistics are not showing in Tautuilli. Does Tautuilli gather the watch history from the server or can it only catch this after it was installed?

Is there a way to import the watch stats from the server to Tautilli?

**Comment by Arcanemagus** [comment]
[Can Tautulli import history from before it was installed?](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#history-q5)
