### ISSUE TITLE
migration to Python3 

### ISSUE THREAD

**Issue by fliiiix** [Tautulli/Tautulli-Issues#200]
Python 2 is deprecated [very soon]( https://pythonclock.org/ ).
So I guess it is time to upgrade. 
I would love to help and I think the first step would be to replace the [copied versions of libraries](https://github.com/Tautulli/Tautulli/tree/master/lib) with something like a requirements.txt or a setup.py file with dependencies. 

Are you open to such changes? If so let me know. If not please just close this issue.

**Comment by NvrBst** [comment]
Tautulli is the only Python2 application I am running. I get a big WARNING when I start my computer now saying PYTHON2 is depreciated. Is there any plans to get Tautilli updated to Python3? Are there any major hurdles on why Python3 isn't an option?

**Comment by fliiiix** [comment]
The only big migration part I see are all the lib which are copied. (This is the PR I started) 
Other than that I don't think it would be too complicated to migrate. But I didn't had time to continue with my PR.

**Comment by ChaosBlades** [comment]
The zSeriesGuy fork requires Python 3.5 or higher. Maybe at least short term solution would be to move over to that fork.

https://github.com/zSeriesGuy/Tautulli

**Comment by mercury00** [comment]
I would be happy to take a look.

Is there any external dependency on python2?   I've done this a dozen times with other code, the py2 to py3 migration is not impossible, just a matter of updating some code, apis, and testing.

**Comment by fliiiix** [comment]
@mercury00 as stated in the initial post the main issue are the copied libs I guess

**Comment by mercury00** [comment]
OK. Well, I dumbly updated those to whatever was latest.

The Cherrypy api has changed though. Not sure how to code around that. Had to just comment out the timeout_manager part for now.

I got it running in python 3.8, however it goes through the initial setup, gets my credentials, gets my server, has me say okay, waits 5 seconds for the 'token', then... starts over, with no error.

I did a rather dumb python2 to python3 conversion without deeply analyzing the code, so I'm not yet clear on what's wrong but I'll see if maybe I can trace what's happening and what needs to be fixed.
Probably lots of things. But this could be a start, no?

https://github.com/mercury00/Tautulli/tree/upgrade-python3

**Comment by mercury00** [comment]
Also, I did a git add -u for the changed libs, however they pulled in dependencies that are untracked in my working folder. I haven't tested which of these are unnecessary yet. I'm running this in a venv myself so that I can see every lib it needs clean from the system libs. Anyway, will have more time later I suppose.

**Comment by mercury00** [comment]
Actually my branch upgrade-python3 works ok for http / no username/pass no auth when I already have a tautulli.db and config.ini

So, something is likely broken with plexapi. I'll have to see if I can narrow down what.

I've added more of the missing libs - it 'works' for me at the moment but thats because I was able to use an existing db and config file from the previous tautulli. also, I forked from master, not nightly.

**Comment by samip5** [comment]
What's the current status of migrating to Python 3?

**Comment by mercury00** [comment]
After doing a blind conversion (2to3) and testing, it "works" for unauthenticated access.

I think the real upgrade path is instead to do like so: finish felixs migration of vendor libs (there's three that can't be migrated, they can't easily get installed by users, but they'll just stay in the lib folder) for python 2, by putting the required library versions in requirements.txt. That removes them from tautulli and they get installed the way otther python programs install requirements.

Test that it's working.

Then, update the plexpy code to assume py3 and on error fallback to py2 for compatibility with older systems. Most of that is aliasing migrated functions and such. I've done that with a few already.

I'm doing it using venvs to ensure full library support etc. It should be noted that some of the libraries require system libraries to install (non-python). That will have to be added to the install instructions.

I'll put my edits into a branch on my repo and make a pull request with a finished migration for py2 hopefully tomorrow, Felix's PR is incomplete.

--
Aaron

________________________________

**Comment by mercury00** [comment]
First step done actually (I think, my tests work but may need a deeper review). removed the libs that can be removed and replaced with a requirements.txt file.
