### ISSUE TITLE
Notification - session_id is empty on stream

### ISSUE THREAD

**Issue by salimnanji** [Tautulli/Tautulli-Issues#201]
I have a script that will terminate sessions based off of a few different factors. This script has been working correctly for months now, but I'm seeing that when a particular user is streaming, no session_id is available, and their session can not be killed. The user is streaming directly from my server through a chromecast with the Plex app. I can see the device name in my Tautulli history.

The Notification Script Arguments are set correctly:
`-sid {session_id} -sk {session_key} -ip {ip_address} -us {username} -tt {title} -lan {stream_local}`

Normal User:
'2019-10-29 09:52:58 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Trying to run notify script, action: play, arguments: [u'-sid', u'3d242068dga37b-com-plexapp-android', u'-sk', u'5', u'-ip', u'72.***.***.***', u'-us', u'username2', u'-tt', u'TV Show', u'-lan', '0']'

Affected User:
`2019-10-28 18:42:43 - DEBUG   :: Thread-1 : Tautulli Notifiers :: Trying to run notify script, action: play, arguments: [u'-sid', '', u'-sk', u'1', u'-ip', u'104.***.***.***', u'-us', u'username', u'-tt', u'TV Show', u'-lan', '0']`

I've tried calling the terminate_session api using both session_key and session_id, both fail since there doesnt seem to be an associated session_id.

`Tautulli API 'kill_user_stream' request failed: Failed to terminate session: Missing session_id.`

I'm on Tautulli V2.1.37 and PLEX v1.18.0.1944

**Comment by JonnyWong16** [comment]
Chromecast is bugged on Plex's end. Nothing Tautulli can do about it.

https://forums.plex.tv/t/chromecast-wont-transcode/462231
https://forums.plex.tv/t/playback-merged-between-2-accounts/461698

**Comment by salimnanji** [comment]
Thanks. Thought I searched that already. 
Don't know how I missed it.
