### ISSUE TITLE
"Bandwidth" hidden when HW encode and HW decode

### ISSUE THREAD

**Issue by rcork** [Tautulli/Tautulli-Issues#202]
**Describe the Bug**
When media is playing that uses hardware for both the encoding and decoding, the "Bandwidth" field is hidden and requires you to scroll within the activity info <div>

**Steps to Reproduce**
1. Within Plex, enable hardware transcoder
2. Ensure you are using hardware and OS that supports both hardware decode and encode (ie. Nvidia on Linux)
3. In Tautulli, verify the activity info shows both (HW) for both the encode and decode (it should show (HW twice)
4. The Bandwidth label and value is hidden

**Expected Behavior**
All fields (Product, Player, Quality, Stream, Container, Video, Audio, Subtitle, Location and Bandwidth are visible in the activity info without needing to scroll the <div>

**Screenshots**
Here is a screenshot showing the Bandwidth field hidden below Location
![Screenshot from 2019-11-25 16-09-22](https://user-images.githubusercontent.com/3687003/69589130-d40c1600-0f9f-11ea-9f8f-51e43ad9c72b.png)

Here is a screenshot when scrolling down in the activity section
![Screenshot from 2019-11-25 16-09-07](https://user-images.githubusercontent.com/3687003/69589102-b63eb100-0f9f-11ea-9a6b-d242f57c913c.png)

**Relevant Settings**
Plex Media Server - Hardware Transcoder enabled

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.1.38
- Git Branch: master
- Git Commit Hash: a637b3bb2419e5f5b32f9fcfb8dae86860d1f0d9
- Platform and Version: docker running on Synology NAS
- Python Version: 2.7.16
- Browser and Version: Firefox 70.0.1

**Link to logs (required)**
https://gist.github.com/rcork/487b21ce4991aef3d8761e291863f67f

**Comment by TheMeanCanEHdian** [comment]
The area with the stream details is scrollable when the text overflows.
