### ISSUE TITLE
Migrated jail/server, can't install GeoIP database

### ISSUE THREAD

**Issue by MrBrax** [Tautulli/Tautulli-Issues#204]
**Describe the Bug**
It expects the database to be at /usr/local/share/plexpy/GeoLite2-City.mmdb but the new jail mounts the data at /config, therefore the GeoIP install fails. Can't reset the path.

**Steps to Reproduce**
1. Change config path when migrating
2. Try to install GeoIP database

**Expected Behavior**
Successful install

**Screenshots**
![157548985026760](https://user-images.githubusercontent.com/1517911/70176941-aa5a9980-16d9-11ea-8331-267c0762aded.png)

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.1.38
- Git Branch: master
- Git Commit Hash: a637b3bb2419e5f5b32f9fcfb8dae86860d1f0d9
- Platform and Version: FreeBSD 11.2-STABLE
- Python Version: 2.7.16
- Browser and Version: Firefox 70

**Link to logs (required)**
```2019-12-04 20:56:33 - INFO    :: CP Server Thread-11 : Tautulli Config :: Writing configuration to file
2019-12-04 20:56:45 - DEBUG   :: CP Server Thread-8 : Tautulli Helpers :: Downloading GeoLite2 gzip file from MaxMind...
2019-12-04 20:56:48 - DEBUG   :: CP Server Thread-8 : Tautulli Helpers :: Extracting GeoLite2 database...
2019-12-04 20:56:48 - ERROR   :: CP Server Thread-8 : Tautulli Helpers :: Failed to extract the GeoLite2 database: [Errno 2] No such file or directory: '/usr/local/share/plexpy/GeoLite2-City.mmdb'
```

This should be the only required logs, too much personal info in the full ones.

**Comment by Arcanemagus** [comment]
This is a support problem, not a bug in Tautulli. You need to remove (default) or fix the paths in your configuration file _as [the FAQ](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q11) tells you to do_.

**Comment by MrBrax** [comment]
Thanks but no thanks. Have a nice day.
