### ISSUE TITLE
WARNING - No image input received.

### ISSUE THREAD

**Issue by ApolloGods** [Tautulli/Tautulli-Issues#206]
Hello,

Someone can handle this warning with me please?
Cannot find to resolve it..
the only message is 

WARNING | No image input received

but from whom, where or wich file, title, date, metadata problem, id problem... really no img?..
 there are too many questions for me to solve this warning.
please help someone
thanks a lot

logfile:
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/3964210/tautulli.log)

**Comment by JonnyWong16** [comment]
It's fine. Just ignore it.
