### ISSUE TITLE
Verifying server with custom hostname fails due to use of re.fullmatch()

### ISSUE THREAD

**Issue by codingwithcurt** [Tautulli/Tautulli-Issues#209]
**Describe the Bug**
In commit https://github.com/Tautulli/Tautulli/commit/f5794a5baedfe8b0e82e46bfa09647fb3402252b a bug was introduced when attempting to validate a server by hostname, instead of IP address. The input validation calls `re.fullmatch` which [is only available in Python 3.4+](https://docs.python.org/3/library/re.html#re.fullmatch).

This causes validation of Plex servers where a hostname string is entered as the server address to fail with a 500 internal server error (due to the traceback produced for the missing function).

**Steps to Reproduce**
1. Open Tautulli
2. Go to 'Settings' (click top-right > Settings)
3. Choose 'Plex Media Server' pane
4. In 'Plex IP Address or Hostname' enter a hostname, not an IP address and check the Remote + SSL checkboxes
5. Click Verify Server

**Expected Behavior**
Server validates successfully when Plex is indeed hosted at the hostname+port entered

**Screenshots**

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.1.39
- Git Branch: master
- Git Commit Hash: None
- Platform and Version: Docker (linuxserver.io) on Linux 5.3.16
- Python Version: 2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]
- Browser and Version: Latest Chrome (as of writing 79.0.3945.88)

**Link to logs (required)**
The failure in the get_server_id API call returns a 500 but produces no entries in the log messages, which I found interesting

**Comment by codingwithcurt** [comment]
```
Traceback (most recent call last):
  File "/app/tautulli/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/tautulli/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/tautulli/lib/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/app/tautulli/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/tautulli/plexpy/helpers.py", line 66, in wrapper
    return function(*args, **kwargs)
  File "/app/tautulli/plexpy/webserve.py", line 3670, in get_server_id
    ip_address = get_ip(hostname)
  File "/app/tautulli/plexpy/helpers.py", line 568, in get_ip
    elif not re.fullmatch(r'[0-9]+(?:\.[0-9]+){3}(?!\d*-[a-z0-9]{6})', host):
AttributeError: 'module' object has no attribute 'fullmatch'
```

**Comment by Arcanemagus** [comment]
Already fixed in https://github.com/Tautulli/Tautulli/commit/b7bb159630f26761ad39d42d75d55c634abcc7a1, thanks for the report!
