### ISSUE TITLE
Telegram Notifications not formatting with HTML

### ISSUE THREAD

**Issue by 1activegeek** [Tautulli/Tautulli-Issues#21]
**Version:**
2.0.22
**Branch:**
Master
**Commit hash:**
a08bce2073b1847762a22a843b13acc5f996d9cb
**Operating system:**

Linux 4.14.16-unRAID
**Python version:**
2.7.14 (default, Feb 22 2018, 21:59:35) [GCC 6.3.0]
**What you did?**
Created notifications for Telegram to send upon newly added content to the library which used HTML styling for the formatting. I think this may be related to #20 as they outlined the use of image caption for Telegram sending. This would possibly explain why the HTML formatting would be lost.
**What happened?**
Notifications were received, but missing the formatting specified.
**What you expected?**
Notifications with the correct formatting.

**How can we reproduce your issue?**

1. Create a new telegram notification agent
2. Ensure that include poster image is marked
3. Ensure HTML support is ticked
4. Set the newly added content option
5. Set the Subject to use html tags `<b> </b>` for example
6. Force media update or wait for media update
7. Telegram message received with no formatting as expected. 

Subject Text:
```
<b>New {media_type!c} Available</b>
```
Body Text:
```
<movie>{title} ({year}) - Runtime {duration} {imdb_url}</movie><show>{show_name} {thetvdb_url}</show><season>{show_name} - Season {season_num00} {thetvdb_url}</season><episode>{show_name} - S{season_num00}E{episode_num00} - {episode_name} {thetvdb_url}</episode>
```
**What are your (relevant) settings?**
- Include Poster Image
- Enable HTML tags
- Add HTML tags to the message/subject

**Logs:**
No error logs

**Screenshots:**
![screen shot 2018-03-14 at 8 58 24 am](https://user-images.githubusercontent.com/6810720/37404108-3f1ede14-2767-11e8-86d6-f393a3b283b1.png)
![screen shot 2018-03-14 at 8 58 33 am](https://user-images.githubusercontent.com/6810720/37404109-3f2c74fc-2767-11e8-8fd2-4c24dca0bdfc.png)

**Comment by JonnyWong16** [comment]
This might be a bug with Telegram photo captions since I am sending the correct `parse_mode=HTML` value.

**Comment by 1activegeek** [comment]
So I dug into it a bit. Played with some manual runs and formats and tried both HTML and Markdown, neither are working (not in Tautulli). So I think I can confirm your notion that it's actually telegram not doing something correct. I have a feeling they either have a bug, or did some copy paste job from the sendMessage documentation and left that in there. Being that the caption has a limit of 200 chars also makes me believe that its not supported or not supposed to be. 

I've opened up a support chat with them to note it and see what I can get. I'll ping you back on this issue if I get anywhere. If changes are required, I'll see if I can get cobble them together and submit a PR. Closing this for now.

**Comment by JonnyWong16** [comment]
Thanks for the update.

**Comment by enchained** [comment]
I think telegram does not support HTML captions in some clients for now. Please do a "caption" word search on this channel for details: https://t.me/tgbeta
For example, I think there is b/i/monospace/url support in the stable Mac client, alpha Desktop client, Telegram 4.8 on Android, Telegram X 5.0.2 on iOS, but I don't have any of those to test. I think this feature could probably be added to most of the clients in the next few month.
For now, what can be done (and for #20 issue too) is always send too long notifications as messages, and  an option to never sent then as captions.

**Comment by 1activegeek** [comment]
@enchained it looks as though you are correct. I just updated the Mac client to the latest and do in fact see the correct formatting! Apparently the iOS app has a few version to make through the app store before it's available, but this is pretty great. The most common place I see this right now is Mac desktop app.

Still no word back from the support message I sent, but in leu of that this obviously makes sense. So I guess @JonnyWong16 if anyone else brings it up - it's for sure a telegram issue, and should make its way to clients shortly.

**Comment by JonnyWong16** [comment]
Telegram 4.8 on Android also doesn't show formatting (yet).

**Comment by 1activegeek** [comment]
Looks like there is a 4.8.4 in play store. That Beta channel said 4.8 (1206). Maybe .4 is the 1206 build?

**Comment by JonnyWong16** [comment]
Oh, HTML formatting does work on Telegram 4.8.4 on Android.
