### ISSUE TITLE
New version 2.1.41 has a big settings bug

### ISSUE THREAD

**Issue by ALoubert** [Tautulli/Tautulli-Issues#210]
I was running v2.1.39 without any problem till today.
I saw a new v2.1.41 came out yesterday, so I upgraded my v2.1.39 to v2.1.41.

Upgrade went by with no issue.
But when connected to v2.1.41, when I went to the settings page, I got the following result:

Error !
KeyError: 'maxmind_license_key'
<label for="maxmind_license_key">MaxMind License Key</label> <div class="row"> <div class="col-md-6"> <input type="text" class="form-control" id="maxmind_license_key" name="maxmind_license_key" value="${config['maxmind_license_key']}" data-parsley-trigger="change"> </div> </div> <p class="help-block"> Enter and save your MaxMind License Key to install the GeoLite2 database. </p>
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/data/interfaces/default/settings.html, line 1241: <input type="text" class="form-control" id="maxmind_license_key" name="maxmind_license_key" value="${config['maxmind_license_key']}" data-parsley-trigger="change">
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/data/interfaces/default/base.html, line 165: ${next.body()}
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/mako/runtime.py, line 860: callable_(context, *args, **kwargs)
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/mako/runtime.py, line 835: _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/mako/runtime.py, line 803: **_kwargs_for_callable(callable_, data))
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/lib/mako/template.py, line 443: return runtime._render(self, self.callable_, args, data)
/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/webserve.py, line 78: _session=_session, **kwargs)

It seems to be related to the MaxMind GeoLite2 database, but I don't have it installed on my Tautulli config.
I even can't install it; if I try, I'm getting an error "Tautulli Helpers :: Downloading GeoLite2 gzip file from MaxMind..." followed by "Tautulli Helpers :: Failed to download GeoLite2 gzip file from MaxMind: [Errno socket error] [Errno -2] Name or service not known". I also don't have any place (3rd party API keys) where to set a MaxMind license..."
In all cases, the GeoLite database isn't mandatory, is it ?
So, I don't have it and don't need it.

Tautulli was working perfectly without, so I don't see why it couldn't continue in new version.

I reinstalled v2.1.39 over v2.1.41, and everything OK again. For now.
But it means there's an issue with the last version, and that should be corrected.

Can someone help ?

**Comment by Arcanemagus** [comment]
This is a support issue, as you were [already told](https://www.reddit.com/r/Tautulli/comments/eiws4g/new_version_2141_has_a_big_settings_bug/fcuioak/). Please do not post in multiple places, and definitely don't file an issue for something that isn't a bug.

If you are looking for more interactive support please use the [Discord server](http://tautulli.com/discord).
