### ISSUE TITLE
Movies Icon

### ISSUE THREAD

**Issue by Takhsis01** [Tautulli/Tautulli-Issues#212]
My movies Icon in "Libraries" seems to be set to a bing link that pulls up a...less than savory image.  I'm unsure if it was somehow changed on my side, but I thought I'd let you know just in case it isn't.  This is using the Tautulli/Tautulli docker image.

Here is a snip of what I'm seeing:

![image](https://user-images.githubusercontent.com/49572974/71913904-0e8bd580-313e-11ea-9acc-70a42862e4a8.png)

**Comment by samwiseg0** [comment]
This seems like you have an extension or malware on your machine causing this. This is not a Tautulli issue.

**Comment by willmaticx** [comment]
Takhsis01 did you ever find out what was causing this? I had the same thing happen to my audiobooks library.

**Comment by Takhsis01** [comment]
I did not.  It's on a Linux box in a docker container, so I don't know what could have infected it. I suppose you could find that php file and edit the correct value in.  I just nuked out my configs and started over.

**Comment by willmaticx** [comment]
Wow thanks for the quick response. Mine was on a windows box and I was able to simply blank out that field via the "Library Thumbnail URL" via the Tautulli UI. What an obscure thing for malware to bother with...

**Comment by JonnyWong16** [comment]
More likely you have Tautulli exposed to the internet without securing it and someone found it and changed your icons.

**Comment by willmaticx** [comment]
You might be right, I'll double check those settings. Thanks all!

**Comment by Takhsis01** [comment]
That definitely could have been the issue.  I don't recall if I had mine take credentials before, but I do now.
