### ISSUE TITLE
Music tab is shown even though there aren't any records

### ISSUE THREAD

**Issue by agneevX** [Tautulli/Tautulli-Issues#213]
**Describe the Bug**
Tautulli shows Music tab even though there aren't any data for Music.
<img width="696" alt="image" src="https://user-images.githubusercontent.com/19761269/72206866-b7c52980-34b8-11ea-9d54-742df8dbf9f5.png">

**Expected Behavior**
Music tab shouldn't show. 

**Tautulli and System Info**
- Version: 2.1.42
- Git Branch: master
- Git Commit Hash: c8f132a750c81444e2b4e725908067703e3d7f58
- Platform and Version:  Debian 10 Buster (Raspbian)
- Python 2.7.16

**Comment by JonnyWong16** [comment]
That's not a bug. Just don't click the button.

**Comment by agneevX** [comment]
Why should it show if there aren't any records?

**Comment by TheMeanCanEHdian** [comment]
That doesn't make it a bug, it makes it a feature request.
https://feathub.com/Tautulli/Tautulli
