### ISSUE TITLE
[Feature Request] Concurrent stream timer

### ISSUE THREAD

**Issue by goose-ws** [Tautulli/Tautulli-Issues#214]
I have the notification enabled for concurrent streams; however, when a user changes quality or immediately switches from streaming one file to another, I'll get a notification about concurrent streams. Assumedly because for a second, there are two from the same client. Would it be possible to add a "timer" to the concurrent streams notification? Configurable or hard coded, but either way, to give a "10 second grace period" before concurrent streams (above 2, anyways) any triggered.

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Issues/blob/master/README.md#feature-requests
