### ISSUE TITLE
Future Request: Gotify Notifications 

### ISSUE THREAD

**Issue by Hobbabobba** [Tautulli/Tautulli-Issues#215]
Gotify is a very simple notification service - you can selfhost it. Ideal as a companion for a selfhosted plex/tautulli environment.

https://gotify.net/

**Comment by TheMeanCanEHdian** [comment]
Feature requests go on FeatHub
https://feathub.com/Tautulli/Tautulli

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/pull/1348#issuecomment-482814761
