### ISSUE TITLE
Username changed - Tautulli hacked

### ISSUE THREAD

**Issue by fArGo1911** [Tautulli/Tautulli-Issues#217]
Today I noticed that my user name including account picture changed in Tautulli. Just my Tautulli name (admin) meaning the Plex account has not been compromised. Anyone else noticed the same?

**Comment by JonnyWong16** [comment]
Not s bug report. Do not post in multiple places. 

https://www.reddit.com/r/Tautulli/comments/etrfff/tautulli_hacked_my_username_changed/
