### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by wazerstar** [Tautulli/Tautulli-Issues#218]
I do not know where to state or ask this, so I will try here.

Got this mail from github about Tautulli using Deprecated stuff

```
On February 3rd, 2020 at 23:48 (UTC) your personal access token (tautulli) using python-requests/2.18.4 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/31169720/commits/master

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

Is this something I should ignore a long updates coming out or?

**Comment by Arcanemagus** [comment]
This is already fixed in [v2.1.43](https://github.com/Tautulli/Tautulli/releases/tag/v2.1.43), update your Tautulli instance.

**Comment by wazerstar** [comment]
> 
> 
> This is already fixed in [v2.1.43](https://github.com/Tautulli/Tautulli/releases/tag/v2.1.43), update your Tautulli instance.

Thanks, not sure why mine has not updated yet, it usually does that automatic whenever there's a new version out.

**Comment by Arcanemagus** [comment]
Default update check interval is every 6 hours, the release is only 2 hours old 😉.

**Comment by wazerstar** [comment]
> 
> 
> Default update check interval is every 6 hours, the release is only 2 hours old 😉.

That makes sense, thanks again :)
