### ISSUE TITLE
Telegram Notifications missing metadata details

### ISSUE THREAD

**Issue by 1activegeek** [Tautulli/Tautulli-Issues#22]
**Version:**
2.0.22
**Branch:**
Master
**Commit hash:**
a08bce2073b1847762a22a843b13acc5f996d9cb
**Operating system:**

Linux 4.14.16-unRAID
**Python version:**
2.7.14 (default, Feb 22 2018, 21:59:35) [GCC 6.3.0]
**What you did?**
Created notifications for Telegram to send upon newly added content to the library. Body Text:
```
<movie>{title} ({year}) - Runtime {duration} {imdb_url}</movie><show>{show_name} {thetvdb_url}</show><season>{show_name} - Season {season_num00} {thetvdb_url}</season><episode>{show_name} - S{season_num00}E{episode_num00} - {episode_name} {thetvdb_url}</episode>
```
**What happened?**
When notifications are received, they're missing certain details from the messages. I've seen TV Episode Name, Movie Release Year, and TVDB URL's all missing. 
**What you expected?**
Notifications with metadata intact. 

**How can we reproduce your issue?**

1. Create a new telegram notification agent
2. Set the newly added content option
3. Set the body to use the supplied format
4. Force media update or wait for media update
5. Telegram message received with missing metadata. 

**What are your (relevant) settings?**
Body Text:
```
<movie>{title} ({year}) - Runtime {duration} {imdb_url}</movie><show>{show_name} {thetvdb_url}</show><season>{show_name} - Season {season_num00} {thetvdb_url}</season><episode>{show_name} - S{season_num00}E{episode_num00} - {episode_name} {thetvdb_url}</episode>
```

**Logs:**
No error logs

**Screenshots:**
**Missing TV URL at the end:**
![screen shot 2018-03-14 at 8 58 24 am](https://user-images.githubusercontent.com/6810720/37404772-334d2878-2769-11e8-9c1a-cee531fd5e09.png)
**Missing TV URL at the end:**
![screen shot 2018-03-14 at 8 58 33 am](https://user-images.githubusercontent.com/6810720/37404773-335b2356-2769-11e8-9b1f-ae2add8c3e17.png)
**Missing Movie Release Year:**
![screen shot 2018-03-14 at 8 58 48 am](https://user-images.githubusercontent.com/6810720/37404774-33682d76-2769-11e8-9e27-2d02fd4e8072.png)
**Missing Episode Name & TV URL:**
![screen shot 2018-03-14 at 8 59 03 am](https://user-images.githubusercontent.com/6810720/37404775-3376c598-2769-11e8-9a4b-db95a058f878.png)

**Comment by JonnyWong16** [comment]
Possibly your notification delay is too sort and the metadata has not been downloaded on the Plex server yet.

**Comment by 1activegeek** [comment]
Ok, I'll try adjusting this to 2 or 3 minutes delay. Assuming this is the reason for the missing name or year, what would cause the missing URL's? Those aren't being pulled from Plex are they? Otherwise I'm not understanding the "3rd Party APIs - Enable TheMovieDB lookups" option.

**Comment by JonnyWong16** [comment]
IMDB and TheTVDB are not options listed under "3rd Party API's". Those URLs just use whatever match you have on your Plex server.

**Comment by 1activegeek** [comment]
Ok, so an adjustment to this looks to have grabbed the right metadata at one point. I guess I need to drill into plex and see why it's taking so long to parse metadata. Thanks jonny!

**Comment by slamdunx** [comment]
Would be interested to hear if you have any success trying the code I posted yesterday:

Tautulli/Tautulli#1338

Feedback in the pull request comments section would be much appreciated please.

Thanks.
