### ISSUE TITLE
Error on Synced items

### ISSUE THREAD

**Issue by sibberio** [Tautulli/Tautulli-Issues#220]
**Describe the Bug**
I've some TV Shows converted and sync to my iPad Pro.
Since the last Plex update now some show that are converted and downloaded on iPad are showned as not downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/9988958/74455976-72fd2b80-4e86-11ea-847d-f05076a724d7.png)

**Relevant Settings**
Plex Version 1.18.6.2368

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.1.44
- Git Branch: nightly
- Git Commit Hash: c825176563a21245a035514b1d870aa814d77f63
- Platform and Version: docker container
- Python Version: 2.7.16

**Comment by JonnyWong16** [comment]
On the Synced Items page, *triple click* on the "Synced Items" header at the top. This will bring up the raw XML data for all your synced items directly from Plex. Look for the `itemsDownloadedCount` for that sync item. If it says `0` then the issue is with Plex and not with Tautulli.

**Comment by sibberio** [comment]
Thanks Jonny! I didn't know this "trick". So `itemsDownloadedCount` is zero. As usual your software is good... Plex a little bit less.
