### ISSUE TITLE
HTTP Root config var not behaving properly

### ISSUE THREAD

**Issue by below9k** [Tautulli/Tautulli-Issues#222]
**Describe the Bug**
I discovered this bug because after every restart Tautulli sets the `http_root` var back to the actual site root and causes redirect issues after startup. Tautulli (possibly in conjuction with nginx) redirect to `https://mytautulli.below9k.xxx/https://mytautulli.below9k.xxx/`
Tautulli (admin ui?) is not respecting the config.ini

**Steps to Reproduce**
1. Change "HTTP Root" in admin UI (from `https://mytautulli.below9k.xxx` to `/`)
2. Save + Restart
3. Navigate back to the the admin panel
4. Notice there was no change in the admin UI (still shows full url)
5. Notice it is changed in the config.ini file (only shows `http_root = /`)

**Expected Behavior**
Don't try to be smart and fill in some valid url or whatever it's trying to do...

**Relevant Settings**
- Tried with `http_proxy = 1` and `0`

**Tautulli and System Info (see Tautulli settings page)**
Git Branch: master
Git Commit Hash: c825176563a21245a035514b1d870aa814d77f63
Configuration File: /opt/Tautulli/config.ini
Database File: /opt/Tautulli/tautulli.db \| Status
Log File: /opt/Tautulli/logs/tautulli.log
Backup Directory: /opt/Tautulli/backups
Cache Directory: /opt/Tautulli/cache
Newsletter Directory: /opt/Tautulli/newsletters
Arguments: ['--config', '/opt/Tautulli/config.ini', '--datadir', '/opt/Tautulli', '--quiet', '--daemon', '--nolaunch']
Platform: Linux 4.4.0-173-generic (#203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 - Ubuntu 16.04 xenial)
System Timezone: America/Chicago (UTC-0600)
Python Version: 2.7.12 (default, Oct 8 2019, 14:14:10) [GCC 5.4.0 20160609]

**Link to logs (required)**
https://gist.github.com/below9k/ce8d8768877b0bf107f457005bdc5618 - nothing relevant here from what I can see

My only solution here is to `sed` the file and replace the value during service startup or stop the server, edit the value, and start... is my configuration so broken I have to do this?

**Comment by JonnyWong16** [comment]
Your logs got cut off. The last restart shown in your logs is from February 26th.

```
2020-02-26 12:46:26 - INFO    :: MainThread : Tautulli is restarting...
2020-02-26 12:46:26 - INFO    :: MainThread : Restarting Tautulli with ['/usr/bin/python', '/opt/Tautulli/Tautulli.py', '--config', '/opt/Tautulli/config.ini', '--datadir', '/opt/Tautulli', '--quiet', '--daemon', '--nolaunch']
2020-02-26 12:46:27 - INFO    :: MainThread : Starting Tautulli v2.1.44
```

**Comment by below9k** [comment]
github didn't like 10k lines on a gist lol. I trimmed it down to sometime yesterday

**Comment by Arcanemagus** [comment]
It works just fine on the first upload, if you ever edit the file in the web interface (like you did) though it gets truncated. [Direct link to full logs](https://gist.githubusercontent.com/below9k/ce8d8768877b0bf107f457005bdc5618/raw/92cff7aec53403ae928aa26d650de39865f35752/gistfile1.txt).

**Comment by JonnyWong16** [comment]
You should never enter a URL in the HTTP root setting. It's a root, not a URL.

Completely shut down Tautulli, check your process to make sure it's not running (`ps aux | grep Tautulli`), open the `config.ini` file and completely delete the `http_root` line, then Tautulli back up again. Go to Tautulli directly via the IP address and not through your reverse proxy. Is the HTTP root setting blank now?

**Comment by below9k** [comment]
I think my browser is auto populating in inputs :(
The url only shows up in the input when I use chrome and my user + extensions...
