### ISSUE TITLE
'Synced Items' not showing as downloaded

### ISSUE THREAD

**Issue by phreaq** [Tautulli/Tautulli-Issues#223]
I have several items synced to a few different devices, and Tautulli's 'Synced Items' lists them all, but says none are downloaded/0% complete, even though they are downloaded.

I'm using V2.1.44 of Tautulli, Plex Media Server is at Version 1.18.8.2468.

Anyone else with the issue?

**Comment by JonnyWong16** [comment]
Duplicate #220.
