### ISSUE TITLE
Issue with Users page - possibly due to user with pending invite.

### ISSUE THREAD

**Issue by rosenqui** [Tautulli/Tautulli-Issues#225]
The _Users_ page no longer loads any data. It gets stuck with "Fetching rows..." showing at the bottom of the page. In the logs it shows `WebUI :: /users : Uncaught ReferenceError: page is not defined. (users.js:65)`

I haven't had any trouble in the past with the Users page, but I just added a new user and they haven't confirmed their invite, so it's possible that the issue is due to the one "invite pending" user.

This is from v2.2.0 running on an ASUSTOR NAS.

**TAUTULLI CONFIGURATION**

Git Branch: | master
-- | --
Git Commit Hash: | None
Configuration File: | /config/config.ini
Database File: | /config/tautulli.db \| Status
Log File: | /config/logs/tautulli.log
Backup Directory: | /config/backups
Cache Directory: | /config/cache
Newsletter Directory: | /config/newsletters
Arguments: | ['--datadir', '/config']
Platform: | [Docker] Linux 4.14.x (#1 SMP Fri Mar 6 00:38:15 CST 2020)
System Timezone: | local (UTC-0400)
Python Version: | 2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]

**Comment by Arcanemagus** [comment]
Clear your browser cache, this isn't a Tautulli issue.

**Comment by rosenqui** [comment]
Thanks; that did it, I should have tried that first. I cleared all of the cookies and site data, but didn't wipe out the browser cache.
