### ISSUE TITLE
hide_episode_spoilers.py does not remove artwork after episode watched

### ISSUE THREAD

**Issue by ditmarvisser** [Tautulli/Tautulli-Issues#227]
**Describe the Bug**
Using the [hide_episode_spoilers.py script](https://gist.github.com/JonnyWong16/ea8f51f674fdb4ebf4e47e53cd1a10e5) to have blurred episode thumbnails, does not remove the blurred thumbnail after the episode is watched. The notification does get triggered, but the file does not get deleted.

**Steps to Reproduce**
1. Follow the instructions in the gist to enable the script, and add new episodes so the thumbnails get blurred.
2. Watch the episode until the specified watch percentage.
3. The script gets triggered according to the log, but the file remains on the disk.

**Expected Behavior**
The file gets deleted and the thumbnail gets restored to the original non-blurred version.

**Relevant Settings**
- The blurred settings in the gist, copy-pasted.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.2.0
- Git Branch: master
- Git Commit Hash: 76893100fc30370dbde2f7d8e1c5fbe300baf92d
- Platform and Version: Win 10
- Python Version: 2.7.17
- Browser and Version: Chrome 80

**Link to logs (required)**
https://gist.github.com/ditmarvisser/241ee2146a780cb7746688addb77634a
Relevant logs @ 2020-03-19 19:27:39, 2020-03-19 16:21:36, 2020-03-18 23:45:34.

**Comment by JonnyWong16** [comment]
GitHub issues for bug reports in the core Tautulli app. Scripts are not part of the core Tautulli app because those are things that you add yourself.

If you want support for scripts, please use the `#scripts` channel in our [Discord server](https://tautulli.com/discord).
