### ISSUE TITLE
Notification - Not recognising play start

### ISSUE THREAD

**Issue by garybooker** [Tautulli/Tautulli-Issues#23]
**Version:**

Git Branch: | master
-- | --
Git Commit Hash: | a08bce2073b1847762a22a843b13acc5f996d9cb
Configuration File: | /share/CACHEDEV1_DATA/.qpkg/PlexPy/CONFIG/plexpy.conf
Database File: | /share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/tautulli.db
Log File: | /share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/logs/tautulli.log
Backup Directory: | /share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/backups
Cache Directory: | /share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR/cache
GeoLite2 Database: | Click here to install the GeoLite2 database.
Arguments: | ['--daemon', '--port=8659', '--datadir=/share/CACHEDEV1_DATA/.qpkg/PlexPy/DATADIR', '--config=/share/CACHEDEV1_DATA/.qpkg/PlexPy/CONFIG/plexpy.conf', '--nolaunch']
Platform: | Linux 4.2.8
Python Version: | 2.7.12 (default, Aug 21 2016, 01:11:52) [GCC 5.2.0]

**What you did?**
Updated from PlexPy
**What happened?**
All worked OK but not receiving email notification for playback start. Other notifications work OK (Watched & recently addedO
**What you expected?**

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/garybooker/d2a5d15097df0c893b2aa1f883f7e24c

**Comment by JonnyWong16** [comment]
Please post your logs properly.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q14

**Comment by garybooker** [comment]
OK. Sorry for that. Hopefully logs OK now. I have a condition that excludes my music Library in the email notification.

**Comment by JonnyWong16** [comment]
Fixed on v2.0.24.
