### ISSUE TITLE
404: /images/platforms/xbmc.svg

### ISSUE THREAD

**Issue by glensc** [Tautulli/Tautulli-Issues#231]
Noticed such 404 from chrome console when setting up tautulli behind reverse proxy.

VERSION V2.2.1, installed from https://hub.docker.com/r/linuxserver/tautulli

**Comment by glensc** [comment]
probably should be kodi.svg

**Comment by glensc** [comment]
@JonnyWong16 why closed without reason? what's the fix?

**Comment by JonnyWong16** [comment]
[Tautulli v2.2.3 Changelogs](https://github.com/Tautulli/Tautulli/releases/tag/v2.2.3)

* UI:
  * Fix: XBMC platform icon not being redirected to the Kodi platform icon.
