### ISSUE TITLE
Web app manifest URLs invalid

### ISSUE THREAD

**Issue by ospring** [Tautulli/Tautulli-Issues#232]
**Describe the Bug**
When loading tuatulli, there are warnings when trying to load ressources from web app manifest

**Steps to Reproduce**
1. Go to tautulli home page
2. load dev tools with F12
3. in application section, there are warnings due to ${http_root} token miss interpreted

**Expected Behavior**
No warnings, favicon ressources correctly loaded
**Screenshots**
![image](https://user-images.githubusercontent.com/34972355/79039574-5a896300-7be2-11ea-84e2-0cee75f0e2a9.png)

**Relevant Settings**
- Enable HTTP Proxy : active
- Enable HTTPs : inactive
- http Host : 0.0.0.0
- http port : 8181

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.1
- Git Branch: master
- Git Commit Hash: 16ffbd9940d1566e9b2d69cd1e9990f89dbaa867
- Platform and Version: Windows 10
- Python Version: v2.7.15:ca079a3ea3
- Browser and Version: Edge Chromium  80.0.361.111

**Comment by ospring** [comment]
Hi. Thanks for the fix. However, Plexpy URL is not at the root of my external domain access : I use the Tautulli "HTTP Root" and "Public Tautulli Domain" parameters... So "/" as start URL is wrong for me and the installed webapp on my desktop send me to the wrong place.

May I suggest `"../../home"` as start URL ?

**Comment by JonnyWong16** [comment]
Tautulli automatically redirects `/` to `/http_root`.

**Comment by ospring** [comment]
I have a reverse proxy (Apache) in front of tautulli and only the virtual dir is "reverse-proxyfied" to Tautulli web server. so "/" leads to my domain home page and so the installed webapp goes to my home page...

I have tested the patch with MS Edge and with "../../home" and it is working in my case

Is my setup wrong ?

**Comment by JonnyWong16** [comment]
Oh, I tested it with my local IP address not my own reverse proxy. I see what you mean now.
