### ISSUE TITLE
Tautulli Remote Android App Device Registration Does not work

### ISSUE THREAD

**Issue by h3lo** [Tautulli/Tautulli-Issues#234]
**Describe the Bug**
The new "Register a new device" workflow is broken. Clicking it shows a QR code and API key. Entering the key or scanning the code with the app works, and the app works. But in the settings UI nothing happens, and there is only a "Cancel" button. Once clicking away from the new device modal in any way, the API key becomes invalid and the app can't connect anymore.

**Steps to Reproduce**
1. Go to 'Settings' -> 'Tautulli Remote Android App'
2. Click on 'Register a new device'
3. Scan the QR Code into the App or manually copy the API Key
4. Click anywhere on the screen in the web UI so the modal closes (or click cancel)

**Expected Behavior**
A save or OK button to save the new device.

**Screenshots**
N/A

**Relevant Settings**
- Not sure what you need here, let me know and I will add.

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.1
- Git Branch: master
- Git Commit Hash: 16ffbd9940d1566e9b2d69cd1e9990f89dbaa867
- Platform and Version: Ubuntu (will be updating to 20.04 upon release)
- Python Version: 2.7.6
- Browser and Version: FireFox 75.0

**Link to logs (required)**
https://gist.github.com/h3lo/c69952962d6cc599f7d45b2b25573299

**Possible Workaround**
Look at my 'Steps to Reproduce' section above. Instead of clicking away or clicking cancel which closes the modal, if I simply close the browser tab after step 3, and open a new one, it seems the API key stays valid, however the device is not registered, and there doesn't appear to be a way to revoke it, so this in itself is a bug...

**Comment by Arcanemagus** [comment]
This is not the place for support requests, if your setup is working correctly the dialog will disappear on its own when the device finishes registration.

[App Fails to Register](https://github.com/Tautulli/Tautulli-Remote/wiki/App-Fails-to-Register)

If you need further help please use one of the [support options](https://tautulli.com/#support), with [Discord](https://tautulli.com/discord) being preferred.

**Comment by h3lo** [comment]
It's a bug that there's no way to make this work without exposing tautulli to the internet...... I'm both annoyed and disappointed that this is the response.

Also, read my possible workaround. It's definitely a bug that the API key can't be removed.
