### ISSUE TITLE
NullRefer Anonymizer Service Defunct

### ISSUE THREAD

**Issue by thickconfusion** [Tautulli/Tautulli-Issues#235]
**Describe the Bug**
In Tautulli's Web interface settings, there is an option to specify an anonymizer service. The default is https://nullrefer.com. It appears that this service is no longer online. I suggest specifying a different default, such as https://blankrefer.com. It has the same interface, such as https://blankrefer.com/?SITE.

**Steps to Reproduce**
1. Go to 'Settings'
2. Click on 'Web Interface'
3. Scroll down to 'Anonymous Redirect'
4. Default is "https://www.nullrefer.com/?", which appears to be down according to isitdownrightnow.com and down.com.

**Expected Behavior**
The default anonymizer service should be one that is available.

**Screenshots**
N/A

**Relevant Settings**
See above

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.0
- Git Branch: master
- Git Commit Hash: 76893100fc30370dbde2f7d8e1c5fbe300baf92d
- Platform and Version: Win 10
- Python Version: 2.7.17
- Browser and Version: Chrome 81

**Link to logs (required)**
N/A

**Comment by Arcanemagus** [comment]
It looks like this has only been down for 4 days, do you have any evidence that it is _permanently_ down and not a temporary outage? The setting is there to change it to whatever you want in the meantime.

**Comment by JonnyWong16** [comment]
`blankrefer.com` is on PiHole's default blocklist. It also tries to load `http://www.statcounter.com/counter/counter.js` when redirecting so that's not an option.

**Comment by thickconfusion** [comment]
NullRefer appears to have been restored.
