### ISSUE TITLE
Tautulli not updating with older versions of git

### ISSUE THREAD

**Issue by nmcmahon1215** [Tautulli/Tautulli-Issues#236]
**Describe the Bug**
A new option was added to the git update which is not supported on older versions of git, specifically git packaged with CentOS7

Git throws an error that the option `--ff-only` is not recognized

**Steps to Reproduce**
1. Go to Settings
2. Click check for updates
3. Click update
4. Tautulli restarts the same version silently

**Expected Behavior**
Tautulli should update. 

**Relevant Settings**
- CentOS 7
- git version 1.8.3.1

**Tautulli and System Info (see Tautulli settings page)**
- Version:  v2.2.0
- Upgrading to version: v2.2.1
- Git Branch: master
- Platform and Version: CentOS 7
- Python Version: Python 2.7.5

**Link to logs (required)**
https://gist.github.com/nmcmahon1215/d4259aa81001533c00ce931f08fa0910

**Comment by samwiseg0** [comment]
This has already been fixed and is in the beta branch. https://github.com/Tautulli/Tautulli/commit/e4ec24be261c690015b9d70bcc88a89b8c3b2ea5

**Comment by JonnyWong16** [comment]
Duplicate #228.
