### ISSUE TITLE
Renaming history record id to row_id is a breaking change

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli-Issues#239]
**Describe the Bug**
Renaming history record id to row_id in commit c979e78 is a breaking change. I would suggest to keep "id" in the api for legacy support.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.2.2-beta
- Git Branch: beta
- Git Commit Hash: 6d5c3207011e221b8b6aa915c333f08d375c800b

**Comment by JonnyWong16** [comment]
Can you explain why you need `id`?

**Comment by tfonfara** [comment]
Out there there are plenty of users that are using the Tautulli api. With the introduced breaking change they are all unable to access history records once they update to the new version of Tautulli (as soon as it's out of beta), if they use `get_stream_data` together with `row_id` parameter (that is in stable version filled with `id`, in beta version with `row_id`).

**Comment by JonnyWong16** [comment]
Is that the only place where `id` is used?

I will add support for both `id` and `row_id` in the next release, but you should update your app to use `row_id` in the future.

**Comment by tfonfara** [comment]
As far as I know it is 🤔 
Cool, thanks! I will definitely, was just thinking about existing installs.
