### ISSUE TITLE
Direct Play incorrectly identified (IOS?) and another possibly related error

### ISSUE THREAD

**Issue by JamminR** [Tautulli/Tautulli-Issues#24]
**Version:**
v2.0.22
**Branch:**
Master
**Commit hash:**
a08bce2073b1847762a22a843b13acc5f996d9cb
**Operating system:**

 Windows 10
**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
**What you did?**
Examined History tab
**What happened?**
Noticed shared user used IOS to play content. It was listed as "Direct Played"
![image](https://user-images.githubusercontent.com/3392170/37440323-9fc7f866-27d2-11e8-90db-5595e357b69a.png)

Examined source details, it shows transcodes for several of the parts.
![image](https://user-images.githubusercontent.com/3392170/37440361-b7a8080e-27d2-11e8-8af3-d5ac6277a346.png)

Viewing the logs during this time also indicate hundreds if not thousands of entries stating:
WebUI :: /home : Object doesn't support property or method 'trunc'. (home:868)
**What you expected?**
I'd expect History column to indicate the transcoded tooltip and icon, and not so many errors in logs.

**How can we reproduce your issue?**

Unsure what exact device shared user was using, bit it's listed as IOS.

**What are your (relevant) settings?**
I keep a tab open to history most of the time in background. It was not selected, but browser was open at time.

**Link to logs:**
HUNDREDS of the /home object trunc errors appear during this session. Unsure if it related/cause.

'
2018-03-14 17:08:24 | ERROR | WebUI :: /home : Object doesn't support property or method 'trunc'. (home:868)
2018-03-14 17:08:23 | ERROR | WebUI :: /home : Object doesn't support property or method 'trunc'. (home:868)
2018-03-14 17:08:21 | DEBUG | Tautulli ActivityHandler :: Session 6 resumed.
2018-03-14 17:08:01 | DEBUG | Tautulli ActivityHandler :: Session 6 started by user X (X) with ratingKey (X- The X).
2018-03-14 16:12:47 | INFO | Tautulli Pmsconnect :: Requesting name from server...
'

**Comment by JonnyWong16** [comment]
Fix won't be retroactive.

Re: the `Object doesn't support property or method 'trunc'` error. Are you using Internet Explorer?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc#Browser_compatibility

**Comment by JamminR** [comment]
Firefox Qauntum 58.0.2, with Windows high contrast theme, which, in Windows 10 Fall Creators, is known to break some Windows menus. Maybe it's breaking Firefox.
This user is likely to watch more of this show, they actually made the request I obtain it. 
Before updating to beta channel to test the transcode check, I'll remote into the server without themes and use Firefox (same version) to see if it throws same error during show.
Any additional logs wanted from (where if so?) during stream if it still occurs?

**Comment by JamminR** [comment]
OK, think I found /home trunc issue.
I had an Internet Explorer 11 window open in the background due to some various odd testing I was doing with Tautulli recently.
Want a new issue created for it, now that I figured out it's not necessarily related to the incorrect stream decision? I know everyone hates IE11, but it's still out there, and not 100% EOL yet.

**Comment by JonnyWong16** [comment]
No, there are other thing in Tautulli that don't 100% support IE either. I'm not going to bother with it.

**Comment by JamminR** [comment]
I'm not planning on going to nightly to test this.
As I no longer run two instances (as I previously did with PlexPy and Tautulli), bit afraid to be on bleeding edge. Is there a general timeline of nightly->beta->release? I might be more willing to go to beta than I would nightly.
