### ISSUE TITLE
Tautulli doesn't play nice with custom certs on Plex

### ISSUE THREAD

**Issue by andrasg** [Tautulli/Tautulli-Issues#240]
**Describe the Bug**

When having Plex configured with a custom SSL cert and domain name, Tautulli still compares commonname to the *.plex.direct CN and fails websocket communication.

**Steps to Reproduce**
1. configure tautulli to talk to plex
2. setup plex to use a custom cert
3. setup plex to use a custom DNS name, matching the cert's common name
4. make sure tautulli can resolve the custom dns name and reach plex on this name
5. goto settings, select server with custom name, click on verify server
6. Error in log:

`Websocket connection test failed: hostname 'your.custom.dns' doesn't match '*.1234yourid.plex.direct'`

**Expected Behavior**
Tautulli web socket should respect the custom domain name and not verify against the *.plex.direct CN.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.2.1
- Git Branch: master
- Git Commit Hash: None
- Platform and Version: docker (linuxserver/tautulli)
- Python version: 2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]

**Relevant logs**

```
2020-04-27 17:45:32 | ERROR | Websocket connection test failed: hostname 'your.custom.dns' doesn't match '*.1234yourid.plex.direct'
2020-04-27 17:45:32 | DEBUG | Testing websocket connection...```

**Comment by JonnyWong16** [comment]
I use Tautulli with my own domain and certificate. I think you have a misconfiguration, but I can't tell because you haven't posted your complete logs.

**Comment by andrasg** [comment]
I have noticed an issue on Plex side, indeed. Now the certs are ok, seeing my custom (public) certs.

I am not entirely sure how I ended up here, but it seems Tautulli is trying to connect without ssl:

`Websocket connection test failed: [Errno 104] Connection reset by peer`

If I go into testing, click manual connection, enter the right servername and port, I get:

`Websocket connection test failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)`

Logs are here: https://gist.github.com/andrasg/1d7b19698282f432e23800a2c5797500

**Comment by JonnyWong16** [comment]
Have you checked the "Manual Connection" setting?

![image](https://user-images.githubusercontent.com/9099342/80396227-33c95e80-8869-11ea-85b8-9017f52f0baf.png)

**Comment by andrasg** [comment]
I was now able to verify connection using manually adding the `<local-ip>.<serverid>.plex.direct` hostname URL and forcing manual connection. After that I was able to add it by custom DNS name as well.
Closing the issue, thanks for the help.
