### ISSUE TITLE
Notification trigger upon termination of stream from player 

### ISSUE THREAD

**Issue by Patrick1610** [Tautulli/Tautulli-Issues#243]
I have noticed that after an episode on Plex has reached the 'watched percentage' and I stop the stream, there is not triggered an pause or stop trigger (I have an Apple TV 4K). I understand from an earlier conversation that this is a limitation of the player, not the server or tautulli itself.

Even though, I was wondering the following. Since the stream is terminated, and no longer visible in Tautulli as activity, is it possible to create an extra Notification Trigger that does not trigger upon regular pause/stop triggers, but does trigger when a stream is terminated? 

Hope something is possible to enhance this functionality. 

Regards, Patrick

**Comment by samwiseg0** [comment]
This is not the place for support requests.

If you need further help please use one of the [support options](https://tautulli.com/#support), with [Discord](https://tautulli.com/discord) being preferred.
