### ISSUE TITLE
Uncaught TypeError: Failed to construct 'Notification': Illegal constructor.

### ISSUE THREAD

**Issue by MateEke** [Tautulli/Tautulli-Issues#245]
**Describe the Bug**
Android Chrome browser notifications doesn't work.
```
ERROR: 

WebUI :: /settings#tab_tabs-notification_agents : Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead.. (pnotify.custom.min.js:40)
```

**Steps to Reproduce**
Create a browser notification agent and under "Test Notifications" tab press "Test Browser" button on Android.

**Expected Behavior**
Working HTML5 notifications for Android.

**Relevant Settings**
- Default Browser notification agent is sufficient for testing

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.2.4
- Git Branch: master
- Git Commit Hash:  7f178e091349a1399395c1ac3227d6f0fa801efc
- Platform and Version: Ubuntu 18.04 Docker
- Python Version: 2.7.17
- Browser and Version: Android Chrome 83.0.4103.60

**Link to logs (required)**
[LOG](https://gist.github.com/MateEke/062bd6ff41f6b363c63c2cfd36148ae3).

**Comment by JonnyWong16** [comment]
Browser notifications were never meant to be push notifications on mobile. Sorry, but I don't think this will be fixed. There are many other better options for mobile push notifications.
