### ISSUE TITLE
Add support for S3 Image Hosting

### ISSUE THREAD

**Issue by craftbyte** [Tautulli/Tautulli-Issues#246]
AWS S3 is a widely used file hosting service. It is supported by most screenshot apps and file uploaders. Since Tautulli already supports imgur, I see adding S3 support the next step in supporting more options for image uploads.

**Comment by samwiseg0** [comment]
This is not the place for feature requests. Please use [FeatHub](https://feathub.com/Tautulli/Tautulli).
