### ISSUE TITLE
Mac OS Build 2.5.0 Beta 1: Uncaught Exception

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [Tautulli/Tautulli-Issues#248]
**Describe the Bug**
The packaged build of Tautulli for Mac OS fails to launch after relevant settings to utilise HTTPS are enabled and saved.

**Steps to Reproduce**
1. Settings ➡️ Web Interface tab
2. Tick the boxes to enable HTTPS proxy, HTTPS, and to create a self-signed certificate
3. Activate the Save button
4. Confirm restart by activation of the Restart button.

**Expected Behaviour**
Tautulli should relaunch.

**Relevant Settings**
Enabled HTTPS Proxy, HTTPS and create self-signed certificate

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.5.0 beta 01
- Platform and Version: Mac OS 10.15.5
- Python Version: 3.8.3
- Browser and Version: Safari Technology Preview 107

**Link to logs (required)**
https://gist.github.com/Rogue-Git-Dev/b62fe95ab0043bf6744629b5df3e2d0e

**Comment by JonnyWong16** [comment]
How did you create an issue without the template? Did you erase the template?

**Comment by Rogue-Git-Dev** [comment]
Yes, I erased the text in the field. In this case, it was easier for me simply to make known the issue more efficiently rather than navigate the text in the template and attempt to populate the relevant sections.

**Comment by JonnyWong16** [comment]
Please do not do that again. The template is there for a reason and provides us with important info. Please edit your issue and fill out the template.

**Comment by Rogue-Git-Dev** [comment]
I thought to leave it, but I was able to explain what is wrong and what is necessary to reproduce it. Is there any other information you need? I copied that code directly from the entry in the log where it began; everything above that was normal.

**Comment by JonnyWong16** [comment]
Please edit your issue and fill out the template.

**Comment by Rogue-Git-Dev** [comment]
I do not have the template.

**Comment by JonnyWong16** [comment]
Copy and paste it from a new issue.
