### ISSUE TITLE
Attempting to restore migrated tautulli.db errors with no such column: is_admin

### ISSUE THREAD

**Issue by albino1** [Tautulli/Tautulli-Issues#25]
**Version:** V2.0.22

**Branch:** master

**Commit hash:** a08bce2073b1847762a22a843b13acc5f996d9cb

**Operating system:** Synology DSM 6.1.5-15254 Update 1 (Linux 3.10.102)

**Python version:** 	2.7.14 (default, Mar 14 2018, 20:37:29) [GCC 4.7.3 20130102 (prerelease)]

**What you did?** 

The SynoCommunity PlexPy package was finally able to update now that Tautulli is out of Beta, so I ran the update, and it seemed to work, but I was unable to get the package to actually start.  So I backed up my post-migration `tautulli.db` and did a fresh install.  After running the wizard and verifying it was able to connect to Plex server and display a currently playing item I tried restoring the previously migrated `tautulli.db`.  

**What happened?**

Tautulli showed the previous PlexPy data, but was unable to connect to the Plex server.  I tried re-verifying the server and it was successful.  I also tried fetching a new token and that also appeared to work.  However, when I would go back to the home page it would say I wasn't connected.  Once in the logs I found several errors saying:

`Database error: no such column: is_admin`

**What you expected?**

I expected the migrated `tautulli.db` file to work, but it appears it didn't migrate correctly.

**What are your (relevant) settings?**

My PlexPy install was very basic, I changed almost no settings and only had a few notifications setup.

**Link to logs:**

Here's the most recent logs from when I tried the "migrated" database:

[tautulli.zip](https://github.com/Tautulli/Tautulli-Issues/files/1813921/tautulli.zip)

I guess my only real question here is if there's anything I can do to successfully use either the `tautulli.db` from after the PlexPy -> Tautulli auto-update, or perhaps restore from an older PlexPy db backup like this one:

`plexpy.backup-20180310175530.sched.db`

Any help would be appreciated.  Thanks!

**Comment by JonnyWong16** [comment]
Your `tautulli.db` did not migrate properly. Restore one of the `plexpy.db` backups as `tautulli.db`.

**Comment by albino1** [comment]
That seems to have worked, thanks!
