### ISSUE TITLE
Newsletters on IOS are unreadable if dark mode is enabled

### ISSUE THREAD

**Issue by simonk83** [Tautulli/Tautulli-Issues#252]
**Describe the Bug**
With dark mode enabled on IOS, most of the episode/movie summaries are unreadable (see image)

**Steps to Reproduce**
1. Enabled dark mode
2. View newsletter email

**Expected Behavior**
Text backgrounds should be changed to white if dark mode is enabled

**Screenshots**
See next comment

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.4
- Git Branch: master
- Git Commit Hash: 7f178e091349a1399395c1ac3227d6f0fa801efc

**Comment by simonk83** [comment]
![9BD68B74-0102-4427-AD53-91ED6F66FB8A](https://user-images.githubusercontent.com/518440/85238126-21396300-b46f-11ea-80ad-903e283faf46.png)

**Comment by Arcanemagus** [comment]
You are more than welcome to fix this yourself if you so desire, if you do find a way to fix it without breaking other clients please open a PR to `nightly`
[Q: I want to customize the newsletter.](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-custom-template)

**Comment by simonk83** [comment]
Wait sorry, are issues not being accepted anymore?

**Comment by JonnyWong16** [comment]
Unfortunately this is not something that I will spend time supporting.

**Comment by simonk83** [comment]
Ok... 😄

**Comment by simonk83** [comment]
You mean Tautulli in general, or this specific problem? I was about to submit another issue with the newsletters but I guess I won’t?

**Comment by JonnyWong16** [comment]
I have no interesting in changing the default newsletter template to support other clients. You are free to customize the newsletter template yourself following the FAQ answer linked above.

**Comment by Arcanemagus** [comment]
There are a myriad of different mail clients out there. We don't have the time to learn the idiosyncrasies of each and every one to try to make the newsletter work in all of them. There are several that are plain broken in how they render the messages. If you want to fix that yourself then by all means go for it, and if fixing that doesn't break the clients we have tested on then we would welcome a PR to `nightly`, but it's not something that we will be working on.

This is exactly why the custom newsletter functionality is there.

**Comment by simonk83** [comment]
Ok fair enough. It’s just gmail though which is presumably the majority chunk of your user base. 

All good, your prerogative to work on what you want. I’ll see if I can work out a fix.

**Comment by samwiseg0** [comment]
Use the native mail client. It works perfectly with the default template. 

I would argue the native mail app is much more of the user base than the gmail app. 

Screenshots:
https://imgur.com/a/P07FRJR
