### ISSUE TITLE
Newsletters on mobile are squished and wrap around

### ISSUE THREAD

**Issue by simonk83** [Tautulli/Tautulli-Issues#253]
**Describe the Bug**
With dark mode enabled on IOS, most of the episode/movie summaries are unreadable (see image)

**Steps to Reproduce**
1. Enabled dark mode
2. View newsletter email

**Expected Behavior**
Text backgrounds should be changed to white if dark mode is enabled

**Screenshots**
![57875BF3-F65A-4308-A8CB-F6703ACDDA66](https://user-images.githubusercontent.com/518440/85238153-52b22e80-b46f-11ea-8138-a112326897e2.png)

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.4
- Git Branch: master
- Git Commit Hash: 7f178e091349a1399395c1ac3227d6f0fa801efc

**Comment by Arcanemagus** [comment]
See [my other comment](https://github.com/Tautulli/Tautulli-Issues/issues/252#issuecomment-647199371).

**Comment by JonnyWong16** [comment]
Same answer as #252.
