### ISSUE TITLE
Error Communicating with Server with Live TV

### ISSUE THREAD

**Issue by purevertigo** [Tautulli/Tautulli-Issues#254]
**Describe the Bug**
When launching a live TV session, randomly Tautulli will throw up "There was an error communicating with your Plex Server. Check the logs and verify your server connection in the settings."

**Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior**
Info window should be provided

**Screenshots**
NA

**Tautulli and System Info (see Tautulli settings page)**
VERSION V2.1.28
- Git Branch:  master]
- Git Commit Hash: [eg. 2635569e765e5817400ed1032a27bfc850242f6a]
Platform: | Windows 10 (10.0.18362)
-- | --
System Timezone: | Australia/Sydney (UTC+1000)
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

**Link to logs (required)**
<script src="https://gist.github.com/purevertigo/214c01d1757be9ad20bab42323f1754a.js"></script>

Close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
-->

**Comment by blacktwin** [comment]
This was addressed in [2.2.0 release](https://github.com/Tautulli/Tautulli/releases/tag/v2.2.0). Please update.

**Comment by purevertigo** [comment]
OK. I did check for updates though and was told there were none available from the app?

**Comment by blacktwin** [comment]
How did you install Tautulli? Which method did you [follow](https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#windows)?
