### ISSUE TITLE
Fontawesome icons not working in tautulli/tautulli:latest container.

### ISSUE THREAD

**Issue by BinaryJay** [Tautulli/Tautulli-Issues#256]
**Describe the Bug**
In some locations in Tautulli where fontawesome icons are used, they don't show up but instead show up as empty squares.

**Steps to Reproduce**
1. Go to a page that uses fontawesome, example /users.   The icon next to Edit is not showing correctly.
I've also noticed this on the now playing frame between the source and target transcodes.

**Expected Behavior**
The fontawesome icon should display.

**Screenshots**
https://imgur.com/H8sx6XP

**Tautulli and System Info (see Tautulli settings page)**
Running in the official docker container, latest tag.

**Comment by Arcanemagus** [comment]
This is working just fine here, the issue is on your end. If you need help figuring out what is wrong please use one of the [support options](https://tautulli.com/#support), with Discord being preferred.

**Comment by BinaryJay** [comment]
Figured it out.  For those who find this issue in the future:

It was the Rakuten Chrome extension breaking this.  Sorry, I should have tried an alternative browser before reporting.
