### ISSUE TITLE
No support for proxy-based servers

### ISSUE THREAD

**Issue by Fmstrat** [Tautulli/Tautulli-Issues#263]
**Describe the Bug**
While at first I thought this issue was related to hostname lookup, it's actually an issue with proxy based networks (Plex behind reverse proxy). Since the "Plex Server URL" is automatically retrieved, there is no way to force it to an external defined host lookup for proxying, such as "myhost.mydomain.com:port". Plex always responds with whatever is configured as the non-custom return point (their plex.com domain).

I'm not really sure how to provide a detailed assessment, but the way to fix it would be to allow a user to override the Plex Server URL detection, and force in a URL of their own.

**Steps to Reproduce**
0. Set up Plex with a custom remote URL and an nginx reverse proxy
1. Go to Settings > Plex media server
2. Try to add a server that is behind the proxy
3. Watch as it grabs the "plex.com" server URL
4. Scratch chin wondering how to force a different URL

**Expected Behavior**
Allow users to override the URL detection

**Screenshots**
n/a

**Relevant Settings**
n/a

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.2.4
- Platform and Version: Docker

**Link to logs (required)**
n/a

**Comment by Fmstrat** [comment]
Hrm, apologies. I notice right after posting this it may be due to compose choosing a different bridge network. Please hold on digging in and I will investigate further and close this if that is correct. Thanks!

**Comment by Arcanemagus** [comment]
Use the advanced setting:
![image](https://user-images.githubusercontent.com/427137/87489761-ab04c800-c5f8-11ea-82c7-c24dc498021e.png)

This isn't the place for support requests, if you have further issues please use one of the [support options](https://tautulli.com/#support), with Discord being preferred.
