### ISSUE TITLE
User removed, then added again, not showing

### ISSUE THREAD

**Issue by Beholden** [Tautulli/Tautulli-Issues#266]
**Describe the Bug**
had user in plex, removed, purged from Tautulli, user added back to plex, will not show again in Tautulli.

**Steps to Reproduce**
1. Go to '...' Listed above
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior**
When on the users page and clicking refresh users, the user should show up again.

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
Git Branch: | master
Git Commit Hash: | 1698622d63f406d50da4429e2b5d1b5d55893358
Configuration File: | C:\Tautulli\config.ini
Database File: | C:\Tautulli\tautulli.db \| Status
Log File: | C:\Tautulli\logs\tautulli.log
Backup Directory: | C:\Tautulli\backups
Cache Directory: | C:\Tautulli\cache
Newsletter Directory: | C:\Tautulli\newsletters
Arguments: | ['--nolaunch']
Platform: | Windows 10 (10.0.19041)
System Timezone: | America/Chicago (UTC-0500)
Python Version: | 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]

**Link to logs (required)**
https://www.dropbox.com/s/vfmigqbqhjwhc9q/logs.zip?dl=0

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q12
