### ISSUE TITLE
Details are missing from log entries after update from PlexPy to Tautulli

### ISSUE THREAD

**Issue by kobuki** [Tautulli/Tautulli-Issues#27]
**Version:**
v2.0.22
**Branch:**
master
**Commit hash:**
a08bce2073b1847762a22a843b13acc5f996d9cb
**Operating system:**
Debian 9.3
Linux 4.13.0-0.bpo.1-amd64
**Python version:**
2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
**What you did?**
Updated to Tautulli v2.0.22 from latest PlexPy (sorry, can't recall the exact version information) and looked at the stream details in history.
**What happened?**
The details are missing for anything but the original stream (see screenshot). New replays after the update show all information correctly.
**What you expected?**
All information are displayed in history for streams both for old and new replays.
**How can we reproduce your issue?**
See descriptions above.
**What are your (relevant) settings?**
N/A
**Link to logs:**
N/A

Erroneous log entry (logged before update):
![Screenshot 1](https://user-images.githubusercontent.com/6766047/37560367-d262ffc6-2a36-11e8-887b-41b1c4f789f1.png)

Good log entry (logged after update):
![log2](https://user-images.githubusercontent.com/6766047/37560403-8855fb12-2a37-11e8-8bd5-a48e4948e8c8.png)

**Comment by Arcanemagus** [comment]
PlexPy didn't record that information, so it's simply not there to show for older history records.

**Comment by kobuki** [comment]
Please re-open this. It displayed a lot more information, like the fact of transcoding which is also entirely missing. I'm going to restore the previous version from backups and provide a screenshot.

**Comment by kobuki** [comment]
Attaching image of old log entry where all information is available:

![oldlog1](https://user-images.githubusercontent.com/6766047/37560586-84bbafd4-2a3b-11e8-8997-7fe64913deee.png)

Version is: PlexPy 1.4.25 master/cfd30996264b7e9fe4ef87f02d1cc52d1ae8bfca

I'm keeping the old PlexPy until this is resolved - I would like to keep and be able to view all the info gathered in my logs during Plex use...

**Comment by kobuki** [comment]
Well, looking into it a little bit more, it seems that the tables are populated with old data properly, but there are a lot ow new columns with empty fields. Many fields look like copies of the old data, like:

width -> video_width
transcode_container -> stream_container_decision
etc.

It appears old data entries are not migrated properly or at all. Should be an easy fix.
