### ISSUE TITLE
Database error: no such column: is_active after updating to v2.5.4

### ISSUE THREAD

**Issue by desigi** [Tautulli/Tautulli-Issues#270]
**Describe the Bug**
After upgrading to v2.5.4, when starting Tautulli (in docker), the container will not respond when accessing it from a browser. The page remains blank.

See the logs below. I found the following database error from the logs:
`Database error: no such column: is_active`
Traceback:
```
File "/app/tautulli/Tautulli.py", line 310, in <module>
    main()
  File "/app/tautulli/Tautulli.py", line 220, in main
    plexpy.initialize(config_file)
  File "/app/tautulli/plexpy/__init__.py", line 341, in initialize
    users.refresh_users()
  File "/app/tautulli/plexpy/users.py", line 80, in refresh_users
    monitor_db.upsert('users', key_dict=keys_dict, value_dict=item)
  File "/app/tautulli/plexpy/database.py", line 423, in upsert
    self.action(update_query, list(value_dict.values()) + list(key_dict.values()))
  File "/app/tautulli/plexpy/database.py", line 375, in action
    sql_result = c.execute(query, args)
sqlite3.OperationalError: no such column: is_active
```

**Steps to Reproduce**
1. Upgrade Tautulli to the most recent version (v2.5.4)
2. Start the Tautulli docker container
3. Access Tautulli from a browser with the configured port.
4. Receive message that a connection could not be established.

**Expected Behavior**
The Tautulli dashboard should appear.

**Screenshots**
N/A

**Relevant Settings**
I cannot access the settings since Tautulli never really loads.

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.5.4
- Git Branch: master
- Git Commit Hash: 21dec5feb3e8ae5395453f96af948f710b1a5381
- Platform and Version: Ubuntu 18.04 Docker version 19.03.2, build 6a30dfc
- Python Version: 2.7.17
- Browser and Version: Firefox 79.0

**Link to logs (required)**
[tautulli.log](https://gist.github.com/desigi/f0124082d10c4ad2021973294d04b649)

**Comment by samwiseg0** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18
