### ISSUE TITLE
Windows .exe install, module pyOpenSSL missing

### ISSUE THREAD

**Issue by Spanjoekel** [Tautulli/Tautulli-Issues#278]
**Describe the Bug**

After upgrading to the latest version, i cannot run the web interface on SSL. VERSION V2.5.5 

**Steps to Reproduce**
2. Click on '...'
3. Scroll down to '...'

VERSION V2.4.* was working perfectly.

**Expected Behavior**

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.1.29]
VERSION V2.5.5 
- Git Branch: [eg. master]
Master
- Git Commit Hash: [eg. 2635569e765e5817400ed1032a27bfc850242f6a]
184ae4608367bf601077690a7f9d059c720b452
- Platform and Version: [eg. Windows 10]
Windows Server 2019 1809 built 17763.1282
- Python Version: [e.g. 2.7.16]
Python Version: | 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
Built-in
- Browser and Version: [e.g. Chrome 74]
Edge version 85.0.564.51 (Official build) (64-bit)
**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/5223389/tautulli.log)

**Comment by JonnyWong16** [comment]
https://www.reddit.com/r/Tautulli/comments/io7h87/255_broke_https_with_custom_not_self_signed_ssl/

Already been fixed in https://github.com/Tautulli/Tautulli/commit/68946ceede8f50824fa69e60a37d303243edd975

**Comment by Spanjoekel** [comment]
Fixed it, uninstall and reinstalled fixed it! Thanks
