### ISSUE TITLE
Cannot import tautulli.db

### ISSUE THREAD

**Issue by FGOD1983** [Tautulli/Tautulli-Issues#279]
**Describe the Bug**
I did a re-install of my server due some issues and in the meantime upgraded from ubuntu 16.04 to 20.04. I re-installed Tautulli and everything works like intended, but I can't seem to import my old tautulli.db that is in a backup of my old `/opt/Tautulli` setup folder. It states the database is invalid (Invalid database specified).

**Steps to Reproduce**
1. Go to 'settings->Import & Backups'
2. Click on 'Database Import Tautulli'
3. Select the old tautulli.db file from the old os backup or even the planned backup db files under the backup folder

**Expected Behavior**
It should import my old database/history of what has been watched

**Screenshots**
[screenshot](https://paste.pics/d18794110efc335dc12c4465daa01809)

**Relevant Settings**
nothing setup yet. pure default options.
Could find this in the logs: `Tautulli Database :: Invalid database specified: attempt to write a readonly database`

**Tautulli and System Info (see Tautulli settings page)**
- Version: v2.5.5
- Git Branch: master
- Platform and Version: Ubuntu 20.04
- Python Version: 3.8
- Browser and Version: Chrome v84.0.4147.125 

**Link to logs (required)**
[logs](https://gist.github.com/FGOD1983/00e2302543a35bbee183a0aeaf3268ac).

**Comment by JonnyWong16** [comment]
Tautulli doesn't have the correct Linux permissions to access the database.

**Comment by FGOD1983** [comment]
ah my bad, I totally missed the fact that the backup was done with sudo and thus being owned by root instead of tautulli. Thx for this!
