### ISSUE TITLE
Windows installer is unsigned

### ISSUE THREAD

**Issue by napei** [Tautulli/Tautulli-Issues#282]
**Describe the Bug**
The windows installer is unsigned, causing SmartScreen to show and possibly causing confusion for the user.

**Steps to Reproduce**
1. Download fresh installer
2. Run installer

**Expected Behavior**
No SmartScreen

**Screenshots**
![image](https://user-images.githubusercontent.com/8946502/95028133-ceb44780-06e9-11eb-885f-c5304f671de5.png)

**Relevant Settings**
- Other settings
  - Windows 10 Pro 2004

**Tautulli and System Info (see Tautulli settings page)**
- Version: latest (2.5.6)
- Platform and Version: Windows 10

**Link to logs (required)**
N/A

**Comment by JonnyWong16** [comment]
This is not something that I'm not going to fix. I am not going to pay hundreds of dollars per year for a code signing certificate.
