### ISSUE TITLE
Tautulli upgrade to 2.5.6 will break Newsletters

### ISSUE THREAD

**Issue by ThierryBegin** [Tautulli/Tautulli-Issues#283]
**Describe the Bug**
all newsletter are showing in dashboard but when you click on them you will have errors, not displaying them

**Steps to Reproduce**
1. create a newsletter in 2.5.5
2. upgrade tautulli to 2.5.6
3. select news letter

**Expected Behavior**
newsletter format should be upgraded 

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.5.6]
- on Freebsd

**Comment by JonnyWong16** [comment]
Closing stale issue.
