### ISSUE TITLE
Discord Webhook Always Plays Media Poster at Start

### ISSUE THREAD

**Issue by rlongio** [Tautulli/Tautulli-Issues#284]
**Describe the Bug**
In Discord notifications, for all notifications using webhooks, regardless of the combination of flags checked (ie Metadata, Summary, Link) and (On Watched, On Start) send a media poster at the start of any media.

**Steps to Reproduce**
1. Create a Discord Notification from settings
2. On Configuration Tab: Add Discord Webhook URL
3. On Triggers Tab: Add any combination of playback triggers.
4. See attached screenshot of error.  

**Expected Behavior**
One complete notification per trigger.

**Screenshots**
![2020-10-27 20_25_23-#movies - Discord](https://user-images.githubusercontent.com/69773028/97376219-35fd8b80-1893-11eb-863f-0a7d1f49e942.png)

**Relevant Settings**
None besides mentioned above

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.5.6]
- Git Branch: [eg. master]
- Git Commit Hash: 14b98a32e085d969f010f0249c3d2f660db50880
- Platform and Version: Windows 10
- Python Version: 2.7.18
- Browser and Version: Version 86.0.4240.111 (Official Build) (64-bit)

**Link to logs (required)**
https://gist.github.com/rlongio/dc7070dd26cbfee302e20e0552f3d883

**Comment by JonnyWong16** [comment]
I don't think that is coming from Tautulli. Disable all triggers and play something in Plex. Check other applications where you have used the same webhook.

**Comment by rlongio** [comment]
Its the only webhook.

**Comment by JonnyWong16** [comment]
It is not coming from Tautulli. Shutdown Tautulli and go play something in Plex.

**Comment by rlongio** [comment]
You are absolutely right, my apologies.  Must be coming from Plex.
