### ISSUE TITLE
Error when attempting to start Tautulli service

### ISSUE THREAD

**Issue by capnhowyoudo** [Tautulli/Tautulli-Issues#285]
Not sure where the hang up is at any help would be appreciated.

Trying to run Tautulli as a service in Ubuntu 20.04 LTS

Steps to Reproduce

    Start service : Sudo systemctl start Tautulli.service

Expected Behavior A clear and concise description of what you expected to behavior 

For service to start

Relevant Settings

    eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
    eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
    eg. Newsletter agent configuration/checkboxes/template/etc
    Other settings

Tautulli and System Info (see Tautulli settings page)

    Version: 2.5.6
    Git Branch: Master
    Git Commit Hash: 14b98a32e085d969f010f0249c3d2f660db50880
    Platform and Version: [ubuntu 20.04 LTS]
    Python Version: 2.7.18
    Browser and Version: Firefox 82.0

Oct 28 20:31:55 systemd[1]: tautulli.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit tautulli.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Oct 28 20:31:55  systemd[1]: tautulli.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit tautulli.service has entered the 'failed' state with result 'exit-code'.
Oct 28 20:31:55 systemd[1]: Failed to start Tautulli - Stats for Plex Media Server usage.
-- Subject: A start job for unit tautulli.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit tautulli.service has finished with a failure.
-- 
-- The job identifier is 5887 and the job result is failed.
Oct 28 20:31:55 polkitd(authority=local)[756]: Unregistered Authentication Agent for unix-process:33301:3076957 (system bus name >

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use one of the [support options](https://tautulli.com/#support), with Discord being preferred.
