### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by jasonsansone** [Tautulli/Tautulli-Issues#286]
**Describe the Bug**
Tautulli memory usage steadily increases over time to huge numbers (as high as 120GB).  I restarted Tautulli less than 24 hours ago, but memory usage is over 32GB.  

**Steps to Reproduce**
1. Start Tautulli
2. Wait
3. Check output from 'top -o size'

**Expected Behavior**
I have completely purged my DB, updated Tautulli to the newest build, and updated all FreeBSD packages and python to the newest available.  I would not expect an empty DB to consume 100GB of system memory.

**Screenshots**
<img width="786" alt="Screen Shot 2020-11-01 at 10 26 42 AM" src="https://user-images.githubusercontent.com/14913945/97808500-da355880-1c2c-11eb-94b5-ce9fff653a72.png">
<img width="786" alt="Screen Shot 2020-11-01 at 10 26 21 AM" src="https://user-images.githubusercontent.com/14913945/97808502-dacdef00-1c2c-11eb-91e5-8c96554a4ded.png">

**Relevant Settings**
Settings don't appear to have any relevance to the issue.

**Tautulli and System Info (see Tautulli settings page)**
Version: 2.6.0
Git Branch: master
Git Commit Hash: a8adad7dbb1b992d0b51067b6ccdfc64f64a2950
Arguments: | ['--daemon', '--pidfile', '/root/Tautulli/tautulli.pid', '--quiet', '--nolaunch']
Platform: FreeBSD 12.2-PRERELEASE (FreeBSD 12.2-PRERELEASE 4912790fb32(HEAD) TRUENAS - FreeBSD 12.2)
Python Version: 3.7.9 (default, Oct 17 2020, 01:23:59) [Clang 8.0.1 (tags/RELEASE_801/final 366581)]

**Link to logs (required)**
https://gist.github.com/jasonsansone/368286ae4303a91cc16e1c858869a5f8

**Comment by JonnyWong16** [comment]
Can you try switching to the `nightly` branch to see if the issue is fixed? Go to Settings > General (Show Advanced) > Git Remote / Branch, change the dropdown to `nightly` and click `Checkout Branch`.

**Comment by jasonsansone** [comment]
Sure.  I will test and report back.  As a point of reference, memory usage is up to 78GB right now.

<img width="756" alt="Screen Shot 2020-11-03 at 1 01 12 AM" src="https://user-images.githubusercontent.com/14913945/97957189-25a44f80-1d70-11eb-8f4c-34add4f49060.png">

**Comment by jasonsansone** [comment]
I had to reboot the box to install an update, but it appeared to be holding steady prior to reboot.  System was up over 12 hours without growing past 3GB, so it seems to work.

**Comment by JonnyWong16** [comment]
Thanks for the report. I will consider this as fixed.

**Comment by jasonsansone** [comment]
Thank you!
