### ISSUE TITLE
Can't install 2.6.1 on Mac as "Tautulli is already running|

### ISSUE THREAD

**Issue by gers1978** [Tautulli/Tautulli-Issues#289]
**Describe the Bug**
I am trying to install 2.6.1 from the pkg file.  I keep getting a message saying "Tautulli is already running".  I have closed the app, and killed any Tautulli process in Activity Monitor, but they keep re-opening.  If I click "Retry", I get the same error.

**Comment by JonnyWong16** [comment]
Have you tried removing the app (move to trash) first? Or restarting your computer?

**Comment by PetersenLars** [comment]
I have the same issue (Mac OS). Did try to restart my Mac but that didn't resolve it. Good chance that removing would work but do you have any idea why this is happening? Didn't have this issue when I updated without pkg's.

**Comment by JonnyWong16** [comment]
Disable Tautulli to run on startup before restarting.

**Comment by gers1978** [comment]
> I have the same issue (Mac OS). Did try to restart my Mac but that didn't resolve it. Good chance that removing would work but do you have any idea why this is happening? Didn't have this issue when I updated without pkg's.

Yeah, updating manually with pkgs is a pain anyway.  My Mac mini runs headless.  I have Tautulli running on a Linux seedbed remotely and it just updates automagically.

**Comment by PetersenLars** [comment]
Apparently it remained active in my Login items. Removed it and now it's fixed!

**Comment by JonnyWong16** [comment]
I'm closing this issue because the install bug was part of this fix in [v2.6.1](https://github.com/Tautulli/Tautulli/releases/tag/v2.6.1).

    Fix: High CPU/memory usage in some instances.
