### ISSUE TITLE
History does not work all the time!

### ISSUE THREAD

**Issue by skillfr** [Tautulli/Tautulli-Issues#29]
**Version:** 2.0.24

**Branch:** master

**Commit hash:** ebb287e1ee9d84c88267e8cf5404954f89c6d781

**Operating system:** Debian 7 Linux 4.7.9-xxxx-grs-ipv6-64

**Python version:** 2.7.3 (default, Nov 19 2017, 01:35:09) [GCC 4.7.2]

**What you did?** 
The update of plexpy to tautulli

**What happened?**
History does not work all the time!
It's very annoying to have a history that records when he wants!

**What you expected?**
It works like on plexpy 1.4!

**How can we reproduce your issue?**
I do not know! when I restart Tautulli, it works for 2 or 3 days, then history does not work anymore!

Log : https://pastebin.com/scmfgktu

**Comment by Arcanemagus** [comment]
Please fill out the template when filing an issue. In this case you have omitted your logs, which would be required to see if there was anything wrong here.

You can find instructions on how to post your logs here: [Where can I find my Tautulli logs?](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q14)

**Comment by skillfr** [comment]
an idea ?

**Comment by Arcanemagus** [comment]
I see a couple of different things in your logs.

----

```
2018-03-19 21:02:00 - INFO    :: MainThread : Checking if the database upgrades are required...
2018-03-19 21:02:00 - DEBUG   :: MainThread : Altering database. Renaming notifiers.
```

Every time that Tautulli starts it is attempting to fix the schema of the database, which leads me to think it can't actually _write_ to the database. Can you verify that the user Tautulli is running as has full permissions to the folder it is in?

----

```
2018-03-19 21:26:15 - WARNING :: CP Server Thread-8 : Failed to access uri endpoint /servers/********0d/sync_lists. Status code 401
```

It looks like the token you have stored in Tautulli, although it lets you access the Plex server, isn't letting you talk to plex.tv. Please force a refresh of your authentication token in the settings.

**Comment by skillfr** [comment]
thank you, it seems to work by renewing the token!
