### ISSUE TITLE
Export Metadata for Movie Collection Fails

### ISSUE THREAD

**Issue by abnersnell** [Tautulli/Tautulli-Issues#290]
**Describe the Bug**
Exporting Metadata for a Movie Collection fails.
 
**Steps to Reproduce**
1. Go to 'Libraries'
2. Click on 'Movies'
3. Click on 'Collections' 
4. Select any Movie Collection
5. Click on 'Export Metadata'
6. Leave Defaults
7. Click on 'Export'

**Expected Behavior**
Expect to see "Download" button instead of "Failed" in list at bottom of page

**Tautulli and System Info (see Tautulli settings page)**
Git Branch: | master
Git Commit Hash: | da8d41868d70af75ac8ab95970b5123049cda14f
Configuration File: | /config/config.ini
Database File: | /config/tautulli.db \| Status
Log File: | /config/logs/tautulli.log
Backup Directory: | /config/backups
Cache Directory: | /config/cache
Export Directory: | /config/exports
Newsletter Directory: | /config/newsletters
Arguments: | ['--datadir', '/config']
Platform: | [Docker] Linux 4.15.0-124-generic (#127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 - Debian GNU/Linux 10 buster)
System Timezone: | America/Chicago (UTC-0600)
Python Version: | 3.8.6 (default, Oct 13 2020, 20:49:19) [GCC 8.3.0]

**Link to logs (required)**
https://gist.github.com/abnersnell/067122dd53d771a0eb519cdfc7d73145

**Comment by JonnyWong16** [comment]
Upstream bug with `plexapi`.

https://github.com/pkkid/python-plexapi/pull/616
