### ISSUE TITLE
Support for Synology DSM7 Structure

### ISSUE THREAD

**Issue by crypticraven** [Tautulli/Tautulli-Issues#293]
**Describe the Bug**
Since the upgrade to the Synology to DSM 7 (preview at this point). The update for Plex had significant changes and directory structures. Tautulli no longer see's the installation of Plex on my DSM.

**Steps to Reproduce**
1. Upgrade to DSM 7
2. Update Plex to binaries that support DSM7 natively (not needing to use script triggers and tasks to start/stop services)
3. Use Plex and Tautulli. When Plex is logging a play, it's not detected in Tautulli.

I see that I need to map to "/volume1/@apphome/PlexMediaServer/Plex Media Server/Logs"; but do not have the access to do so.

**Expected Behavior**
Tautulli (if running) will state that it's not able to contact the server.

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.1.29] 2.6.2
- Git Branch: [eg. master] master
- Git Commit Hash: [eg. 2635569e765e5817400ed1032a27bfc850242f6a]
- Platform and Version: [eg. Windows 10] Docker-Synology
- Python Version: [e.g. 2.7.16] 3? It's built into the docker container
- Browser and Version: [e.g. Chrome 74] Chrome 87

**Comment by JonnyWong16** [comment]
Tautulli doesn't use the Plex logs so a change the directory has absolutely not effect on the operation of Tautulli.

Your Tautulli logs are missing from your issue so there is nothing I can do to help you.

**Comment by crypticraven** [comment]
Is there a plan to support Plex on a Synology that's on DSM 7?

**Comment by JonnyWong16** [comment]
There is nothing to change or support. As long as you can run Docker then everything should work as before. That is the entire point of Docker - the containers do not need to know or care about the operating system. If Docker containers are not working then it's an issue with Docker and not an issue with Tautulli.

**Comment by crypticraven** [comment]
How does Tuatulli service detect PMS?

**Comment by JonnyWong16** [comment]
Over your network using the IP address and port or DNS.

**Comment by crypticraven** [comment]
It looks like the configuration of the token changed; I fetched a new token and it's working as expected.
