### ISSUE TITLE
Updating from earlier unofficial snap caused data and config lost

### ISSUE THREAD

**Issue by capruro** [Tautulli/Tautulli-Issues#294]
**Bug Report**
I’m really happy to see that tautulli snap is finally a thing, officially!!
Nevertheless, I'm sad to report an issue with the update. I don’t want to question why data and config folders were moved, however, this change caused all snap users that were using previous unofficial version (tautulli snap <= v2.6.2) to lose their history without being informed. Hopefully the data are still in the old path and I describe below how to mitigate the problem. I understand this is the first official snap release, but I would like to see more notifications about possible destructive changes in the future cause snap have auto-update and in case like this the users needs to be informed in advance.
Thank you!

**Steps to Fix**
1. Stop the snap `sudo snap stop tautulli`
2. Copy your previous folder to the new path `sudo cp -r /var/snap/tautulli/common /root/snap/tautulli/common`
3. Restart your tautulli snap `sudo snap start tautulli`
4. Enjoy your amazing monitoring tool!

**Tautulli and System Info (see Tautulli settings page)**
- Version: [v2.6.3]
- Git Branch: [master]
- Git Commit Hash: [366823cee9229efcfd6e7eca043734d6fcc8fcd3]
- Platform and Version: [snap linux]

**Comment by JonnyWong16** [comment]
Updating the Snap package from v2.6.4 --> 2.6.5 should migrate the user data to `/root/snap/tautulli/common/Tautulli`.

If you end up with an extra subdirectory `/root/snap/tautulli/common/Tautulli/tautulli`, then run the following commands.
```
sudo cp -r /root/snap/tautulli/common/Tautulli/tautulli /root/snap/tautulli/common/Tautulli
sudo rm -r /root/snap/tautulli/common/Tautulli/tautulli
```
