### ISSUE TITLE
Tautulli NotificationHandler :: Notification thread exception: list indices must be integers, not unicode

### ISSUE THREAD

**Issue by SethDG** [Tautulli/Tautulli-Issues#295]
**Describe the Bug**
Email newsletter notification fails with error "Tautulli NotificationHandler :: Notification thread exception: list indices must be integers, not unicode"

**Steps to Reproduce**
1. Configure email newsletter to be sent at midnight for the last day
2. Email newsletter fails with error:

2020-12-24 00:00:18 - ERROR   :: Thread-3 : Tautulli NotificationHandler :: Notification thread exception: list indices must be integers, not unicode
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/notification_handler.py", line 77, in process_queue
    notify_newsletter(**params)
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/newsletter_handler.py", line 136, in notify
    success = newsletter_agent.send()
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/newsletters.py", line 512, in send
    self.newsletter = self.generate_newsletter()
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/newsletters.py", line 473, in generate_newsletter
    self.retrieve_data()
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/newsletters.py", line 837, in retrieve_data
    recently_added[media_type] = self._get_recently_added(media_type)
  File "/share/CACHEDEV1_DATA/.qpkg/Tautulli/tautulli/plexpy/newsletters.py", line 715, in _get_recently_added
    filtered_items = [i for i in recent_items['recently_added']
TypeError: list indices must be integers, not unicode

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17651234/103137346-d4d51700-468d-11eb-8b78-5942dba5a7c6.png)

**Relevant Settings**
Plex Media Server - http://192.168.0.240:32400
Newsletter agent configuration - simple, every day at midnight for last 1 day

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.6.4
- Git Branch: master
- Git Commit Hash: 1019fecc9e61fcb1e18c0c252e76020990d40cb2
- Platform and Version: Linux 4.14.24-qnap (#1 SMP Mon Nov 23 02:11:47 CST 2020)
- Python Version: 2.7.16 (default, May 11 2019, 15:29:22) [GCC 4.9.2]
- Browser and Version: N/A

**Link to logs (required)**
https://gist.github.com/SethDG/b9e226c607a640a3df477ba67d596519

**Comment by samwiseg0** [comment]
Python 2 is not going to be supported anymore. Can you try with python3 and see if you get the same error?

**Comment by SethDG** [comment]
I'm not sure how to force Tautulli to use Python 3 on QNAP.  I have Python v 3.5.2.0.1 installed on my QNAP.  But still Tautulli says it is using Python 2.7.16 (default, May 11 2019, 15:29:22) [GCC 4.9.2].  Obviously, outside of the scope of this issue, but figured I'd ask nonetheless.

**Comment by samwiseg0** [comment]
Please use python3.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29

**Comment by JonnyWong16** [comment]
https://www.reddit.com/r/Tautulli/comments/khm9g4/qnap_nas_tautulli_update_python_2_to_python_3/

**Comment by SethDG** [comment]
> [reddit.com/r/Tautulli/comments/khm9g4/qnap_nas_tautulli_update_python_2_to_python_3](https://www.reddit.com/r/Tautulli/comments/khm9g4/qnap_nas_tautulli_update_python_2_to_python_3/)

Ya, I stumbled across that reddit thread at first, but I didn't see anything there that could help me out

**Comment by JonnyWong16** [comment]
It's not meant to help you. It's meant to tell you that there is *nothing we can do to help you* with Python 3 using the QNAP package.

**Comment by SethDG** [comment]
> It's not meant to help you. It's meant to tell you that there is _nothing we can do to help you_ with Python 3 using the QNAP package.

Thanks, I read it again and again and it started to finally click.  If anyone else stumbles across this issue, I changed Tautulli to use python 3 on QNAP using:

`
ln -bfs /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3 /share/CACHEDEV1_DATA/.qpkg/Tautulli/bin/python
ln -bfs /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3-config /share/CACHEDEV1_DATA/.qpkg/Tautulli/bin/python-config
`

Tautulli now reports that it is running on 3.5.2 (default, Aug 10 2016, 18:01:45) [GCC 4.9.2]

I'll check back in tomorrow after the newsletter runs again tonight with a success or failure.

**Comment by SethDG** [comment]
So, it does appear that running Tautulli with Python 3 resolved my issue.  I received my newsletter tonight.  You can close this issue if you'd like.  Thanks for the assistance & guidance!
