### ISSUE TITLE
Setting TZ=Amercia/Los_Angeles returns UTC time instead of PST

### ISSUE THREAD

**Issue by bbrendon** [Tautulli/Tautulli-Issues#297]
**Describe the Bug**
setting TZ to Amercia/Los_Angeles returns UTC but says "America" ?

I noticed this because I converted from python27 venv to docker install and my graphs were shifted.

But what works...
setting TZ to America/Denver returns MST
setting TZ to PST8PDT returns PST

...I couldn't figure out why Amercia/Los_Angeles is broken. I'm guessing somewhere in the docker chain.

**Steps to Reproduce**
```
cat docker-compose.yaml
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ./tautulli:/config
    environment:
      - PUID=124
      - PGID=1010
      - TZ=Amercia/Los_Angeles
    ports:
      - 8181:8181


# docker exec -it tautulli bash
root@60cdb2adbbf7:/app# date
Wed Jan 13 06:44:20 Amercia 2021
root@60cdb2adbbf7:/app#
# da^C
root@04b3d2ffeabd:/app# exit
# date
Tue 12 Jan 22:44:46 PST 2021
 #

```

**Expected Behavior**
setting TZ to Amercia/Los_Angeles should return PST

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
- eg. Plex Media Server IP address/port/checkboxes/proxy/etc.
- eg. Notification agent configuration/triggers/conditions/text/delay/grouping/etc.
- eg. Newsletter agent configuration/checkboxes/template/etc.
- Other settings

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.1.29]
- Git Branch: [eg. master]
- Git Commit Hash: [eg. 2635569e765e5817400ed1032a27bfc850242f6a]
- Platform and Version: [eg. Windows 10]
- Python Version: [e.g. 2.7.16]
- Browser and Version: [e.g. Chrome 74]

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).

**Comment by JonnyWong16** [comment]
You spelt `America` wrong.

**Comment by bbrendon** [comment]
lol.

**Comment by bbrendon** [comment]
Looks like its still broken...

```
# docker exec -it tautulli bash
root@7441927fd9e9:/app# date
Wed Jan 13 20:02:46 UTC 2021
root@7441927fd9e9:/app# exit
modena:/srv/downloader# date
Wed 13 Jan 12:02:48 PST 2021
 # cat docker-compose.yaml


  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ./tautulli:/config
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=124
      - PGID=1010
      #- TZ=PST8PDT
      - America/Los_Angeles
    ports:
      - 8181:8181

```

**Comment by Arcanemagus** [comment]
You aren't defining your environment correctly. If you need help please move over to our [Discord server](https://tautulli.com/discord.html).
