### ISSUE TITLE
issue upgrading tautulli on synology nas

### ISSUE THREAD

**Issue by axx3lro** [Tautulli/Tautulli-Issues#298]
hello. i had installed plexpy-custom from a .spk on synnocommunity and upgraded to tautulli several years ago. i don't know how to upgrade to v2.5.4 . i have installed python 3 . Where do I find tautulli.service file?
plexpy-custom in installed in /volume1/@appstore/plexpy-custom

![Untitled](https://user-images.githubusercontent.com/30498909/104487687-42d07800-5582-11eb-8842-a8aa823842db.jpg)

**Comment by JonnyWong16** [comment]
GitHub Issues are reserved for bug reports.

Please use the [Discord Server](https://tautulli.com/discord) for support questions.
