### ISSUE TITLE
McAfee thinks Tautulli is a virus

### ISSUE THREAD

**Issue by lucienorrin** [Tautulli/Tautulli-Issues#299]
**Describe the Bug**
McAfee deletes the installer as soon as I download it. 

**Steps to Reproduce**
1. Download latest version (v2.6.5)
2. Try to install/upgrade existing installation
3. McAfee tells me they saved me from a virus...

**Expected Behavior**
Expect it to install without a virus

**Screenshots**
Provide screenshots to help explain your problem.

**Relevant Settings**
- McAfee Internet Security 16
- Security Center 18.9

**Tautulli and System Info (see Tautulli settings page)**
- Version: current version  V2.6.4
- Git Branch: master
- Git Commit Hash: 1019fecc9e61fcb1e18c0c252e76020990d40cb2
- Platform and Version: Windows 10
- Python Version: 3.8.6 

**Link to logs (required)**
I don't think there are any tautulli logs, I never got to the point of opening the installer.

**Comment by lucienorrin** [comment]
![Screenshot 2021-01-15 090047](https://user-images.githubusercontent.com/26599079/104743329-30d10f80-5711-11eb-8043-16c75d642c0f.png)

**Comment by JonnyWong16** [comment]
https://www.reddit.com/r/Tautulli/comments/kx61fx/265_windows_64_installer_doesnt_work_mcafee/
