### ISSUE TITLE
Telegram notification body cannot be blank

### ISSUE THREAD

**Issue by advokatb** [Tautulli/Tautulli-Issues#30]
**Version:**
2.0.24

**Branch:** 
master

**Commit hash:**
ebb287e1ee9d84c88267e8cf5404954f89c6d781

**Operating system:**
Windows 10

**Python version:**
2.7.13

**What you did?**
I've set up Telegram notifications

**What happened?** 
Nothing happened. No notification in Telegram.

**What you expected?**
I've expected to recieve text from my settings 
`<show>Серия <b>{title} (S{season_num}E{episode_num}) </b> добавлена в библиотеку Plex.</show><movie>Фильм <b>{title} ({year})</b> добавлен в библиотеку Plex.</movie>
`
![image](https://user-images.githubusercontent.com/6189889/37734115-e56dfe58-2d52-11e8-8f89-103e71a24fc7.png)

**How can we reproduce your issue?**
Enter my code above in Telegram settings Message Body

**What are your (relevant) settings?**

**Link to logs:**
[tautulli.log.zip](https://github.com/Tautulli/Tautulli-Issues/files/1835038/tautulli.zip)

**Comment by JonnyWong16** [comment]
Do not upload attachments for your logs.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q14

Message bodies cannot be blank.

**Comment by advokatb** [comment]
Sorry for logs. Here is a link https://gist.github.com/advokatb/fef747a18cb443dc2f972deb99cc52c8

I have one notification agent. It's Telegram.
In Telegram Settings on Text tab I've put this code
`
<show>Серия <b>{title} (S{season_num}E{episode_num}) </b> добавлена в библиотеку Plex.</show><movie>Фильм <b>{title} ({year})</b> добавлен в библиотеку Plex.</movie>
`
for **Recently Added** event
![default](https://user-images.githubusercontent.com/6189889/37757693-852e69b0-2db6-11e8-9731-8a5edfff868e.png)
So the Message body IS NOT blank.

**Comment by JonnyWong16** [comment]
It is blank when you add a season/episode/artist/track just like it shows you when you click preview text. You cannot have a blank body.

**Comment by advokatb** [comment]
Hm. I've updated my code to 
```
<show>Серия <b>{title} (S{season_num}E{episode_num}) </b> добавлена в библиотеку Plex.</show><movie>Фильм <b>{title} ({year})</b> добавлен в библиотеку Plex.</movie>
{artist_name}<album> - {album_name}</album><track> - {album_name} - {track_name}</track> was recently added to Plex.
```
so the Preview now looks like this
![default](https://user-images.githubusercontent.com/6189889/37779735-ca368fbc-2df5-11e8-8125-f22a9c81bd6f.png)
so all fields are not blank.

But I do not get any notifications.

When I use `<b>{title}</b> added to Plex.` - notifications work.

What should be my code for separate movies and show notifications?

**Comment by JonnyWong16** [comment]
Post your logs again.

**Comment by advokatb** [comment]
Solved, thanks. Do not know how did I fix it though.
