### ISSUE TITLE
Downloading on Microsoft Edge Chrome version thinks version 2.6.6 has a virus. 

### ISSUE THREAD

**Issue by SmoothAdmin** [Tautulli/Tautulli-Issues#301]
Not sure what's in the .exe packaging but Microsoft Edge (chrome version) thinks that Tautulli version 2.6.6 is a virus and blocks it.

**Comment by JonnyWong16** [comment]
I already submitted it to Microsoft.

**Comment by SmoothAdmin** [comment]
It's also worth noting that Windows Defender completely blocks it. I tried copying it to my 2019 server Plex server and it goes toasted by Defender and I got a notice saying there was a virus.

**Comment by MaddionMax** [comment]
![image](https://user-images.githubusercontent.com/36500454/107284498-3692ea00-6a5e-11eb-87a6-985da3f0935f.png)

**Comment by iekozz** [comment]
Seems to be fixed here, just downloaded and installed without issues. Tested with edge en chrome.

**Comment by MaddionMax** [comment]
Tried again, but nothing changed under Chrome. Defender lock the file as a Trojan.

**Comment by iekozz** [comment]
@MaddionMax Have you updated the definitions?

**Comment by MaddionMax** [comment]
> @MaddionMax Have you updated the definitions?

Of course.

**Comment by SmoothAdmin** [comment]
> Seems to be fixed here, just downloaded and installed without issues. Tested with edge en chrome.

It's working now for me too with the latest Defender defs. 

Thanks!

**Comment by MaddionMax** [comment]
Can you please post the latest def number?

**Comment by iekozz** [comment]
> Can you please post the latest def number?

![image](https://user-images.githubusercontent.com/19673722/107413294-e3c63a80-6b10-11eb-8f55-18cf2251f0dd.png)

**Comment by MaddionMax** [comment]
Thanks. Same as here...but still not working. :(

**Comment by SmoothAdmin** [comment]
I have KB2267602 (Version 1.331.577.0) installed on my Plex server (Windows Server 2019) which allowed Tuatulli to download and install without any issues.

**Comment by JonnyWong16** [comment]
Resolved by Microsoft.

https://reddit.com/r/Tautulli/comments/lflu6z/windows_defender_blocked_tautulli_from_running/gmmhrve/
