### ISSUE TITLE
Media Info Snippets Get Cut Off

### ISSUE THREAD

**Issue by purevertigo** [Tautulli/Tautulli-Issues#304]
When viewing media info for TV or other, the panel loses/cuts off the bottom line. 

![Screen Shot 2021-02-23 at 00 13 13](https://user-images.githubusercontent.com/6506461/108714032-25bd9a80-756d-11eb-80f8-5308b9452e06.jpg)

**Relevant Settings**
All apps tautulli and plex are current versions.

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.6.6
- Git Branch: [eg. master]
- Git Commit Hash: 2cc5bf812fe05e0666aeaeb37ed550c59816fb4c
- Platform and Version: Windows 10
- Python Version: 3.8.6
- Browser and Version: Chrome 88

**Comment by TheMeanCanEHdian** [comment]
You can scroll, this is a result of the hardware transcoding taking multiple lines.
