### ISSUE TITLE
Tautulli creating incorrect Plex Direct URL and Port

### ISSUE THREAD

**Issue by 12nick12** [Tautulli/Tautulli-Issues#31]
**Version:**
Just git pulled today

**Branch:**
master

**Commit hash:**
N/A

**Operating system:**
Debian 8.9

Linux 3.16.0-5-amd64

**Python version:**
2.7.9 

**What you did?**
Git pulled to update

**What happened?**
Tautulli lost access to my plex server

**What you expected?**
I didn't expect the way it connected to change

**What are your (relevant) settings?**
When creating the URL it still tries to use port 32400, but that's blocked via iptables because I put my plex thru cloudflare

Image of issue:
https://imgur.com/a/3thke

**Comment by JonnyWong16** [comment]
That url is retrieved automatically from https://plex.tv/api/resources?includeHttps=1.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q17

**Comment by 12nick12** [comment]
Is there anyway to just make it connect to localhost?

**Comment by JonnyWong16** [comment]
You can type in `localhost` in the IP address box.

**Comment by 12nick12** [comment]
It wasn't letting me before. I guess I was doing it wrong. Thank you for your help. have a great day
