### ISSUE TITLE
get_home_stats return different results than the web page

### ISSUE THREAD

**Issue by Na3blis** [Tautulli/Tautulli-Issues#32]
**Version:**
2.0.25
**Branch:**
master
**Commit hash:**
244008d539bc2aeb2a09b18d9fb4d7331e27798f
**Operating system:**
Docker
**Python version:**
3.6.4
**What you did?**
Made an api call to get_home_stats

**What happened?**
I am putting the info into a grafana graph using python scripts. I make a call to get_home_stats and parse the top_users data to pull out who watched shows and how many from the last day. the total_plays I received from the call are 5 & 3

**What you expected?**
I expected to get total plays of 3 & 3 as is displayed on the web page (though it would be nice if the last day could be programmed to be the last actual day, and not the last 24 hours so at 12:00am all the stats would reset). 

**How can we reproduce your issue?**

Watch some shows the previous day. Call the get_home_stats the next day, at least 24 hours after the first show was watched. Observe the difference between the total plays between the web page and the api call.
As a note, the top tv data in the call is also showing 8 shows watched, rather than the 6 shown on the web page. I'm including a screen shot, as well as the full json for get_home_stats?time_range=1
![tautulli ss](https://user-images.githubusercontent.com/6439247/37828088-3f40cdde-2e70-11e8-86bb-deff64a4ac20.jpeg)

**What are your (relevant) settings?**
I have the parameter time_range=1 set when making the API call
**Link to logs:**
[get_home_stats.txt](https://github.com/Tautulli/Tautulli-Issues/files/1841393/get_home_stats.txt)

**Comment by Na3blis** [comment]
I did not, what does the grouping parameter do?

**Comment by Arcanemagus** [comment]
> what does the grouping parameter do?

The equivalent to Settings -> General -> Group Successive Play History in the web interface, which is enabled by default.

Essentially that takes multiple entries (such as when a user pauses the stream) and groups them into a single one for display.

**Comment by Na3blis** [comment]
Ok, thanks, adding the grouping parameter does seem to solve the issue. Might need to update the API description, all it says is grouping is 1 or 0, and doesn't actually say it's purpose

**Comment by Arcanemagus** [comment]
I think it's assumed that when using the API you know how the regular interface works, PR's to the `nightly` branch of the [code repository](https://github.com/Tautulli/Tautulli) improving the documentation are always welcome 😉.
