### ISSUE TITLE
Get nothing in Poster_url argument 

### ISSUE THREAD

**Issue by djfluo** [Tautulli/Tautulli-Issues#33]
**Version:**
V2.0.25
**Branch:**
master
**Commit hash:**
244008d539bc2aeb2a09b18d9fb4d7331e27798f
**Operating system:**
Ubuntu 16.04
**Python version:**
Python 3.5.2
**What you did?**
Notification with script with {poster_url} argument

**What happened?**
This argument don't work anymore, poster_url=nothing

**What you expected?**
The link of the poster 

**How can we reproduce your issue?**
Try to get information through poster_url argument on "start play" trigger for example.

**What are your (relevant) settings?**
I have all informations with other arguements, only {poster_url} doesn't work
Arguments : {media_type} {title} {season_num00} {episode_num00} {poster_url} {imdb_id} {trakt_url} {library_name} {username} {ip_address}

**Link to logs:**
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/1844604/tautulli.log)
My script : 
[test.sh.txt](https://github.com/Tautulli/Tautulli-Issues/files/1844606/test.sh.txt)

Thank you

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-how-do-i-set-up-imgur-for-notification-posters

**Comment by djfluo** [comment]
@JonnyWong16 
Right ! Sorry 
Thank you JonnyWong16
