### ISSUE TITLE
Cannot Check for Updates

### ISSUE THREAD

**Issue by krohmag** [Tautulli/Tautulli-Issues#36]
**Version:**
2.0.25
**Branch:**
master
**Commit hash:**
244008d539bc2aeb2a09b18d9fb4d7331e27798f
**Operating system:**
Darwin 16.7.0 (macOS 10.13.3 17D102)
**Python version:**
2.7.10
**What you did?**
Selected the 'Check for Updates' button.
**What happened?**
Saw box that Tautulli is up to date 
**What you expected?**
An indication that an update was available. I was originally on 2.0.24.
**How can we reproduce your issue?**
1. Click the 'Check for Updates' button.
2. See box in bottom right corner of window indicating that Tautulli is up to date.
3. Verify error and warning in Tautulli logs.
4. Ran `curl -I  https://api.github.com/repos/Tautulli/Tautulli/commits/master` from same machine and received a 200 HTTP response. 
5. Verified proper installation via FAQ guidelines. This is where I pulled 2.0.25 and restarted Tautulli. 

**What are your (relevant) settings?**
No API tokens. Using origin/master for branch. Standard path for `git`. Updates are enabled. Automatic updates are enabled. 
**Link to logs:** 
https://pastebin.com/6jJf5Fra

**Comment by JonnyWong16** [comment]
This is not an issue with Tautulli. It's a certificate error between your machine and GitHub. I believe `cURL` uses its own certificate store, so it won't give you the same results.

https://githubengineering.com/crypto-deprecation-notice/

https://www.reddit.com/r/PleX/comments/83gmnt/the_tautulli_v2_release_is_finally_here_plexpy_is/dw137c7/

**Comment by Arcanemagus** [comment]
We have a FAQ entry for this now, if that doesn't solve it for you there are instructions in the entry for what to do next 😉

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#ssl-update

Thanks for taking the time to reach out!
