### ISSUE TITLE
Cannot update from 2.0.22 to 2.0.25

### ISSUE THREAD

**Issue by jchhenderson** [Tautulli/Tautulli-Issues#37]
**Version:**
2.022

**Branch:**
master

**Commit hash:**
none

**Operating system:**
Linus 4.2.8 (QNAP NAS)

**Python version:**
2.7.12 (default, Aug 21 2016, 01:11:52) [GCC 5.2.0]

**What you did?**
tried to update from 2.0.22 to 2.0.25 (using "Check for updates" button.

**What happened?**
Tautulli reported it was up to date.

**What you expected?**
2.0.25 to be dowloaded/installed

**How can we reproduce your issue?**
open Tautulli
select Settings
Press <check for updates>

**What are your (relevant) settings?**
?

**Link to logs:**
https://gist.github.com/jchhenderson/07e21927a831c8703903378bb0e42ff8

**Comment by Arcanemagus** [comment]
Please upload your logs as requested in the issue template.

**Comment by jchhenderson** [comment]
I did - I can see the link to it.

...not sure what I have down wrong (sorry).

**Comment by jchhenderson** [comment]
...I can see entries up to now in the logs screen, but when I download them (link in opening post), they stop on 24th.

Here is a copy/paste of the the ones that might be useful.
-- | -- | --
```
2018-03-27 18:20:45 | INFO | Tautulli is up to date
2018-03-27 18:20:45 | INFO | Cannot compare versions. Are you running a local development version?
2018-03-27 18:20:45 | DEBUG | Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/compare/244008d539bc2aeb2a09b18d9fb4d7331e27798f...None
2018-03-27 18:20:45 | INFO | Comparing currently installed version with latest GitHub version
2018-03-27 18:20:45 | DEBUG | Latest version is 244008d539bc2aeb2a09b18d9fb4d7331e27798f
2018-03-27 18:20:45 | DEBUG | Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master
2018-03-27 18:20:45 | INFO | Retrieving latest version information from GitHub

```

**Comment by JonnyWong16** [comment]
Page your logs on [Gist](https://gist.github.com). We will not download a file to view your logs.

**Comment by jchhenderson** [comment]
OK, thanks for the explanation (I did not realise that).  I think I have done it now (I put it in the original post).  But as I wrote, the downloaded log stops a few days ago.  I have added a copy/paste of the last few entries above - would you like me to put them in gist too?

**Comment by JonnyWong16** [comment]
Are you still using the old PlexPy qpkg? Have you installed the new Tautulli qpkg?

**Comment by jchhenderson** [comment]
yes.  I did an in-app update in order to keep my history (that is what I was told to do).

**Comment by jchhenderson** [comment]
...I am happy to install fresh, but there was no "import from PlexPy" option at the time.  Is there one now?

**Comment by Arcanemagus** [comment]
> but there was no "import from PlexPy" option at the time. Is there one now?

If you follow these steps it should update automatically:

1. Shut down PlexPy as well as your Tautulli instance
2. _Copy_ your current `plexpy.db` to `tautulli.db` in the Tautulli folder
3. Start Tautulli

**Comment by jchhenderson** [comment]
OK, got it; terminal access was required to access <NAS>/share/.qpkg/

thanks to both @JonnyWong16 , @Arcanemagus :-)
