### ISSUE TITLE
Tautulli Telegram notifications repeating

### ISSUE THREAD

**Issue by punch1982** [Tautulli/Tautulli-Issues#38]
**Version:**
VERSION V2.0.25 

**Branch:**
master

**Commit hash:**
244008d539bc2aeb2a09b18d9fb4d7331e27798f

**Operating system:**
Windows 10

**Python version:**
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**What you did?**
Set up the bot in telegram but following the upgrade from plexpy to tautulli, I am seeing multiple alerts within seconds of each other in my telegram channel. (See screenshot)
<img width="1309" alt="screenshot at apr 01 20-57-37" src="https://user-images.githubusercontent.com/19227983/38176941-1f9f6800-35f0-11e8-8958-b7a37faa2c9d.png">

**Comment by Arcanemagus** [comment]
You didn't post your logs to confirm this, but I'm assuming you are running multiple instances of Tautulli at the same time.

**Comment by punch1982** [comment]
I have a few users added to said plex and it's only happening now and then and for certain users. What logs would be useful (apologies, new to this!)? At the time of this screenshot, 3 users online and just this one is repeating constantly. 

I believe only one instance is running.

**Comment by Arcanemagus** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q14

**Comment by punch1982** [comment]
https://gist.github.com/punch1982/a044ec1f1eee1905fba2cde3f704a582

**Comment by Arcanemagus** [comment]
https://gist.github.com/punch1982/a044ec1f1eee1905fba2cde3f704a582#file-tautulli-log-L1744-L1751

You have something _very_ odd going on here, it looks like something is force stopping that user's streams... and they are immediately starting them back up again.

I don't see anything wrong with Tautulli itself here though.

**Comment by punch1982** [comment]
So this user has just reported the episode in question being watched played perfectly. Appreciate that's no help, but whilst others were playing in between the repeat alerts, it was just this one client at this time. Very odd.

**Comment by Arcanemagus** [comment]
You can double check the websocket log to see the raw events coming from Plex, but I'm betting it will be showing the same thing but more verbosely. (It contains tokens, don't post it here.)

Plex is telling Tautulli that the user is starting a stream, _something_ is immediately trying to force stop the stream, it's getting stopped... and then immediately starting playing again. That's all I can really tell from these logs.

**Comment by JonnyWong16** [comment]
Try going to Settings > General (show advanced) > Flush Temporary Sessions.

**Comment by punch1982** [comment]
ok thanks, will have a go.

**Comment by icenine9** [comment]
http://dogshit.nerdslam.com/tautullilogs.zip

Same duplicate telegram notification issue. Intermittent, no pattern I can see.

**Comment by JonnyWong16** [comment]
Assuming resolved.
