### ISSUE TITLE
Library media info search cannot handle spaces in search term

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli-Issues#39]
**Version:** v2.0.26-beta
**Branch:** beta
**Commit hash:** 818e7723ff20badc026905edf67c6d81979408da
**Operating system:** Linux 4.4.0-116-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Called get_library_media_info api with search term that contains a space.
**What happened?** Response returned an empty array. Same issue applies for the web interface as well.
**What you expected?** Response should return results that match the search term.
**How can we reproduce your issue?**
* In the web interface go to libraries > any section > media info and type one of the titles, e.g. `fast and furious`. Up to `fast` I get results, once I add the space results list is empty.
* Call the api with same term: `api/v2?apikey=abc&app=true&cmd=get_library_media_info&section_id=1&search=fast%20and%20furious`. Same results as in the web interface.

**Comment by JonnyWong16** [comment]
Your search terms have to match the string exactly. `fast and the furious` not `fast and furious`.

![image](https://user-images.githubusercontent.com/9099342/38203175-2d656ba2-3653-11e8-9a8d-108b4b7e28d7.png)

```
{
    "response": {
        "data": {
            "data": [
                {
                    "added_at": "1435615115", 
                    "audio_channels": "2", 
                    "audio_codec": "aac", 
                    "bitrate": "2086", 
                    "container": "mp4", 
                    "file_size": "1631124244", 
                    "grandparent_rating_key": "", 
                    "last_played": 1435783686, 
                    "media_index": "", 
                    "media_type": "movie", 
                    "parent_media_index": "", 
                    "parent_rating_key": "", 
                    "play_count": 1, 
                    "rating_key": "62561", 
                    "section_id": 1, 
                    "section_type": "movie", 
                    "sort_title": "Fast and the Furious: Tokyo Drift", 
                    "thumb": "/library/metadata/62561/thumb/1462164413", 
                    "title": "The Fast and the Furious: Tokyo Drift", 
                    "video_codec": "h264", 
                    "video_framerate": "24p", 
                    "video_resolution": "1080", 
                    "year": "2006"
                }, 
                {
                    "added_at": "1403551173", 
                    "audio_channels": "6", 
                    "audio_codec": "ac3", 
                    "bitrate": "11726", 
                    "container": "mkv", 
                    "file_size": "9409643707", 
                    "grandparent_rating_key": "", 
                    "last_played": 1435555265, 
                    "media_index": "", 
                    "media_type": "movie", 
                    "parent_media_index": "", 
                    "parent_rating_key": "", 
                    "play_count": 1, 
                    "rating_key": "503", 
                    "section_id": 1, 
                    "section_type": "movie", 
                    "sort_title": "Fast and the Furious", 
                    "thumb": "/library/metadata/503/thumb/1462164418", 
                    "title": "The Fast and the Furious", 
                    "video_codec": "h264", 
                    "video_framerate": "24p", 
                    "video_resolution": "1080", 
                    "year": "2001"
                }
            ], 
            "draw": 1, 
            "filtered_file_size": 11040767951, 
            "recordsFiltered": 2, 
            "recordsTotal": 1366, 
            "total_file_size": 11040767951
        }, 
        "message": null, 
        "result": "success"
    }
}
```

**Comment by tfonfara** [comment]
That is also not working in my case.

<img width="530" src="https://user-images.githubusercontent.com/728683/38203336-39ed2cc4-369f-11e8-8dc2-12c67b4735c1.png">
<img width="552" src="https://user-images.githubusercontent.com/728683/38203339-3de53754-369f-11e8-8adb-c3884b9d2090.png">

**Comment by JonnyWong16** [comment]
Clear your media info cache.

`http://localhost:8181/delete_media_info_cache?section_id=XX`

**Comment by tfonfara** [comment]
`message: "Deleted media info table cache for library with id 1."` and restarted Tautulli afterwards but same results.
But if I search for a different term with spaces this seems to work, so I guess this is some local caching problem. I'll close the issue.
