### ISSUE TITLE
Custom notification with player condition fails to trigger on stop

### ISSUE THREAD

**Issue by mattsch** [Tautulli/Tautulli-Issues#40]
**Version:**
v2.0.25

**Branch:**
master

**Commit hash:**
244008d539bc2aeb2a09b18d9fb4d7331e27798f

**Operating system:**
Linux 4.15.12-301.fc27.x86_64

**Python version:**
2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

**What you did?**
Created a custom MQTT notification trigger (notifier_id 7) on playback, pause, stop and resume for two specific players.

**What happened?**
 Playback triggers just fine, but I've been noticing that it doesn't seem to trigger for stop consistently. I believe pause and resume trigger as well. I suspect it may have to do with other sessions starting while mine is active, but not 100% sure there.

**What you expected?**
The notification trigger to execute for all four states for the specific players.

**How can we reproduce your issue?**
1. Create a notification agent that requires a specific player (or two)
1. Play something from a library
1. Stop playing.

**What are your (relevant) settings?**
Notification agent with triggers on playback, pause, stop, and resume. Screenshots:
![screenshot from 2018-04-02 12-37-24](https://user-images.githubusercontent.com/134440/38205886-4ec959b6-3676-11e8-9b85-2e415eb0c720.png)
![screenshot from 2018-04-02 12-37-08](https://user-images.githubusercontent.com/134440/38205887-4ed8911a-3676-11e8-8eaa-a707b0a073c7.png)

**Link to logs:**
https://pastebin.com/fZ2Q2xcp

**Comment by JonnyWong16** [comment]
Settings > Notifications (show advanced) > Allow Consecutive Notifications

**Comment by mattsch** [comment]
Thanks! I've adjusted and will test later to see if that fixes things. Why would this still fire some of the time with that setting disabled?

**Comment by JonnyWong16** [comment]
If you stop before the watched percentage is reached. (i.e. before 90% or whatever you set it at)

**Comment by mattsch** [comment]
Gotcha.

**Comment by mattsch** [comment]
Apologies, wasn't able to verify until last night, but can confirm changing the setting got things working as expected. Thanks again!
