### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by STaRDoGG** [Tautulli/Tautulli-Issues#41]
I just fetched the latest version 2.0.26 beta, and unzipped it right over the top of my older install (don't recall the exact version # offhand, but it was something like 1.4.x I think). Restarted and refreshed the browser, and this shows in it now:

https://i.imgur.com/hqkEBTJ.png

**Comment by JonnyWong16** [comment]
You got a corrupted download or didn't unzip the files properly. It's missing something.

**Comment by STaRDoGG** [comment]
Thanks. I unzipped version 2.0.28 into the directory and it worked great. I enabled SSL after that, and now I can't access it anymore though, lol, I get:

> This site can’t be reached
localhost refused to connect.
Try:

> Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by Arcanemagus** [comment]
You likely just need to access `https://localhost:8181/`. If that doesn't work we have several [support options](http://tautulli.com/#support) available.

I'm marking this as closed since issues are for bug reports, not support requests.
