### ISSUE TITLE
Facebook notification Issue

### ISSUE THREAD

**Issue by kevmasonk1** [Tautulli/Tautulli-Issues#44]
Hi 

Any help appreciated with this hopefully an easy fix?

-->

VERSION V2.0.28

Master Branch

f335ffa8d5d4d851d69da11a3632a3146cb95f33
--

**Operating system:**
Linux 3.13.0-137-generic

**Python version:**

2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
--
Facebook notifications now dont work since moving to HTTPS
I have followed instructions as per instructions and set Tautulli to Create Self-signed Certificate as per below
Facebook requires HTTPS for authorization. Please enable HTTPS for Tautulli under Web Interface.

I can connect and auto to facebook via the redirect generated ending facebook_redirect
but when I try a test notification the post fails displaying notification failed.
Log details show the below error message:-

Tautulli Notifiers :: Error sending Facebook post: Unsupported post request. Object with ID '********87' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

**Comment by JonnyWong16** [comment]
Facebook has blocked all non-approved apps.

https://developers.facebook.com/blog/post/2018/04/04/facebook-api-platform-product-changes/

**Comment by kevmasonk1** [comment]
Hi 
I believe my app is already approved and Live is there anything I should check

**Comment by Arcanemagus** [comment]
_Nobody's_ app is approved. They are still working out what their new approval process will be. Please read the above link.

**Comment by kevmasonk1** [comment]
Understood, what I meant was my app had already went throug the terrible approval process and was live not 'In Development' I am guessing there is a new process to be followed going forward due to the changes. I assumed if app was already approved and not in development it would be fine.

**Comment by mikeatdesk** [comment]
Is our recourse to just wait until Facebook figures out their approval process, and get our app approved?

**Comment by Arcanemagus** [comment]
There's nothing that can be done about this here at least.
