### ISSUE TITLE
Tautulli update check spams identical notifications

### ISSUE THREAD

**Issue by tfonfara** [Tautulli/Tautulli-Issues#46]
**Version:** v2.0.26-beta
**Branch:** beta
**Commit hash:** 818e7723ff20badc026905edf67c6d81979408da
**Operating system:** Linux 4.4.0-116-generic
**Python version:** 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?** Use a not up to date Tautulli version and setup any notification agent with trigger "Notify on Tautulli Update Available" enabled
**What happened?** Tautulli sends a notification every time a update check runs, even if the same notification was already sent shortly before
**What you expected?** Tautulli update notification should work as same as Plex update notification and send only one notification per update version (so to say cache last known newer version)
**How can we reproduce your issue?**
* Use a Tautulli version that is not up to date
* Enable any notification agent with trigger "Notify on Tautulli Update Available"
* Stress the update check by clicking "check for update" Button (or wait for some time, as update check runs periodically)
* Receive a lot of identical notifications (also check the log files for validation)

**Comment by JonnyWong16** [comment]
> Tautulli update notification should work as same as Plex update notification and send only one notification per update version

The Plex one actually sends the notification every 12 hours when it checks for updates.

**Comment by tfonfara** [comment]
One notification in 12 hours would be okay and enough for the Tautulli one as well I think. I played a bit with the update_check api and resulted in the following, while the pms_update api was called at the same time.
Btw. is there a way to get the currently installed Tautulli version? Maybe to return that always with update_check, in the case that there is no update and there is an update available 🤔

<img width="418" alt="bildschirmfoto 2018-04-07 um 10 35 09" src="https://user-images.githubusercontent.com/728683/38453037-7d57b14c-3a4f-11e8-9ef1-5206dade66bb.png">
