### ISSUE TITLE
Session ending doesn't trigger "Playback stopped" notifications

### ISSUE THREAD

**Issue by jordandrako** [Tautulli/Tautulli-Issues#47]
**Version:** V2.0.28

**Branch:** master

**Commit hash:**  f335ffa8d5d4d851d69da11a3632a3146cb95f33

**Operating system:**
Linux 4.13.0-37-generic (using this docker image: https://hub.docker.com/r/shiggins8/tautulli/)

**Python version:** 2.7.14

**What you did?**

1. Enabled playback stopped trigger on MQTT notification agent.
1. Start playing an episode to test.
1. Stop before episode is over to test (Stop test 1)
1. Receive notification that playback stopped.
1. Resume episode.
1. Let episode end. (Stop test 2)

**What happened?**
- Stop test 1 resulted in receiving MQTT notification that playback stopped.
- Stop test 2 resulted in *NOT* receiving any MQTT notification.

**What you expected?**

Both stopping manually and letting media run to the end to trigger Playback Stopped notifications.

**How can we reproduce your issue?**

1. Enable MQTT notification agent and set up the broker and topic settings.
1. Find a way to monitor published notifications (I'm using an MQTT sensor in home assistant)
1. Enable triggers for: Playback Start, Playback Stop, Playback Pause, Playback Resume.
1. Start playing media as described above to see received notifications.

**What are your (relevant) settings?**
Other than already described the text in the notifications is customized. The subject line is either "playing", "paused", or "stopped". The body is {player}.

**Link to logs:**
Relevant sessions that I was monitoring for my tests are 51 and 52, and my MQTT agent is `notifier_id 5`.
https://gist.github.com/jordandrako/fd587c4bff6fe145f71b88ae528738ad

**Comment by JonnyWong16** [comment]
#40

**Comment by jordandrako** [comment]
Testing.

**Comment by jordandrako** [comment]
Perfect, didn't read that issues body so wasn't sure it was relevant. Thanks.
