### ISSUE TITLE
Notifications Skipping Movies

### ISSUE THREAD

**Issue by XDGFX** [Tautulli/Tautulli-Issues#48]
I've recently set up notifications for twitter - only for recently added content. The notifications were coming through fine until a few days ago, where TV shows notify fine but no movies show up.

Settings in tautulli are default except:

Notification delay: 500s
Group notifications by season or album enabled 
Imgur poster upload enabled 

Twitter agent settings:
Subject: New Media 😁
Body: 

{title} <movie>({year}) </movie>was recently added to {library_name}. 
<movie>Rotten tomatoes rating: {audience_rating}%</movie>

{summary}

V2.0.28
Windows 10
Can't check python version right now as on mobile

Please say if I can add any more detail!

**Comment by JonnyWong16** [comment]
Issue template not filed out properly.
