### ISSUE TITLE
Facebook Notifications to Closed Group stopped working

### ISSUE THREAD

**Issue by mikeatdesk** [Tautulli/Tautulli-Issues#49]
**Version:** 2.0.28

**Branch:** master

**Commit hash:** f335ffa8d5d4d851d69da11a3632a3146cb95f33

**Operating system:** Darwin 17.4.0

**Python version:** 2.7.10

**What you did?** No changes other than automatic updates via git

**What happened?** Facebook Notifications to Closed Group stopped working

**What you expected?** Facebook Notifications continue working.

**How can we reproduce your issue?** Setup a Facebook Notification Agent to post to a Private Group, following the specific steps outlined in the Notification Setup.

It was working for months, then suddenly stopped.

I found one Google result that suggested re-creating the Facebook App, which I did. It yielded the same here.

Error: Tautulli Notifiers :: Error sending Facebook post: Unsupported post request. Object with ID '********43' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

Error is identical on both Facebook Apps. Previously worked, stopped on April 4th.

**What are your (relevant) settings?**
http://take.ms/hO9o4

**Link to logs:**
http://take.ms/42dNH

**Comment by JonnyWong16** [comment]
Duplicate #44.
