### ISSUE TITLE
Port not changing

### ISSUE THREAD

**Issue by bdschuster** [Tautulli/Tautulli-Issues#50]
**Version:**
v2.1.0-beta
**Branch:**
beta
**Commit hash:**
b144ded87bcf2f561eff40531eab6655f4270ea7
**Operating system:**

Linux 4.4.0-119-generic
**Python version:**
 2.7.12
**What you did?**
Changed Port in config
**What happened?**
Port changed in config file, and showing in settings, but still working on old port 8181
**What you expected?**
Port to change to new port 8183
**How can we reproduce your issue?**

Settings > Web Interface > HTTP Port changed to 8183 > Save.
Service restarts, settings show new port, but still working on old port, checked config file, confirmed it did change in config file. Restarted service manually, but still working on old port.

**Comment by JonnyWong16** [comment]
Check if you have multiple instances of Tautulli running (multiple python processes).

**Comment by bdschuster** [comment]
There looks to be about 21 running, all ending in --port=8181.
After checking logs, i see 

  | Using forced web server port: 8181
-- | --

After changing to 8183 and restarting.

**Comment by bdschuster** [comment]
and that number varies on how many are running, been watching and it's about 19-24 processes always running.

**Comment by JonnyWong16** [comment]
Make sure there is only one process running.

Whatever method you are using to start Tautulli has the command line argument for `--port`. The setting in the UI won't do anything because the command line argument takes precedence.

**Comment by bdschuster** [comment]
Thanks for pointing me in the right direction, found my issue in /etc/defaults/plexpy, there was a port specified there...I commented out that line, now I am able to change the port within settings. Also, it still seems that several PID's actually run all the time. When i stop the service (or shutdown via web), it does stop all of them. Is this normal?

**Comment by JonnyWong16** [comment]
No, there should only be one instance started.
