### ISSUE TITLE
Some eligible notifications not triggering

### ISSUE THREAD

**Issue by antigravity83** [Tautulli/Tautulli-Issues#51]
Version: 2.0.28
Branch: Master
Commit Hash: f335ffa8d5d4d851d69da11a3632a3146cb95f33
Operating System: Linux 4.9.0-6-amd64
Python Version: 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

WHAT YOU DID
Set up Pushover notifications for when the following content is added to my library:
TV Shows - Episode = 01, Airdate = 2018
Movies - Release Date = 2017 and/or 2018

WHAT HAPPENED
Some eligible content not triggering a notification

See examples of new content that didn't trigger a notification: https://imgur.com/ehzogWC

WHAT I EXPECTED
Pushover notifications to be generated when the eligible content is added to library. 

HOW TO REPRODUCE
Use the same notification settings and add eligible content to the library- see if the appropriate notifications are triggered.

SETTINGS
Group notifications by Season or Album: No
Group notifications by TV Show or Artist: No
Notification Delay: 600 seconds
Notify on Recently Added: Yes
Conditions: https://imgur.com/UdJ3YFA

LOGS
https://gist.github.com/antigravity83/22ac6777a3c33a6c6db80480ac790c26

**Comment by Arcanemagus** [comment]
The Recently Added picture you posted doesn't seem to be included in your logs.

You logs are _full_ of your custom condition evaluating to `False`, which I'm not surprised at since you seem to be missing several `()` from what you are intending there.

Please note that issues are _not_ the place for help getting your custom notifications working, but for bug reports.

**Comment by antigravity83** [comment]
Thanks - wasn't sure if it was a bug or an issue with my notification config. 

Thanks for the hint- I missed the () functionality

**Comment by JonnyWong16** [comment]
GitHub issues are for bug reports not support questions.
