### ISSUE TITLE
http_password is changing on restart

### ISSUE THREAD

**Issue by vjbonan** [Tautulli/Tautulli-Issues#53]
Hello,  I am not sure what version I am but pretty recent, but I cannot check because I can not log in, for whatever reason my http_password in config.ini keeps changing to a strange value at least 50 characters long.   This happens whenever tautulli starts.  I did recently install the app on the phone.  Could this be related? 

Any help would be appreciated.  Thanks!

**Comment by Arcanemagus** [comment]
I'm closing this as issues are **not** the place for support requests, we have [several options](http://tautulli.com/#support) available for that, with [Discord](https://discord.gg/tQcWEUp) being preferred.

----

Your question is also already answered in the FAQ: https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q3
