### ISSUE TITLE
After enabling Self hosted images twitter notifications with posters fail

### ISSUE THREAD

**Issue by samwiseg00** [Tautulli/Tautulli-Issues#54]
**Version:**
V2.1.1-BETA
**Branch:**
Beta
**Commit hash:**
1d3cd431ebd02a6d9b7e7aa1d9a2cd935c033fd9
**Operating system:**
Linux 3.10.0-693.2.2.el7.x86_64
**Python version:**
2.7.5 (default, Aug 4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
**What you did?**
Change Image Hosting from Imgur to self hosted
**What happened?**
Twitter notifications fail with error
```
Tautulli Notifiers :: Twitter notification failed: {'message': 'Media type could not be determined.'}
```
**What you expected?**
Twitter notifications to succeed. 
**How can we reproduce your issue?**
Setup twitter notifications to post on any action. Use Include Poster Image

I have ensured that /image is externally accessible without auth. 
Newsletters and its images work just fine with self hosted. 
Discord notifications with posters work as well with self hosted images. 

Let me know if you need me to perform further debug. 

**What are your (relevant) settings?**
Include Poster Image
**Link to logs:**
https://gist.github.com/samwiseg00/a7bfb825d000deee0bcc69566c0531a0

**Comment by meepmeep** [comment]
I have a similar issue with the newsletter settings.

- I started with imgur as hosting service for image, 
- Send some newsletters, everything was fine, 
- Try to switch to "self hosted on public Tautulli domain". On the next newsletter I get these logs (one for each image which should be uploaded) :

`Tautulli Helpers :: Cannot upload poster to Imgur. No Imgur client id specified in the settings.
`

**Comment by JonnyWong16** [comment]
That's completely unrelated. You do not have self-hosted newsletters configured correctly.

**Comment by JonnyWong16** [comment]
They don't. That's why they are separate settings.

**Comment by meepmeep** [comment]
So, only using "self hosted image" should work ? (without copying newsletter to /newsletter folder ?)

I try with both checked, it works. But it wasn't my main question here (only checking self hosted image didn't work as I thought)

**Comment by samwiseg00** [comment]
Confirmed fixed!

Thanks!
