### ISSUE TITLE
Cannot scroll down in the Watch Statistics Lists in Firefox on Mac OS

### ISSUE THREAD

**Issue by morrisonpeter** [Tautulli/Tautulli-Issues#55]
You can scroll down on the Watch Statistics Lists when using Safari on MacOS or iOS, or Firefox on Windows 10, but this action does not work on Firefox [59.0.2 (64-bit)] running on MacOS [10.13.4 (17E199)], for me.

Tautulli is installed on a Windows 10 Pro server and I am accessing Tautulli on my Mac through my local network.

There are no error messages in my tautulli.log file or plex_websocket.log file so I haven't included them in this issue. I'll add them if requested.

**Version:**
v2.0.28

**Branch:**
master

**Commit hash:**
f335ffa8d5d4d851d69da11a3632a3146cb95f33

**Operating system:**

Windows 10
{although the bug is in the web interface on MacOS High Sierra [10.13.4 (17E199)] - using Firefox [59.0.2 (64-bit)]}

**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]

**What you did?**
Attempt to scroll through the lists of Watch Statistics on the Tautulli homepage, viewed over my LAN on Firefox on MacOS.

**What happened?**
Nothing

**What you expected?**
The lists should normally scroll down (the lists, not the page) with the mouse wheel, and/or a scroll bar appears on some browsers.

**How can we reproduce your issue?**

1. Open Firefox on MacOS
2. Open the Tautulli web interface. (In my case enter the IP version of the URL [http://192.168.86.34:8181/home])
3. Attempt to scroll through the Watch Statistics (any of the sections).
3b. The bug: the mouse wheel moves the page and not the list in the box of statistics, and no scroll bar appears.

**What are your (relevant) settings?**
Initial off-the-shelf settings + Pushover notification agent configured.

**Link to logs:**
As per above, "There are no error messages in my tautulli.log file or plex_websocket.log file so I haven't included them in this issue. I'll add them if requested."

**Comment by Arcanemagus** [comment]
It looks like this is a [known issue](https://support.mozilla.org/en-US/questions/984141) with Firefox on macOS, with the recommended work around being to turn off Smooth Scrolling in Firefox's settings.

I'm marking this as closed since this has nothing to do with Tautulli itself.

**Comment by morrisonpeter** [comment]
For anyone looking at this in the future the recommended solution in the "known issue" link, turning off smooth scrolling in Firefox, did not fix the problem and made no difference. So using a different browser is the band-aid solution unless Firefox catches this issue.

**Comment by Arcanemagus** [comment]
Does Chrome work for you? Or is it _only_ Safari that works?

**Comment by morrisonpeter** [comment]
I just checked and it does work in Chrome [Version 65.0.3325.181 (Official Build) (64-bit)].

I haven’t used it in ages because Chrome has performance issues on Mac OS (that’s why I use Firefox for cross-platform browsing) but Chrome says the version is up to date.

So I have only found this issue in Firefox and only on MacOS.



On Apr 14, 2018, at 8:44 PM, Landon Abney <notifications@github.com<mailto:notifications@github.com>> wrote:


Does Chrome work for you? Or is it only Safari that works?

**Comment by Arcanemagus** [comment]
Does the page itself scroll? Or is it only the cards that don't scroll?

**Comment by Arcanemagus** [comment]
There are some additional workarounds reported here: https://support.mozilla.org/en-US/forums/contributors/709697?last=54950#post-54832

**Comment by morrisonpeter** [comment]
The page itself scrolls instead of the individual statistics boxes, in Firefox Mac. 

I tried changing "show scroll bars" to  "always" but no change. The scroll bars appeared in all of my my windows but they did not appear in the statistics boxes like they do in the other browsers/OS's.
