### ISSUE TITLE
Notification should wait until Plex has gathered alle meta data

### ISSUE THREAD

**Issue by Skaronator** [Tautulli/Tautulli-Issues#59]
**Version:** 2.0.28
**Branch:** master
**Commit hash:** f335ffa8d5d4d851d69da11a3632a3146cb95f33
**Operating system:** Debian 9 via Docker

**Python version:** 2.7.14
**What you did?** Added a movie/series

**What happened?** Tautulli send a notification with a thumbnail from the movie file since Plex didn't got the meta data yet.

![image](https://user-images.githubusercontent.com/2886913/38904839-04c21cfc-42ad-11e8-91eb-04d86c7a410d.png)

**What you expected?** Tautulli should wait until Plex has alle the meta data.

**How can we reproduce your issue?**
Adding lot of new media files and maybe throttling the internet speed.

**Link to logs:** https://gist.github.com/Skaronator/2191e7b8852a9183e34e2b845783e8f9

(I've added the movie twice, I had to change the setting to reproduce it faster. )

I've set the delay to 5 and 10 min but sometimes tvdb is down and other time it just loads forever in Plex. I don't know why, Plex is running on a SSD raid so I/O R/W shouldn't be the bottleneck. Would be good if Tautulli can just wait. Maybe add another setting for a timeout value for example 1 hour (3600s) and if Plex didn't got the Meta Data it would just send out the notification anyway.

**Comment by JonnyWong16** [comment]
This is not a bug report.

**Comment by humoba** [comment]
If this is not a bug, how we can solve it?

How to put a delay to wait for the metadata to be ready?

@Skaronator how did you repair it?

**Comment by samwiseg00** [comment]
@humoba You need to set a notification delay in the settings. I recommend 500 seconds. Go to Settings > Notifications & Newsletters, Notification Delay

In the future please use one of our [support options](https://tautulli.com/#support), with the [Discord server](https://tautulli.com/discord) being preferred.

Thanks

**Comment by slamdunx** [comment]
Would be interested to hear if you have any success trying the code I posted yesterday:

Tautulli/Tautulli#1338

Feedback in the pull request comments section would be much appreciated please.

Thanks.
