### ISSUE TITLE
Public Tautulli Domain Resetting

### ISSUE THREAD

**Issue by ryanmcgr** [Tautulli/Tautulli-Issues#60]
**Version:**
2.1.1
**Branch:**
beta
**Commit hash:**
1d3cd431ebd02a6d9b7e7aa1d9a2cd935c033fd9
**Operating system:**

Linux 4.4.0-119-generic
**Python version:**
2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
**What you did?**
Entered the wrong subdomain for Public Tautulli Domain by accident. 
**What happened?**
Incorrect domain remains, regardless of update/restart

**What you expected?**
Should update
**How can we reproduce your issue?**

Added a domain from default. Save & Restart. Change to another domain. Save & Restart. Update won't occur.
**What are your (relevant) settings?**

**Link to logs:**

**Comment by ryanmcgr** [comment]
Probably worth noting that the other settings I've adjusted under the Web Interface settings page have updated as expected.

**Comment by Arcanemagus** [comment]
You haven't linked your logs, or reported any errors you are seeing, so since it's working fine for everyone else there isn't much that can be said here.
