### ISSUE TITLE
Amazon Echo *name* not showing in Most Active Platforms panel

### ISSUE THREAD

**Issue by nurbles** [Tautulli/Tautulli-Issues#64]
**Version:**
2.0.28
**Branch:**
master
**Commit hash:**
f335ffa8d5d4d851d69da11a3632a3146cb95f33
**Operating system:**
Windows 10
**Python version:**
2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
**What you did?**
Looked at the home screen
**What happened?**
Noticed an empty line in the "Most Active Platforms" panel
**What you expected?**
I expected the empty line to show "Alexa" or "Echo" or something like that.
**How can we reproduce your issue?**
Use an Amazon Echo with the Plex skill to play music from the Plex Media Server.
**What are your (relevant) settings?**
All defaults ... I'm new to Tautulli and haven't started messing with trying to change any settings.
**Link to logs:**
none

First Image shows the Tautilli panel for the Echo when it is playing music from Plex.  Note "Alexa" and "Plex for Alexa" in the panel.
![tautulli-now-playing](https://user-images.githubusercontent.com/14079927/39271373-dbaec748-48a6-11e8-9226-495edfb4aac6.png)

The second image shows the Most Active Platforms panel at the same time.  (I use my Echo Dot & Show to play Plex music often.)
![tautulli-mostactive](https://user-images.githubusercontent.com/14079927/39271457-19e5defc-48a7-11e8-9c7b-40965d516fe2.png)

**Comment by JonnyWong16** [comment]
Supposedly fixed by Plex.
https://forums.plex.tv/discussion/comment/1660392/#Comment_1660392

Previously recorded history in Tautulli won't be updated. New history should show the correct platform.
