### ISSUE TITLE
Excessive Pushover API usage

### ISSUE THREAD

**Issue by jcs** [Tautulli/Tautulli-Issues#65]
I'm the developer of Pushover and am tracking down an increase in excessive API usage recently that all appear to be coming from your application.

Requests to `/1/sounds.json` and `/1/users/validate.json` are being made for every user of your software, often multiple times per minute.

Why is your software making these requests so often?  Validating a user and fetching the list of sounds should only be done once when the user configures them in the software.

**Comment by Arcanemagus** [comment]
It looks like the sounds are being [dynamically retrieved](https://github.com/Tautulli/Tautulli/blob/f335ffa8d5d4d851d69da11a3632a3146cb95f33/plexpy/notifiers.py#L2786-L2804) whenever the [configuration is requested](https://github.com/Tautulli/Tautulli/blob/f335ffa8d5d4d851d69da11a3632a3146cb95f33/plexpy/notifiers.py#L2825)... which happens every time a notification goes out.

That only explains the `/1/sounds.json` calls, not the `/1/users/validate.json` calls, as the only other line is a call to [`/1/messages.json`](https://github.com/Tautulli/Tautulli/blob/f335ffa8d5d4d851d69da11a3632a3146cb95f33/plexpy/notifiers.py#L2784) when it sends the actual message.

I'm sure there is a better way the `/1/sounds.json` calls can be handled at least, I'll make sure to bring this to the attention of the devs!

**Comment by Arcanemagus** [comment]
@jcs Since we can't find anywhere that `/1/users/validate.json` is being called here, is it possible that's an internal API call that is being generated by the calls to `/1/sounds.json` and/or `/1/messages.json`?

**Comment by jcs** [comment]
Sorry, you can disregard that part, apparently those calls are coming from another broken application.
