### ISSUE TITLE
Tautulli Remote - minor ui issue when viewing history

### ISSUE THREAD

**Issue by jkurelek** [Tautulli/Tautulli-Issues#66]
Version: Tautulli Remote 1.4.193
OS: Android

When viewing the history, it is impossible to remove focus from the search bar, which results in the keyboard always blocking a significant portion of the history. Makes browsing the history very cumbersome/annoying.

![screenshot_20180427-225558](https://user-images.githubusercontent.com/5564064/39391310-41d3e3ae-4a6f-11e8-9892-5de4e86efd07.png)

Thanks. Love Tautulli and the new remote app. Cheers.

**Comment by Arcanemagus** [comment]
Please file this on the [Tautulli-Remote](https://github.com/Tautulli/Tautulli-Remote) repository.
