### ISSUE TITLE
Incorrect posters displayed next to some movies

### ISSUE THREAD

**Issue by ThomasRules2000** [Tautulli/Tautulli-Issues#72]
**Version:**
2.1.4
**Branch:**
Master
**Commit hash:**
b1dc5816a4e8209b954802fa0793186c2ae64b34
**Operating system:**
FreeBSD 11.0-RELEASE

**Python version:**
2.7.13

**What you did?**
Opened up Tautulli to homepage and user page

**What happened?**
Incorrect posters are displayed next to movies, and certain links go to the wrong title

**What you expected?**
Movies are displayed with the correct posters and titled links go to the correct movies

**How can we reproduce your issue?**

Appears to happen randomly across the app - certain movie posters are replaced with others in the library, [album showing occurences](https://imgur.com/a/bop7ez5)
**What are your (relevant) settings?**

**Link to logs:**
https://gist.github.com/ThomasRules2000/2a8fd2185c93e3bc4d16cd4188b9db67

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#move-media

**Comment by ThomasRules2000** [comment]
This works for some movies, but others appear to be missing the "Fix Metadata" button

**Comment by JonnyWong16** [comment]
You have to click from the history page.

**Comment by ThomasRules2000** [comment]
Resolved, although there should be an option to fix metadata when going clicking in from any source, not just the history page
