### ISSUE TITLE
Images not showing in Newsletter

### ISSUE THREAD

**Issue by Kazz3r24** [Tautulli/Tautulli-Issues#73]
**Version: 2.1.4**

**Branch: master**

**Commit hash: b1dc5816a4e8209b954802fa0793186c2ae64b34**

**Operating system: Linux 4.4.0-122-generic**

**Python version: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]**

**What you did? Enabled newsletter and ensured HTML support was enabled for email. Chose imgur for image source**

**What happened? The newsletter works but images aren't showing in the email, tried several browsers and cleared cache. Tried self-hosted images and got same result. The newsletter page which is enabled properly displays images, just not in the email**

**What you expected? For images to show up in the email**

**How can we reproduce your issue? Currently using Gmail as my smtp provider, images are allowed in Gmail from external sources, SSL is configured properly. Images have worked using other apps before**

**What are your (relevant) settings?

**

**Link to logs:**
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/1980436/tautulli.log)

**Comment by JonnyWong16** [comment]
Not a bug report.

![image](https://user-images.githubusercontent.com/9099342/39710518-e2e13184-51d1-11e8-8edd-6e72cfe7aa10.png)

**Comment by Kazz3r24** [comment]
Same result even after switching to Cloudinary and uploading the images from cache/images. I've cleared the browser cache, checked permissions and ownership, restarted Tautulli, I can't even see a mention of it trying to connect with Cloudinary in the logs, unless I can turn on verbose logging somehow?

Any other suggestions? If it's not a bug, where should I post this?

[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/1980949/tautulli.log)

**Comment by JonnyWong16** [comment]
[Discord](https://discord.gg/tQcWEUp) `#support` channel.

**Comment by Satalink** [comment]
Notable bug for local hosted images.
1.  http protocol should follow Tautulli -> Web Interface -> HTTP(S) [ Enable HTTPS ] flag.  
2.  http image links should follow the Tautulli -> Web Interface -> HTTP Port value.

i.e.  
HTTP PORT:  4321
ENABLE HTTPS:  false

<img src="http://domain.my:4321/path/to/newsletter/images/image.ext">

Provided you have port forwarding set up for your Tautulli process, your images should be able to be self hosted for public use.

**Comment by Arcanemagus** [comment]
@Satalink That's what this setting is for:
![image](https://user-images.githubusercontent.com/427137/44542413-98f6a500-a6c1-11e8-897d-8b94dfc4c6bb.png)

When enabling self hosted images you should have gotten a warning that you need to configure that properly.

**Comment by JonnyWong16** [comment]
No it shouldn't because your self-hosted URL should be set exactly how you want to link it. For example, my reverse proxy is HTTPS on port 443 and my Tautulli web interface  settings are HTTP on port 8181. Following the Tautulli settings would cause it to fail.
