### ISSUE TITLE
Newsletter not working with libraries that are hidden from the Plex dashboard

### ISSUE THREAD

**Issue by adamgot** [Tautulli/Tautulli-Issues#75]
**Version:**
V2.1.5-BETA

**Branch:**
beta

**Commit hash:**
8e3fe7bfa2854414fc4abd21a6ce7a7dc5766455

**Operating system:**
Linux 3.16.0-4-amd64

**Python version:**
2.7.9

**What you did?**
Created a newsletter with libraries that are not included in the Plex dashboard.

**What happened?**
Libraries hidden from the Plex dashboard were not included in the newsletter. If only such libraries are specified, no newsletter will be sent due to no data.

**What you expected?**
Newsletter to produce recently added items regardless of them being visible in the Plex dashboard. You can already specify exactly which libraries to include in the newsletter, so even libraries hidden from the dashboard should work if they're explicitly specified (otherwise I could see this being intended behaviour).

**How can we reproduce your issue?**
Create a Plex library, add some items, edit the library -> advanced -> uncheck "Include in dashboard", create a newsletter specifying the library and try to send it.

**What are your (relevant) settings?**

**Link to logs:**
`WARNING | Tautulli Newsletters :: Recently Added newsletter has no data. Newsletter not sent.`

**Comment by JonnyWong16** [comment]
Already answered in the FAQ.

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-recently-added-library

**Comment by adamgot** [comment]
@JonnyWong16 Any chance of changing it so that newsletter generate recently added items the same way that's done on the library view page?
