### ISSUE TITLE
MQTT stopped notifications not firing when pressing stop once the watched percentage has been reached

### ISSUE THREAD

**Issue by UhtredTheBold** [Tautulli/Tautulli-Issues#79]
**Version:**
V2.1.4
**Branch:**
master
**Commit hash:**
b1dc5816a4e8209b954802fa0793186c2ae64b34
--
**Operating system:**

Linux 4.4.0-121-generic
**Python version:**
2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?**
Enabled MQTT notification agent and enabled watched and stop triggers.
**What happened?**
After reaching the watched percentage of a show and pressing stop, an MQTT watched notification was sent only.
**What you expected?**
I expected both stopped and watched notifications to fire. This means my light automation does not work correctly as it only looks for stopped notifications. If I monitor for watched notifications as well then it can fire when the show is still playing.
**How can we reproduce your issue?**

Turn on MQTT notification agent, monitor incoming MQTT notifications and watch the last few minutes of a show and press stop.
**What are your (relevant) settings?**
MQTT notification agent with my broker settings and disabled all but playback, stopped and watched triggers.
**Link to logs:**
I'm not sure how to export logs.

**Comment by JonnyWong16** [comment]
#47
