### ISSUE TITLE
Data missing after update from PlexPy to Tautulli

### ISSUE THREAD

**Issue by marcor2196** [Tautulli/Tautulli-Issues#80]
**Version:**
2.1.4
**Branch:**
beta
**Commit hash:**
b1dc5816a4e8209b954802fa0793186c2ae64b34
**Operating system:**
Win10 Pro x64
**Python version:**
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
**What you did?**
Updated PlexPy.
**What happened?**
After update, all data from my previously PlexPy are missing.
**Link to logs:**
https://www.dropbox.com/s/hqajkh6bthfdp0k/tautulli.log?dl=0

**Comment by JonnyWong16** [comment]
You are starting Tautulli with an unsupported `PlexPy.pyw` file.

Please follow the correct method outlined in the [wiki](https://github.com/Tautulli/Tautulli-Wiki/wiki/Install-as-a-daemon).

**Comment by marcor2196** [comment]
![immagine](https://user-images.githubusercontent.com/39311786/40073655-bc73d806-5877-11e8-8934-b3b9b3e9af38.png)

**This is my shortcut in Startup folder of Windows, its wrong?
I had followed your guide, in fact.**

**This is also the windows folder after the update:**
![immagine](https://user-images.githubusercontent.com/39311786/40073831-429d9c1e-5878-11e8-91f3-d9714ee81bdc.png)

**Comment by JonnyWong16** [comment]
Your logs shows you using the `PlexPy.pyw` file.
```
E:\Programmi\plexpy-master\PlexPy.pyw
```

Delete the `tautulli.db` file and start Tautulli properly with that new shorcut.
