### ISSUE TITLE
Live feeds stuck as playing

### ISSUE THREAD

**Issue by Dulanic** [Tautulli/Tautulli-Issues#81]
**Version:**
VERSION V2.1.4
**Branch:**
master
**Commit hash:**
b1dc5816a4e8209b954802fa0793186c2ae64b34
**Operating system:**
Linux 4.13.0-41-generic

**Python version:**
2.7.14

**What you did?**
Played a live TV channel remotely from my phone via Plex.

**What happened?**
It shows as playing days later.

![image](https://user-images.githubusercontent.com/2948206/40197593-8239971c-59d9-11e8-96e7-14f55abbf1a6.png)

**What you expected?**
Either 1. Ignore live streams or 2. Update when playback stopped.  I'm going to assume #1 as the live feeds are not the most useful information provided by Plex.

**How can we reproduce your issue?**
1. From a remote plex device (in my case a Note 8) play live TV.
2. You will see the live stream show on Activity and it will go away when it stops, but if you go into history, it will still show Currently Playing.

**What are your  (relevant) settings?**
DVR /w HD Homerun.

**Link to logs:**
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/2014348/tautulli.log)

**Comment by Arcanemagus** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#history-q3

See the above for how to flush temporary sessions. This isn't a problem with Live feeds in particular, but a rare case where Plex just fails to tell Tautulli that the stream has stopped.

**Comment by Dulanic** [comment]
But is this the situation? The FAQ clearly says that it shouldn't show it in history unless it is stopped AND that is longer than the duration. This doesn't meet either of these criteria.
```

History is only logged if all those following conditions are satisfied:
After the stream is stopped.
If the total stream duration is longer than the "Ignore interval" you set (Settings > General > Show Advanced).
If "Keep History" for the user is enabled (Users > Edit Mode > Toggle Keep History).
If "Keep History" for the library is enabled (Libraries > Edit Mode > Toggle History).
```
