### ISSUE TITLE
<tv> content included in Telegram <movie> notifications

### ISSUE THREAD

**Issue by mvdg-nl** [Tautulli/Tautulli-Issues#83]
Version: V2.1.4
Git Branch: master
Git Commit Hash: b1dc5816a4e8209b954802fa0793186c2ae64b34
Platform: Darwin 17.5.0
Python version: 2.7.10 (default, Oct 6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

**What happened?**
Content between `<tv>` tags gets included in notifications for movies in Telegram. See screenshots for settings and preview. Result in the preview is the same as actual Telegram notification.

**What you expected?**
Movie subject line: `<b>`Nieuwe film: {title} ({year})`</b>`
Movie content line: {imdb_url}

**Screenshots**
![screen1](https://user-images.githubusercontent.com/37312145/40268043-c31e6c6a-5b66-11e8-92ad-193c62cf524c.jpeg)

![screen2](https://user-images.githubusercontent.com/37312145/40268044-c3f8ae02-5b66-11e8-982c-d7efcd501153.jpeg)

**Comment by JonnyWong16** [comment]
`<tv>` is not a valid tag.
