### ISSUE TITLE
GDPR Complience

### ISSUE THREAD

**Issue by samip5** [Tautulli/Tautulli-Issues#84]
Unfortunately, due to the nature of the issue, I'll create it here as it's not really a feature, but rather a mandatory thing by law.

What would be the best approach in creating a way to get the concent to monitor the usage, as it would require to have a opt-out too?

Everyone who has EU users using their Plex, this affects you most likely.

**Comment by Hellowlol** [comment]
https://www.gdpreu.org/the-regulation/who-must-comply/
