### ISSUE TITLE
Ubuntu 18 / Python 3.6.5

### ISSUE THREAD

**Issue by myplexter** [Tautulli/Tautulli-Issues#85]
Version v2.1.9
**Branch:**
Master
**Commit hash:**
8e4aba7ed41eded677cb5e590f4fc352f44f1a4e
**Operating system:**
Linux 4.15.0-22-generic (#24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 - Ubuntu 18.04 bionic)
**Python version:**
2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

Ubuntu 18 is running at Python 3.6.5

Unable to enter in smtp server password - not a clickable area. Attempted to manually configure by going into the ini file and entering the password. refreshed tautulli. Still not showing password. It has a password listed now, but of incorrect length. Installed PIP and also have python 2.7 installed. Issue is still there. Unable to facilitate changes or input proper password. Attempted to create a new agent and issue is same. Subzero subtitles bundle exhibits same behavior.

**Comment by Arcanemagus** [comment]
> Ubuntu 18 is running at Python 3.6.5

Tautulli _requires_ to be run through Python 2.7.

> Installed PIP and also have python 2.7 installed.

Are you actually using it to _run_ Tautulli, or do you just have it installed?

> Subzero subtitles bundle exhibits same behavior.

This sounds like you might have further issues on your system than the wrong Python version.

----

Issues are **not** the place for support requests, please use one of the many options available here: https://tautulli.com/#support

**Comment by myplexter** [comment]
Ran it under both versions of python and restarted tautulli. Seems that it is same under both versions. Would help if I knew where the variables may be kept for that field so I can manually add it. Appears to be an issue with how Ubuntu 18 presents those fields?

**Comment by Arcanemagus** [comment]
> Appears to be an issue with how Ubuntu 18 presents those fields?

Since you are seeing the same issue in the "Subzero subtitles bundle", I'm guessing that is the case. Try Chrome or Firefox instead of whatever default browser they have installed there.

Again though, issues are **not** the place for support, so I'll be locking this issue. If you still need help getting this working I'd be happy to chat on Discord about this 😉.
