### ISSUE TITLE
Use https for tautulli.com and cloudinary.com in newsletters

### ISSUE THREAD

**Issue by joshuaavalon** [Tautulli/Tautulli-Issues#86]
**Version:**
2.1.9

**Branch:**
master

**Commit hash:**
8e4aba7ed41eded677cb5e590f4fc352f44f1a4e

**Operating system:**
Linux 4.14.40

**Python version:**
2.7.14

**What you did?**
Send newsletter

**What happened?**

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, 
but requested an insecure image '<URL>'. This content should also be served over HTTPS.
```

**What you expected?**
Load all the things through https

**How can we reproduce your issue?**
Send newsletter

**What are your (relevant) settings?**
N/A

**Link to logs:**
N/A

**Comment by JonnyWong16** [comment]
We tried HTTPS for tautulli.com images, but Gmail refused to show them in some cases, so we had to revert back to HTTP by default. If it works for you, then you can modify the links in your own [custom template](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-custom-template).

Cloudinary images have already been updated to use HTTPS in [v2.1.10-beta](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#newsletter-custom-template). Wait for it to be released.
