### ISSUE TITLE
Collection size calculations incorrect when multi-episode files are in the collection

### ISSUE THREAD

**Issue by DeftNerd** [Tautulli/Tautulli-Issues#87]
**Version:** 

V2.1.11-BETA

**Branch:** 

Beta

**Commit hash:** 	

c19cc858bd35da3c4924ad51a07ffece9183e8f7

**Operating system:** 

Linux 4.15.0-23-generic (#25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 - Ubuntu 18.04 bionic)

**Python version:** 

2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

**What you did?** 

Went to a show library, clicked media info, and payed attention to the reported size calculations of shows in my collection

**What happened?** 

Show size calculations are incorrect when multiple episodes are stored in a single file. For instance, a file entitled *Show Name - S01E01-E02 - Episode Title.mp4* is listed in the database as E01 and E02 with the same file size, and the show size total is calculated using those duplicate size figures. 

**What you expected?**

File size collection calculations should pay attention to the `container` column to ensure that one single file representing multiple episodes is only used once in the size calculations

**How can we reproduce your issue?**

* Go to a TV show library
* Click Media Info
* View a show that has multiple instances of multi-episode files (Often seen with cartoons due to TheTVDB requirements)

**What are your (relevant) settings?**

N/A

**Link to logs:**

N/A

**Comment by JonnyWong16** [comment]
Tautulli currently has no support _anywhere_ for multi-episode files, or multi-part files, or multiple versions of the same media.

This is more of a [Feature Request](https://github.com/Tautulli/Tautulli-Issues#feature-requests) than a bug report.
