### ISSUE TITLE
Other users showing as Local?

### ISSUE THREAD

**Issue by brimur** [Tautulli/Tautulli-Issues#89]
Just curious if this is a known issue or just me. Users other the me are all showing in History as Local

![image](https://user-images.githubusercontent.com/8918706/41024310-cf8b6c88-6966-11e8-8051-de8e3cbb3380.png)

Git Branch: master
Git Commit Hash: 8e4aba7ed41eded677cb5e590f4fc352f44f1a4e
Platform: Linux 4.4.0-127-generic (#153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 - Ubuntu 16.04 xenial)
Python Version: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

**Comment by JonnyWong16** [comment]
GitHub Issues is not for support. Please use the [Discord Server](https://discord.gg/tQcWEUp).
