### ISSUE TITLE
Upgrade to 2.1.12 results error in db

### ISSUE THREAD

**Issue by ning42** [Tautulli/Tautulli-Issues#90]
After upgrade to 2.1.12 I now have a lot of errors in my logs.
I looks like there is a error with the DB it self.
eg

```
Tautulli Database :: Database error: no such column: live
Tautulli Database :: Database error: no such column: live

```

**Version:**
V2.1.12
**Branch:**
master
**Commit hash:**
331be52327cf068e64adb35cbe6f955d723df010
**Operating system:**

Linux 4.2.8 (#1 SMP Mon May 28 06:01:52 CST 2018)
**Python version:**
2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
**What you did?**
Updated to 2.1.12 via webinterface
**What happened?**
Errors in log, can't see any items in libary
Perhaps db is corrupt, but going days back from auto backup, doesn't seem to fix the problem.
**What you expected?**
no errors :)
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18

**Comment by ning42** [comment]
Perfect - thank you, missed that one while looking at the FAQ
