### ISSUE TITLE
Self Hosted Newsletter with image host still pulls generic images from tautulli.com over HTTP

### ISSUE THREAD

**Issue by AevumDecessus** [Tautulli/Tautulli-Issues#92]
**Version:**
V2.1.12

**Branch:**
Master

**Commit hash:**
331be52327cf068e64adb35cbe6f955d723df010

**Operating system:**
Linuxserver.io docker container on CentOS 7
Linux 3.10.0-862.3.2.el7.x86_64

**Python version:**
2.7.14

**What you did?**
Set up a new self hosted newsletter with images uploaded to Cloudinary

**What happened?**
The newsletter generated as normal, all show images were uploaded to cloudinary, however, the header image, and some others, were pulled from http://www.tautulli.com, causing mixed content warnings.

**What you expected?**
All images used should be uploaded to the cloud host if set.

**Comment by JonnyWong16** [comment]
#86

**Comment by AevumDecessus** [comment]
So we must use a custom template to move the random images from tautulli.com, all of which are also located on the tautulli host, instead of tautulli honoring the Image Hosting setting and putting those images on imgur/cloudinary and linking them from there?

**Comment by JonnyWong16** [comment]
Yes, that is correct.
