### ISSUE TITLE
Live sessions are displayed as paused indefinitely after stopped

### ISSUE THREAD

**Issue by aptalca** [Tautulli/Tautulli-Issues#93]
**Version:**
2.1.9
**Branch:**
Stable release
**Commit hash:**
8e4aba7ed41eded677cb5e590f4fc352f44f1a4e
**Operating system:**

Docker
Linux 4.14.49-unRAID (#1 SMP Mon Jun 11 16:21:07 PDT 2018)
**Python version:**
2.7.14
**What you did?**
Started live tv in browser session on plex.tv, watched for a bit and then stopped it
**What happened?**
Hours later, tautulli still displays it as an active but paused live session under the History tab. Stopped tab shows "n/a" for the listing
On the dashboard however, it doesn't show it as currently playing. 
**What you expected?**
I expected the history would display it as stopped, and put in the time it was stopped.
**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**
Can provide on request (they are very large)

**Comment by JonnyWong16** [comment]
This was already fixed back in [v2.1.10-beta](https://github.com/Tautulli/Tautulli/releases/tag/v2.1.10-beta).

Current version is [v2.1.12](https://github.com/Tautulli/Tautulli/releases/tag/v2.1.12).
