### ISSUE TITLE
Can not register tautulli IOS app while https is enabled

### ISSUE THREAD

**Issue by capnhowyoudo** [Tautulli/Tautulli-Issues#94]
**Version:**
v2.1.12

**Branch:**
master

**Commit hash:**

331be52327cf068e64adb35cbe6f955d723df010

**Operating system:**

Linux 4.15.0-23-generic

**Python version:**

2.7.15rc1

**What you did?**
Enabled HTTPS with self signed SSL created by tautulli
**What happened?**
HTTPS with SSL outside of network works on safari, firefox, edge and IE. When going to register new device on Iphone i receive "unable to establish connection to tatulli" i have tried local IP and Public IP I have tried QR code and Manual connection. Issue is not preset if https is disabled. 
**What you expected?**
App to work as it did when HTTPs was disabled. 
**How can we reproduce your issue?**
enable https with self signed cert from tatulli and try to register new device. 
**What are your (relevant) settings?**
Port to tatulli opened on router and accessible from outside network. 
**Link to logs:**

**Comment by Arcanemagus** [comment]
You'll have to contact the author of the iOS app, we have nothing to do with it.
