### ISSUE TITLE
Object doesn't support property or method 'trunc' error

### ISSUE THREAD

**Issue by mtherien** [Tautulli/Tautulli-Issues#95]
**Version:** 
2.1.13

**Operating system:**  
Windows 10 (10.0.16299)

**Python version:** 
Windows 10 (10.0.16299)

**What you did?**
Nothing

**What happened?**
This error is repeated in the logs:
WebUI :: /home : Object doesn't support property or method 'trunc'. (home:881)

**What you expected?**
No error

**How can we reproduce your issue?**
I do not know

**What are your (relevant) settings?**

**Link to logs:**
[tautulli.log](https://github.com/Tautulli/Tautulli-Issues/files/2125631/tautulli.log)

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Issues/issues/24#issuecomment-373242719

**Comment by mtherien** [comment]
I am not using IE.  Errors are being logged when I am not accessing the site from any browser.  I mostly use Chrome.  Is there a log somewhere that can tell me the IP address of what is accessing the site?  I could possibly use this to find the client that may be accessing the site.
