### ISSUE TITLE
TV Episodes Title Does Not Refresh During Autoplay

### ISSUE THREAD

**Issue by LettuceSnob** [Tautulli/Tautulli-Issues#96]
**Version:** 2.1.14

**Branch:** Master

**Commit hash:** `7eee7024b6eac0a858748664878d146bf63623b4`

**Operating system:** `Linux 4.15.17-2-pve (#1 SMP PVE 4.15.17-10 (Tue, 22 May 2018 11:15:44 +0200) - Ubuntu 16.04 xenial)`

**Python version:** 2.7.12

--

**What you did?** Observed the Activity page for active streams.

**What happened?** An active stream is shown with the correct play time, but the wrong episode information is displayed. It's displaying whatever episode was originally played, and does not update to account for follow-on episodes that play when auto-play is enabled.

**What you expected?** That the episode/file information for the active stream would update as a new/different file begins to play

**How can we reproduce your issue?**
1. Use Plex Web interface v3.49.1
1. Remote connect to your Plex Player client (I used RasPlex PHT)
1. Press play on a TV episode within a series/season from the Plex Web Interface
1. Playback begins on Plex Home Theater client
1. Wait until the next episode auto-plays after the original, and the file/episode information does not update in tautulli, but the play time-tracking/duration does.

**Link to logs:** 
1. [Tautulli Log](https://pastebin.com/YA6jqyhd)
1. [API Log](https://pastebin.com/xAAK2p6x)

The specific episode in question was the "Office Olympics" episode of The Office. Plex advanced to play the next episode, "The Fire," but Tautulli made it look as if it were replaying the same "Office Olympics" episode every time a new episode started.

**Comment by JonnyWong16** [comment]
Note: This affects any play queue including playlists.

**Comment by sbeaudoin** [comment]
It occurs also for music items played from a playlist.
