### ISSUE TITLE
Can't use without a Plex ID

### ISSUE THREAD

**Issue by darkf** [Tautulli/Tautulli-Issues#98]
**Version:**

**Branch:**

**Commit hash:**

**Operating system:**

**Python version:**

**What you did?**

**What happened?**

Giving no Plex ID results in " Please authenticate." during setup

**What you expected?**

Allow me to proceed without one, like my Plex server, and use it locally.

**How can we reproduce your issue?**

**What are your (relevant) settings?**

**Link to logs:**

**Comment by JonnyWong16** [comment]
This is not a bug report.

No, a Plex.tv account is required.

**Comment by darkf** [comment]
Well that's stupid, Plex does not require one, it should be able to work locally. 👎
